### ISSUE TITLE
Gas Lift Cannot Be Removed Or Broken Once Used

### ISSUE THREAD

**Issue by KirinDave** [TeamPneumatic/pnc-repressurized#292] opened 2018-12-17 20:34 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2

### Forge Version
14.23.5.2768

### Mod Version
0.8.4-303

### Describe your problem, including steps to reproduce it
Once placed on the ground and used, the Gas Lift cannot be reliably removed. Attempts to destroy it with a pickaxe result in a phantom block (even in SSP). Attempts to remove it with Pneumatic Wrench or a TE5 Crescent Hammer do not have any effect (although a right click with the wrench makes a noise). 

### Any other comments?

This behavior seems a little bit inconsistent. I had to run the device and pick up oil to make it consistently fire.  In some cases, simply placing the block meant I could immediate mine it up in a test world. In other cases, the bug would immediately trigger.

Amendment: I can reproduce this behavior in some cases with the Refinery as well.

**Comment by desht** [comment] 2018-12-18 09:12
I can't reproduce this at all, either with a brand new gas lift, or one that's already pumped a load of oil.  Same for the refinery.  I tried in both my dev instance and a test instance outside my IDE, no problems in any case.

* Any errors in the log?
* Can you try in a test world with no other mods (or at least as few as possible)?

**Comment by desht** [comment] 2019-01-26 12:46
I actually encountered this on the Devcraft server, unfortunately where I can't debug it. And when I tried later, I could break it fine (with the same pick). Very weird.

**Comment by desht** [comment] 2019-02-03 11:17
Exception found: https://media.discordapp.net/attachments/534620189812064256/541577485150715904/unknown.png

**Comment by desht** [comment] 2019-02-03 11:33
Looking at the code, can't see how this NPE is happening.  Nothing at BlockPneumaticCraft line 470 can be null, and that line isn't even reached unless the block is dropped by wrenching it.

**Comment by desht** [comment] 2019-02-16 23:38
Fixed in 0.9.2 release

**Closed by desht** 2019-02-16 23:38 UTC
Labels: Bug, Fixed in Dev
