### ISSUE TITLE
[Suggestion] Mekanism heat compatibilty

### ISSUE THREAD

**Issue by Merlo17** [TeamPneumatic/pnc-repressurized#511] opened 2020-05-30 11:49 UTC
I'm currently on 1.15 and i couldn't help but notice mekanism has a whole set of heat generators, pipes and mechanics. I was wondering if it would be a nice idea to implement some compatibility between the two, to help integrate the mods. Heat transferring especially could help a lot, which mek already has pipes for

**Comment by desht** [comment] 2020-05-30 15:13
That is actually planned already - PNC:R has some Mekanism integration in 1.12, but the Mek API has changed a bit and I need to get it figured out.  That'll happen but I want to get PNC as stable as I can on 1.15 first and get a couple more things into the mod.

**Comment by Merlo17** [comment] 2020-05-30 16:40
Sounds good, glad to hear you're already thinking about it. I haven't really played around with it in 1.12 so I probably could've tested that, but it makes sense it's not a priority. Looking forward to it! ^^

**Comment by desht** [comment] 2020-07-01 10:28
If you'd like to have a play with build 48 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/, this build has Mekanism integration: heat is exchanged between PNC & Mek blocks, and Liquid Hydrogen & Ethylene work as fuels in PNC Liquid Compressors.

Now it's possible that some retuning is needed for conversion efficiency numbers; I did as much testing as I could but the more testing the better.  So if you can find ways of breaking this, I'd be glad to know about it!

Also, there are a couple of values in `config/pneumaticcraft-common.toml` you can tweak, in the "Integration" section:

* mek_thermal_resistance_factor = 10.0
* mek_thermal_conversion_efficiency = 0.01

The first one defines how fast heat can move between PNC & Mekanism blocks.  The second is a straight multiplier for conversion efficiency.  0.01 means 1 Mekanism heat is worth only 0.01 PNC heat.  While this seems really low, it's important to consider that the two mods have quite different standards: e.g. a Mek Fuelwood heater produces 400 heat/tick while burning, but it has a much larger heat capacity than PNC blocks.  Anyway if you need to tweak values, those are the two to look at.  I'd be interested to know how you perceive the balancing with the default values - too good, not good enough, just about right?

**Comment by merlerm** [comment] 2020-07-01 14:41
I'll be sure to do some testing once I find some time, but I'm not sure how soon it will be, since I'm getting caught up with uni stuff :P I'll let you know if I find anything

**Comment by Ridanisaurus** [comment] 2020-07-01 15:08
Hello there.
I tested on build 49 as it was out already, and I can confirm it is working pretty nicely.
However, I'm not sure if the Superheating Element from Mekanism is disabled or not as it doesn't seem to work. 
The Resistive Heater works, but fairly slow, while the Fuelwood Heater works at a decent speed, which I guess is how they are designed to work within Mekanism itself.

Furthermore, the Liquid Hydrogen and Liquid Ethylene also works perfect.

**Comment by desht** [comment] 2020-07-01 16:25
@Ridanis how are you using the superheating element?  It should be inside a boiler multiblock (see https://wiki.aidancbrady.com/wiki/Thermoelectric_Boiler).  I did build one of those, and was able to heat it with a PNC:R Vortex Tube (connected either directly to the boiler casing, or via PNC:R heat pipes or Mek Thermo cables).

Resistive Heater will be very slow at its default 40 FE/t, but you can change that in the heater GUI - give it say 320 FE/t and it will  heat things a lot faster...

**Comment by Ridanisaurus** [comment] 2020-07-01 16:39
Yea, I managed to mess up the boiler multiblock. I can confirm it is also working now.

**Comment by desht** [comment] 2020-07-20 09:16
Closing this.  Mek support is pretty much working, although potentially subject to future rebalancing.

**Closed by desht** 2020-07-20 09:16 UTC
Labels: Enhancement: feature, Response Needed

**Comment by Zazow** [comment] 2024-08-13 14:25
While testing on 1.20.1, I noticed the integration works well when taking heat from Mekanism blocks into PNC blocks (e.g. resistive heater to heat sink using thermodynamic conductors). But Mekanism's thermodynamic conductors can't take heat from PNC blocks (i.e. vortex tube can't output it's heat into a thermodynamic conductor). This looks like a bug to me.

Could you confirm if this is intentional or not? If so, how can I make it work as I would like to use one kind of "heat pipes" in my playthrough.

**Comment by desht** [comment] 2024-08-15 08:19
I'd rather it worked, but there are some fundamental differences between how PNC and Mek handle heat internally, and making this work in both directions turned out to be ... complex. To the point where I don't consider it a priority to fix, sorry.

**Comment by Zazow** [comment] 2024-08-15 23:25
Yeah I totally get it, thanks for the prompt response and maintaining the mod!
