### ISSUE TITLE
Trouble with larger orders from Amadron

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#547] opened 2020-07-11 21:16 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.15.2-1.3.2-49
### Describe your problem, including steps to reproduce it

I seem to be having trouble ordering from Amadron lately. I'm not sure if it's something to do with the total cost of the order, but in my video below I can order 1 emerald for 26 potatoes, but I can't get 10 emeralds. For potatoes right now, the magic number seems to be 4 emeralds. Any more than that and the delivery drone never arrives. It happily takes my payment though. 

Doing a similar test with zombie flesh (32) wouldn't let me buy more than 4 at a time either. 

With a 10 clay to 1 emerald trade, however, I can order much more. I did a trade for 12 emeralds, for instance. But a trade for 13 failed. 

In fact, looking at all of those numbers, it almost seem like trading breaks as soon as the payment goes above 128 items. 

### Any other comments?

https://streamable.com/ijrqcv

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/4907597/latest.log)

**Comment by desht** [comment] 2020-07-13 09:07
Confirmed.

**Comment by desht** [comment] 2020-07-13 15:27
Build 51 should fix this (turns out it was actually a more generic pathing issue, where the drone couldn't find a path to the chest after extracting two stacks of items because it was already there...)

**Comment by desht** [comment] 2020-07-14 15:19
Fixed in 1.4.0 release

**Closed as completed by desht** 2020-07-14 15:19 UTC
Labels: Bug, Fixed in Dev
