### ISSUE TITLE
Heat-frame cooling of molten plastic buckets does not appear to be working

### ISSUE THREAD

**Issue by utoc** [TeamPneumatic/pnc-repressurized#466] opened 2020-05-07 03:22 UTC
### Minecraft Version
1.15.2
### Forge Version
31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-6
### Describe your problem, including steps to reproduce it
A vanilla chest with a PNC heat-frame containing only a bucket with molten plastic does not ever cool/turn in to plastic
### Any other comments?
In-world crafting appears to be fine though :)

See attached screenshots:

![javaw_UwC7dBfmfL](https://user-images.githubusercontent.com/11995956/81251048-09ee0580-8fe8-11ea-8f4f-4b6e6a4ead73.png)
![javaw_YOPQT4HyUy](https://user-images.githubusercontent.com/11995956/81251054-0b1f3280-8fe8-11ea-85d4-f8de8bb297bb.png)
![javaw_B5X3fvLAnd](https://user-images.githubusercontent.com/11995956/81251057-0c505f80-8fe8-11ea-8c07-b46921ad9d41.png)

**Comment by desht** [comment] 2020-05-07 07:47
Confirmed.  I bet you're using a dedicated server here?  This worked for me in dev, but not on dedicated server due to some cached data not getting calculated in time on the server.  Will be fixed in next release.

**Comment by desht** [comment] 2020-05-07 10:34
By the way, I'd recommend replacing those compressed iron blocks with the new Heat Pipes - need less iron, look better (arguably), and they don't exchange heat with the surrounding air!

**Comment by utoc** [comment] 2020-05-07 12:07
Dedicated server is right and thanks for the tip about the heat pipes.  I may have a couple more issues and I'll try them in single player before posting about them.  Thank you.

**Comment by desht** [comment] 2020-05-11 10:15
Fixed in 1.1.2 release

**Closed by desht** 2020-05-11 10:15 UTC
Labels: Bug, Fixed in Dev

**Comment by aetherpirate** [comment] 2020-05-26 21:31
Can confirm this same behavior in 1.15.2 with pneumaticcraft-repressurized-1-15-2-1-2-1-25

**Comment by desht** [comment] 2020-05-26 23:47
Nope, it's working fine in the latest version.  Just tested on dedicated server.

**Comment by aetherpirate** [comment] 2020-05-27 11:49
I must be using them wrong. I will test again and give more info if it's not working for me. Let's close this and I'll make my own thread if need be.
