### ISSUE TITLE
Regulating Pressure

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#500] opened 2020-05-23 10:42 UTC
### Minecraft Version
1.14.4

### Forge Version
28.2.4

### Mod Version
1.0.4-13

### Describe your problem, including steps to reproduce it
Do we still use the Regulator Tube Module to regulate pressure? I set up the following and the low-pressure pipe keeps blowing up.

![4 5bar](https://user-images.githubusercontent.com/4198031/82728591-8e7f9a00-9cf1-11ea-9c27-109d4d83ec3f.png)

The following shows that the tube module is working but has twice the pressure than the attached input tube.
![regulator-tube-module](https://user-images.githubusercontent.com/4198031/82728505-dce06900-9cf0-11ea-808f-addf04cb1625.gif)
The advanced settings are configured to be turned off with a lever
![regulator-tube-advanced-settings](https://user-images.githubusercontent.com/4198031/82728669-372df980-9cf2-11ea-8914-59a5bb734c8f.png)

### Any other comments?
When placing the regulator tube module there is some incorrect rendering of the pipes, the look unconnected but are connected.

**Comment by desht** [comment] 2020-05-23 14:23
In the first image, is the regulator on a basic or advanced tube?

* If it's on a basic tube, the tube will blow shortly after the pressure goes above 5 bar
* If it's on an advanced tube, it regulates to 19.9 bar by default, which means a basic tube after it will blow

So what you'd need to do is either use an Advanced PCB to set the threshold, or give it a redstone signal (signal level 12 regulates to 4 bar). Thinking about it, I wonder if it would be more useful if an un-upgraded regulator always regulated to 4.9 bar?

Regarding the pressure difference in the video, that does look a bit weird, and I can't reproduce it.  But I'll keep this ticket open anyway. 

And as for the tubes looking unconnected, I was sure I'd fixed that (was the module preview leaving bad data on the client TE).  You're still seeing that in 1.0.4? :(

**Comment by desht** [comment] 2020-05-23 15:06
Can you give build 14 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.14/ a go?

Not sure if or how much it will help, but worth a try.  I have not been able to reproduce the tubes showing disconnected in this version - if you have a way of reproducing that, I'd be interested to see it.

Regulators (without an upgrade) will now always regulate to 4.9 (with no redstone signal) even when on an advanced tube.  With the Advanced PCB added, you have full control as before.  Other change is that the regulator won't jump to 7.5 bar when the Advanced PCB is applied anymore, since that will just blow up any attached basic tube.  It now defaults to 4.9 bar.

**Comment by duncanwebb** [comment] 2020-05-23 20:27
Sure, I'll give 1.0.4-14 a go. 

I added an advanced PCB to all the regulator tube modules, they have the yellow tinge. The modules are connected to advanced tubes and either the other end is an advanced tube or a basic tube. Then the pressure was set to 4.9 bars. What was strange is that the regulator worked first time and later stopped working the pressure was the same on both sides.

I made https://youtu.be/iC02sIle5jg showing the various steps I did to set up the network and it shows what was happening. Maybe it helps to reproduce the effects. The regulator controlling the flow to the second network shows the double pressure and this is the second time I've seen this effect. It was also a bit high in 1.12 versions.

**Comment by duncanwebb** [comment] 2020-05-24 09:37
The pressure increase on the regulator that is between advanced and basic tubes may show after a game restart. I saw in the video that it worked when assembled and failed after a game restart. It needed pressure before the game restart.

Something else to try is to place a tube on a vortex tube let it build up pressure, right click the pressure tube with the wrench to disconnect the vortex tube. Allow the vortex tube to normalize and right click the tube again to reconnect it to the vortex tube. What I noticed is either a leak or the pressure in the vortex tube remains low.

Hope this helps, testing build 14 now.

**Comment by desht** [comment] 2020-05-24 09:38
That video is private...

**Comment by duncanwebb** [comment] 2020-05-24 11:39
Sorry, wasn't sure if a scheduled video could be seen by others. I've made it unlisted and will later delete it and replace it.

**Comment by desht** [comment] 2020-05-24 11:45
I do believe I've found the problem (calculation error which caused excess air to be allowed to build up in the tube the regulator is one).  Try out build 15 and see if that helps...

**Comment by duncanwebb** [comment] 2020-05-24 13:57
Will download and test build 15.

I've been testing 14 and there are still some connections that don't quite link together. Mostly happens when right clicking with the wrench to make a stop. Sometime the order matters, e.g. placing down a tube and then a vortex tube or placing down a vortex tube and then a tube.

**Comment by duncanwebb** [comment] 2020-05-24 14:31
Tested build 15 and the regulators are working as expected, even after a game restart. Many thanks again for your efforts and help.

**Comment by desht** [comment] 2020-05-25 13:23
Fixed in 1.0.5 release (and 1.2.1 for 1.15.2).

**Closed by desht** 2020-05-25 13:23 UTC
Labels: Bug, Fixed in Dev
