### ISSUE TITLE
Unable to set Pressure Gauge level with Adv. PCB

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#804] opened 2021-05-12 11:40 UTC
### Minecraft Version
1.16.5
### Forge Version
36.1.16
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.1-184
### Describe your problem, including steps to reproduce it

Place Gauge on advanced tube
Place Adv. PCB on Gauge
Click to enter GUI to set

First, notice it won't let you type decimals. It also doesn't visually save the settings you've set when you leave and come back. It does seem to work still, just limited to whole numbers and blind guesswork

**Comment by desht** [comment] 2021-05-12 14:56
Confirmed.  Wonder when this broke?

**Comment by desht** [comment] 2021-05-12 15:00
Hah.  In this change: https://github.com/TeamPneumatic/pnc-repressurized/commit/84d4251744d5a9fddd2f9e56f3c366bdbfb8be91

Derp on my part, sorry.  *Should* be a very easy fix.

**Comment by MuteTiefling** [comment] 2021-05-12 16:31
Lol, cool. Was going to say, it's pretty recent. Only noticed it in dev last night

**Comment by desht** [comment] 2021-05-12 17:06
This should be fixed in build 185.   Will probably get a 2.12.2 out in the next couple of days.

As an aside though, this build also has all advancements created by datagen rather than manual JSON as before.  All seems to be working (and should be an invisible change for players), but if you wouldn't mind trying this out in a dev world where you already have a bunch of PNC advancements, that would be appreciated :)  i.e. look out for any missing advancement that you previously had, unexpected advancement-get toasts, etc.

**Comment by MuteTiefling** [comment] 2021-05-12 18:30
sure thing, will do

**Comment by MuteTiefling** [comment] 2021-05-12 18:32
~Looks like we might be aiming for an update today. What would be a safe version to roll back to to avoid this one?~

Scratch that, we'll hold till you can update. I'll do some testing tonight and let you know.

**Comment by desht** [comment] 2021-05-12 21:44
That would be cool :)

If testing goes well, I can try to get a 2.12.2 out tomorrow. It's just a couple of fixes over the current release including this one.

**Comment by MuteTiefling** [comment] 2021-05-13 00:04
Yeah, had a full reset there of advancements. 

Before:
![image](https://user-images.githubusercontent.com/9543430/118058750-ea0cc280-b35c-11eb-9bae-fbe274c053cb.png)

After: 

![image](https://user-images.githubusercontent.com/9543430/118058780-fee95600-b35c-11eb-8814-3db702ea15b4.png)

Oddly, I got the Compressed Iron Man and Don't Feel Like Waiting advancements upon logging in, too. I am wearing the armor and had speed upgrades in my inventory, but it seems odd that I could get those since I don't have the ones leading up to it.

**Comment by TeamSpen210** [comment] 2021-05-13 00:13
All advancements work that way intentionally (including vanilla), probably just in case you skip a requirement with clever gameplay, or if any "prerequisite" advancements are added in the future.

**Comment by desht** [comment] 2021-05-13 07:30
Well, that's not good :(  Don't understand why that should happen, the advancement JSONs (or their locations) haven't changed at all, only how they're created.

Update: well, I guess they have changed syntatically (although not semantically).  Which I guess is enough for the game to decide to invalidate them.  I'll roll back to the old advancement JSONs for now, since this is a minor update.  Might need to defer that change for a while...

**Comment by desht** [comment] 2021-05-13 09:41
OK, fixed in 2.12.2 release (which also doesn't have the datagen'd advancements, so no problems there either)

This should be safe to include in the next E6 :)

**Closed as completed by desht** 2021-05-13 09:41 UTC
Labels: Bug, Fixed in Dev
