### ISSUE TITLE
Oil Not Generating

### ISSUE THREAD

**Issue by cyberdragon442** [TeamPneumatic/pnc-repressurized#488] opened 2020-05-17 00:19 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version

1.15.2

### Forge Version

31.1.73

### Mod Version

1.1.2-14

### Describe your problem, including steps to reproduce it

Oil does not seem to generate anywhere in the world (above or below ground). This was inspected by flying around in spectator.

This is potentially a mod conflict. We have several major worldgen mods including:

Terraforged
Quark
Biomes o' Plenty

As well as these other mods that effect land based worldgen (besides just adding ores):

PreGenForge
DungeonCrawl

### Any other comments?

Other odd (possibly related) effects noted:

Water does not seem to spawn outside of oceans either...no surface lakes or cave water but tons of lava underground.

**Comment by desht** [comment] 2020-05-17 06:11
Almost certainly related, since PNC oil uses the same lake gen code that water does. If you can find a world with working lakes and no oil then I'll take a look, but so far none of my test worlds have any missing oil, so I'm going to blame some other mod's worldgen for this.

**Comment by aetherpirate** [comment] 2020-05-17 13:46
![image](https://user-images.githubusercontent.com/11506409/82148892-0138d300-9823-11ea-880c-3a9e634622bf.png)

I'm the server owner having this issue. I can confirm it is a TerraForged issue. Tested without, found oil. Tested with BOP, found Oil. Tested with TerrgaForged, no oil. Found a setting that turns off vanilla water features, turned in ON, found oil.

**Comment by desht** [comment] 2020-05-17 14:23
Looks to me like TerraForged is being overbroad with its blacklisting, then.  I use the vanilla `Feature.LAKE`, but that's about it.  TerraForged shouldn't be assuming that all decorators using that feature are vanilla lakes.

**Comment by desht** [comment] 2020-05-18 15:42
Going to close this, because I don't think there's much I can do here.  There's nothing wrong with using a vanilla feature for worldgen as PNC:R is doing here.

**Closed by desht** 2020-05-18 15:42 UTC
Labels: other mod issue
