### ISSUE TITLE
Logistic Drones losing items

### ISSUE THREAD

**Issue by Golrith** [TeamPneumatic/pnc-repressurized#249] opened 2018-09-04 19:49 UTC
### Minecraft Version
12.2

### Forge Version
14.23.4.2760

### Mod Version
pneumaticcraft-repressurized-1.12.2-0.7.8-259

### Describe your problem, including steps to reproduce it
When using the Requester Frame, drones take an entire stack, but only deliver what is Requested, the rest of the stack will vanish.

**Comment by desht** [comment] 2018-09-05 07:39
Can I a bit more information on your setup:

* What is in your requester frame filter, and how many items?
* What type of logistics frame (active provider/passive provider/storage/default storage) is supplying the items to the requester?
* How many items of that type were in the supplying frame's inventory?
* Does the supplying frame have a filter configured?

**Comment by desht** [comment] 2018-09-05 21:50
OK, I thought I could reproduce it, but turns out I had another nearby chest with a storage frame that I'd forgotten about.  The stack I thought had gone missing was actually in there.

Been trying for a while to reproduce the missing items problem, and I can't:

* Chest with Active Provider, no filter
* Chest with Requester, requesting 8 x dirt
* Put a stack of dirt in the Provider
* Drone moves 8 dirt to the Requester, leaving 56 in the Provider

I can't get the drone to misbehave like you described at all, unfortunately.  I do need to ask, are you certain there wasn't another Storage chest nearby that the drone moved stuff to?

**Comment by Golrith** [comment] 2018-09-06 07:05
Odd. I'll do some further testing. I definitely saw the drone only move from the supplier to the requester and somehow the rest of the stack vanished.

**Comment by desht** [comment] 2018-09-06 20:50
That's very interesting for sure. The type of inventory *shouldn't* matter - we just use regular Forge capabilities - so I'll do some more testing with non-vanilla inventories.

**Comment by desht** [comment] 2018-09-07 09:53
I do believe I've discovered the bug - it only happens with certain inventories, which is why I had trouble tracking it down (vanilla chests, iron chests, IE crates worked fine, but AE2 skystone chests didn't).

Anyway, could you give build 260 from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ a go please and let me know if it resolves your problem?  If that works, I'll get a new release out ASAP.

**Comment by Golrith** [comment] 2018-09-07 20:35
Appears to work perfectly, transfers correctly between metalchests diamond chests, and between vanilla and diamond chest.

Great job!

**Comment by Golrith** [comment] 2018-09-11 19:55
Do you have an eta when 260 will be officially released on curse? Would like to update my modpack.

Many thanks.

**Comment by desht** [comment] 2018-09-11 22:41
Fairly soon, but I'm working on a couple more things before an 0.8.0 release...

**Comment by desht** [comment] 2018-09-17 16:12
Fixed in 0.8.0 release

**Closed by desht** 2018-09-17 16:12 UTC
Labels: Bug, Fixed in Dev
