### ISSUE TITLE
Programmable Controller crashes the server

### ISSUE THREAD

**Issue by vertexofvortex** [TeamPneumatic/pnc-repressurized#998] opened 2022-05-05 01:09 UTC
### Describe the bug

Programmable Controller crashes the server and it doesn't start anymore.

### How to reproduce the bug

I programmed the controller to make some tedious modpack custom crafting (some items should be dropped on the floor and then struck by lightning) and it was working well. After some time, I decided to modify it's program by adding a condition to check a controller's pressure and emit redstone signal to turn on the compressor placed close to it. When I put a Network API with modified program into a controller and changed compressor's redstone mode from high signal to ignored (controller started working), the server crashed and doesn't start anymore.

### Expected behavior

The controller should do it's job, not crashing the server, I suppose.

### Additional details

We are playing Engimatica 6 Modpack with huge amount of mods, so maybe I had to report this bug in it's official repository first, but although I am not a Java developer, I think, this issue is not related to other mods, because, as I see in crash report, there is something about drone pressure condition widget and redstone.

### Which Minecraft version are you using?

1.16

### Crash log

[latest.log](https://gist.github.com/vertexofvortex/ea7e6ed3a82724101cff9e55376d47aa)
[crash-report](https://gist.github.com/vertexofvortex/168116c61cdc97f33f539c346eb3b865)

**Comment by vertexofvortex** [comment] 2022-05-05 01:51
I managed to reproduce this issue in singleplayer, recorded it: https://youtu.be/CcMe5Slq3KM.

[crash-report](https://gist.github.com/vertexofvortex/a9e4242c587a23b7a546a64d83dfa9dc)

**Comment by desht** [comment] 2022-05-05 07:20
Duplicate of #988, already fixed in latest release (2.15.7)

**Closed as completed by desht** 2022-05-05 07:20 UTC
Labels: Bug, duplicate
