### ISSUE TITLE
Shift-clicking items into machines can delete the item

### ISSUE THREAD

**Issue by epiz** [TeamPneumatic/pnc-repressurized#238] opened 2018-08-07 20:48 UTC
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2747

### Mod Version
0.7.5-248

### Describe your problem, including steps to reproduce it
Holding shift and clicking a mouse button while hovering over an item stack deletes most stacks when looking at the Air Compressor, Thermopneumatic Processing Plant or possibly other machine GUI. Does not happen with fuels the Air Compressor can burn.

1. open Air Compressor GUI
2. hover over any item stack that isn't solid furnace fuel, e.g. cobblestone, hold shift and click left or right mouse button
3. stack is gone

I noticed this with the Thermopneumatic Processing Plant, too, when I tried to add coal or redstone even though they should be able to go in the item slot.

### Any other comments?
I can't put items into slots they don't belong if I drag them with the mouse. I can put coal or redstone in the Thermopneumatic Processing Plant by dragging them.

**Comment by desht** [comment] 2018-08-08 15:49
I'm not seeing this behaviour at all.  Shift+left or shift+right clicking items which won't go into a slot simply does nothing, as expected.  And shift-clicking coal/redstone into the TPP works as expected, moving those items into the item slot.

So I suspect some other mod is interfering here but I don't know what.  I would need to have a full list of all the mods you're using to have any idea.

**Comment by epiz** [comment] 2018-08-08 19:43
I created a new Instance with just JEI and PneumaticCraft: Repressurized.
[Demonstration, Modlist, and F3](https://imgur.com/a/d92gU3k)

**Comment by desht** [comment] 2018-08-09 14:39
OK, it's something to do with the Forge version.  v2705 (recommend, and what I've been using for dev) does not have the problem.  v2747 (what you're using) does have the problem.

Not sure if it's a Forge bug or something I was doing wrong that the new Forge exposed - doing some debugging now.

**Comment by desht** [comment] 2018-08-09 18:24
This is caused by a change in Forge 2741+ - https://github.com/MinecraftForge/MinecraftForge/commit/4acfca27f88627a78473a982c004a4a18875e8d4

I'm working on a change that will fix this problem for Forge version both older and newer.

**Comment by desht** [comment] 2018-08-10 06:46
This should be fixed in Forge build 2748 or later, will verify later.

**Comment by desht** [comment] 2018-08-10 07:40
Confirmed fixed in Forge, no PneumaticCraft changes required.  You will need to use Forge 2748 or later.

**Closed by desht** 2018-08-10 07:40 UTC
Labels: Bug, other mod issue
