### ISSUE TITLE
Free Mob Duplication

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#679] opened 2020-12-09 22:49 UTC
### Minecraft Version
1.16.4
### Forge Version
35.1.0
### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.0-88
### Describe your problem, including steps to reproduce it

Bit of an odd one here. When I started out playing with the spawner in this world I couldn't really afford multiple spawner cores, so I just used one to capture odd mobs as I found them for later separation into proper spawners. 

Well, I've got 9 mobs stored up in this spawner and I can't seem to empty it. So it's giving me free mobs every time I right click to release one. 

I am able to empty a core that only contains a single mob. 

### Any other comments?

![2020-12-09_17 44 52](https://user-images.githubusercontent.com/9543430/101697806-7893b580-3a46-11eb-8050-9dd20d50c7f7.png)

NBT Info: item.of('pneumaticcraft:spawner_core', {pneumaticcraft:SpawnerCoreStats:{minecraft:pillager:1,minecraft:cat:1,minecraft:trader_llama:1,minecraft:villager:1,minecraft:wandering_trader:1,minecraft:phantom:1,minecraft:witch:1,ars_nouveau:sylph:1,minecraft:iron_golem:1}}).chance(-1.0)

**Comment by desht** [comment] 2020-12-10 09:23
Weird, I can't reproduce this one (tested in both single player and dedicated server).  The core always gets updated when I use it.

**Comment by MuteTiefling** [comment] 2020-12-15 15:44
Alright, reproduced in a simple test world, just PNC, JEI, and Industrial Foregoing to have an easy mob grinder.

pneumaticcraft-repressurized-1.16.4-2.7.2-86
forge 35.1.13

I used spawn eggs to vacuum up the following:

Cat
Phantom
Pillager
Trader Llama
Wandering Trader
Villager
Witch

I then took the core out and used it over by a grinder in survival mode. 

Originally, I was thinking it was mostly due to a modded entity, but these are all defaults. 

If you've got that commit in a test build I can try it with that too to see if it's fixed.

**Comment by MuteTiefling** [comment] 2020-12-15 15:46
Ah, yeah I see it's in build 90, I'll give it a try and report back

**Comment by MuteTiefling** [comment] 2020-12-15 15:51
Yep, that totally fixed it :D nice job

**Comment by desht** [comment] 2020-12-15 16:15
Ah, good!

**Comment by desht** [comment] 2020-12-17 11:23
Fixed in 2.8.0 release

**Closed as completed by desht** 2020-12-17 11:23 UTC
Labels: Bug, Fixed in Dev
