### ISSUE TITLE
Block Texture Missing or not present

### ISSUE THREAD

**Issue by Mastrcodee** [TeamPneumatic/pnc-repressurized#556] opened 2020-07-25 18:05 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Any other comments? mod is pretty cool otherwise. if you could make a pressureized water hose that would be cool.
![2020-07-25_14 00 20](https://user-images.githubusercontent.com/60452830/88463324-cf299a00-ce7f-11ea-9cdb-d7cb6982c8a1.png)

**Comment by desht** [comment] 2020-07-25 18:52
Try reloading textures with F3+t. There's a known problem where the pressure glass model loader occasionally fails to init, and I've never been able to track it down. If that doesn't help, I'll need to see your full log.

What would a pressurised water hose do?

**Comment by Mastrcodee** [comment] 2020-07-25 18:55
It would be able to put out fire at fast speeds and water plants.

**Comment by desht** [comment] 2020-08-03 16:03
I don't think there's really a place for such a tool.  There's already a Crop Stick from this mod for speeding up crop growth, and putting out fires is a bit too much of a niche for a whole new tool.

Did you try texture reloading (F3+T) to resolve the pressure glass issue?

**Comment by desht** [comment] 2020-08-11 11:09
Closing this.  The problem is resolved in 2.1.0 for MC 1.16.1 (Forge 32.0.108 or later required)

It can't be fixed in earlier versions - requires support from Forge.

**Closed as completed by desht** 2020-08-11 11:09 UTC
