### ISSUE TITLE
Crude Oil not acting like a liquid in world

### ISSUE THREAD

**Issue by Sember225** [TeamPneumatic/pnc-repressurized#1084] opened 2022-09-07 01:38 UTC
### Describe the bug

This is for 1.18.2, It was stated fixing this wouldn't be possible until 1.17 or later. Is it now possible to do?
Thank you for your time.

### How to reproduce the bug

Forge version 1.18.2-40.1.73
The oil generated in the world does not have the physical properties of liquids in minecraft. You can jump in a pool of crude and you phase straight through.  This is a duplicate to [#792](https://github.com/TeamPneumatic/pnc-repressurized/issues/792)

### Expected behavior

Crude to act like water or perhaps even thicker

### Which Minecraft version are you using?

1.18.2

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.4.1-131

**Comment by desht** [comment] 2022-09-07 08:04
Dupe of many other similar issues as you spotted but saw fit to raise yet again.  This will never be fixed in 1.18 or earlier but already works in 1.19.

**Closed as completed by desht** 2022-09-07 08:04 UTC
Labels: Bug, duplicate
