### ISSUE TITLE
Liquid Hopper doesn't fill dropped items (buckets/tanks)

### ISSUE THREAD

**Issue by ElaDiDu** [TeamPneumatic/pnc-repressurized#591] opened 2020-08-25 17:56 UTC
### Minecraft Version
1.16.1

### Forge Version
32.0.108

### Mod Version
2.1.1-14

### Describe your problem, including steps to reproduce it
Liquid Hopper doesn't fill dropped items (buckets/tanks).
1- Place a tank, put fluid in it
2- Place a liquid hopper with its input on the tank
3- Drop an item on the ground at the output

### Any other comments?
Items can input just not output

**Comment by desht** [comment] 2020-08-25 20:17
Confirmed (hopper is looking in the wrong place for items).

**Comment by desht** [comment] 2020-08-25 22:37
Will be fixed in next release.  Note that to fill a bucket, the hopper must be able to move 1000mB of fluid at once (due to how buckets work), which requires 7 speed upgrades.  Modded tanks don't have this restriction.

**Comment by desht** [comment] 2020-09-03 09:02
Fixed in 2.2.0 and 1.4.5 release

**Closed as completed by desht** 2020-09-03 09:02 UTC
Labels: Bug, Fixed in Dev
