### ISSUE TITLE
Helmet's Night Vision can get permanently enabled, flickering endlessly

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#825] opened 2021-06-20 03:06 UTC
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.5-190

### Describe your problem, including steps to reproduce it
Turning off the Pneumatic Helmet's Night Vision sometimes fails. When this happens, the night vision effect starts its decay countdown, after which the effect starts strobing wildly. Taking the helmet off does not resolve the problem, but taking it off and putting it back on does.

This happens to me frequently during gameplay with various other mods installed, usually after just a few toggles, either via keyboard or the Armor GUI. It takes more effort without mods on a superflat world, e.g. the ~30s of dedicated toggling shown below. The Armor GUI shows that Night Vision is disabled (not shown in the video), as does the last HUD output.

https://user-images.githubusercontent.com/83793683/122660125-4628ea80-d144-11eb-9aff-2c960a588719.mp4

### Any other comments?

The problem is easy to work around and wouldn't be worth reporting except that I've noticed something similar with Pneumatic Boots rapidly draining pressure despite having everything turned off. This problem is easier to reproduce, and I hope solving it flushes out other things too.

**Comment by desht** [comment] 2021-06-20 09:00
I can reproduce the night vision problem, and I think I have a fix for it, but it'll need a bit of testing.

No idea about the boots draining pressure though, I've never seen that and can't reproduce it.  Going to need a lot more information to track this one down, i.e. what upgrades you have installed for a start.

**Comment by ghost** [comment] 2021-06-20 14:01
> No idea about the boots draining pressure though...

Don't worry about that, I'll keep working on it. It may be a user error. :) I only mentioned it to justify (to myself) logging this bug.

**Comment by desht** [comment] 2021-06-25 07:11
Fixed in 2.13.0

**Closed as completed by desht** 2021-06-25 07:11 UTC
Labels: Bug, Fixed in Dev
