### ISSUE TITLE
Crash while configuring Elevator

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#490] opened 2020-05-18 20:39 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2

### Forge Version
forge-1.15.2-31.1.78

### Mod Version
1.15.2-1.1.3-18

### Describe your problem, including steps to reproduce it

Had this when I was setting floor names on an elevator. I had two elevator call buttons installed and I hit the Left arrow in the floor naming configuration.

This happened before the elevator was formed. There were no labels on the call buttons, for instance. I then applied a redstone signal to the base and it extended normally and the labels appeared. After this, I could not reproduce the crash. 

### Any other comments?

Large elevators seem unusable at this point. I can't seem to walk through the frames on a 3x3 base, so getting inside is a problem. I can get one block in and hit the button to go up, but I get left behind as it goes up. It all works flawlessly on a 1x1 base, however. 

Crash Report: https://gist.github.com/MuteTiefling/ecda247e8d4592176ebc5d89e76c72e7

**Comment by desht** [comment] 2020-05-19 07:20
Confirmed on both problem reports.

I hadn't actually tested with elevators larger than 2x2 (which do work fine).  Looks like any frames which have no visible struts have a collision box, which is wrong.

**Comment by desht** [comment] 2020-05-19 10:01
Give build 21 a go...

**Comment by MuteTiefling** [comment] 2020-05-19 13:04
Yep. Looking slick. Can't reproduce the crash and a 3x3 elevator is working great now.

**Comment by desht** [comment] 2020-05-25 13:24
Fixed in 1.2.1 release

**Closed by desht** 2020-05-25 13:24 UTC
Labels: Bug, Fixed in Dev
