### ISSUE TITLE
Elevator bases blowing up at correct pressure

### ISSUE THREAD

**Issue by ThatTonybo** [TeamPneumatic/pnc-repressurized#568] opened 2020-08-07 02:36 UTC
### Minecraft Version
1.16.1
### Forge Version
forge-1.16.1-32.0.99
### Mod Version
pneumaticcraft-repressurized-1.16.1-2.0.0-4
### Describe your problem, including steps to reproduce it
When building large elevators, placing multiple bases (to achieve a large, tall elevator base for lifting up and down about 60 blocks) the elevator bases keep blowing up for no reason.
### Any other comments?
I am using one single creative compressor set at 3.0 bar. But it seems they all go to past 7-8 bar as I place them. I have even tried placing them all fully (frames and all) and then adding the 3.0 bar but they always explode. It makes the mod impossible to enjoy and feels like a weird bug.

**Comment by desht** [comment] 2020-08-07 06:52
Yep sounds like a bug. I'll take a look into it. Bear in mind that this is the first alpha release for 1.16, so bugs are gonna happen...

**Comment by ThatTonybo** [comment] 2020-08-07 07:43
Of course, gotta expect bugs to happen. But good that it's known now, appreciate the quick response.

**Comment by desht** [comment] 2020-08-07 08:44
Well, I've done some testing, I can't reproduce your problem at all :(   No matter what I've tried, they behave exactly as I expect them to.  Testing with a 3x3 array of elevators, 4 deep (so max elevation 16 blocks).  Added speed upgrades, volume upgrades, etc., no problem.

Can I see some screenshots (or better yet a video) of your setup?

**Comment by desht** [comment] 2020-08-07 08:45
By the way, 3.0 bar isn't quite enough to run Elevators (it's the absolute minimum, and as soon as they start using air, they'll stall at that pressure, even with a Creative Compressor). I had my Creative Compressor set at 4.0 bar for the test.

**Comment by ThatTonybo** [comment] 2020-08-08 03:59
I've ran mine at 3.2ish which seems ok, but doesn't work for the elevators I make (I'm currently trying a 4x3 elevator with 12 deep to go all the way down from a hill), every time I get close to 4.0 bar or so they start exploding.

I can film a video and get it uploaded though, sure. Might need to give me a bit though as I've got poor internet where I am at the moment.

**Comment by desht** [comment] 2020-08-08 08:08
I'll test with a 4x3x12 elevator too and see what happens.  What upgrades are you using, if any?  And where in the multiblock do you apply the pressure?

**Comment by ThatTonybo** [comment] 2020-08-08 13:49
2 or 3 speed upgrades, but it happens no matter what I put in. And I've tried putting the compressor on all sides, at all Y levels.

**Comment by desht** [comment] 2020-08-09 12:01
I tested a setup of 4x3 & 12 deep, and couldn't get it to explode, tested with various pressures from 3.0 up to 5.0 with the Creative Compressor.  I did notice a little pressure jitter when I adjusted the compressor's level, but that isn't too surprising (there are 12 interconnected elevators all trying to exchange air with each other) and it settled down after a few seconds.

In practice, this sort of setup would also heavily benefit from some volume upgrades, since 12 elevators (with 2 or 3 speed upgrades) will be consuming a lot of air: roughly 70 air/tick per elevator, so ~840 air/tick.  You'll need some serious compressor infrastructure to handle that in survival, but some volume upgrades would smooth out the pressure fluctuations.

(As an aside, the depth of bases shouldn't matter as far as air exchange is concerned, since elevator bases never exchange air vertically with each other.  Each layer of bases below the top layer is only there to increase the vertical of the elevator and doesn't store air itself; only the top layer stores and exchanges air.  Lower layers effectively just proxy the top layer's air handler, which is why connecting pressure to them works).

**Comment by ThatTonybo** [comment] 2020-08-10 00:46
So maybe add volume upgrades to them to make sure they don't have any issues handling the air needed?

One thing I also thought of was mod compatibility - could it possibly be another mod that's affecting it in some small way? I noticed that when the compressor is set to 3.2 bar and I add more elevators, and click on the existing ones, their air gauges spin around pretty wildly (and maybe that's why they're blowing).

**Comment by desht** [comment] 2020-08-10 05:23
You might be on to something there with your last point. I'll check into that.

**Comment by ThatTonybo** [comment] 2020-08-11 07:03
I've recorded and uploaded a video to demonstrate what's happening, using 3.2 bar. Hopefully this helps. https://youtu.be/sPE5uxlOnFc

**Comment by desht** [comment] 2020-08-11 08:40
Well, I can't see anything obviously wrong that you're doing, and there's clearly something weird going on... but I just can't reproduce the problem.  No matter what combination of elevator dimensions I've created, and how much I adjust the pressure, or how many elevators I add or remove from the multiblock, they always stay well-behaved.

I'll keep this open, but right now I have absolutely no way of tracking this down, sorry.

**Comment by ThatTonybo** [comment] 2020-08-11 21:45
Yeah, that's alright. Maybe it'll randomly solve itself somehow, don't know. Thank you for looking into it.

**Comment by Fuggschen** [comment] 2020-09-01 10:07
Heyho we are playing Enigmatica 6 and I tried to build an 3x3 elevator with an height of 6 (for 24 meters). I know how you maybe can reproduce this (https://youtu.be/CyhwbtC3OVw) problem:
1) build the elevator normally without connecting any pipes (3 by 3 and 6 up)
2) build the frames to the maximum height (24 frames for each base)
3) build the elevator caller on 2 floors
4) call the elevator without connecting any pressure pipes _OR_ connect pressure to only one base and call the elevator

We are running all elevators with the security upgrade powered by an liquid pressurizer (we use liquid hydrogen) with security and speed upgrades

Edit: Forge version .108 on minecraft 1.16.1 with mod version "2.1.1-14"

**Comment by desht** [comment] 2020-09-01 11:28
Thanks for reminding me about this one.  There's clearly an air feedback loop going on there, but I've never been able to trigger it myself.  However, something did occur to me...

I've made an experimental change and would be interested to know if it helps.  Can you try out build 28 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ and see if that helps any?

**Comment by desht** [comment] 2020-09-01 11:51
Oh, one other thing: if you also have Immersive Engineering in your pack, this version of PNC requires IE 1.16.1-4.0.0-118 or newer.

**Comment by ThatTonybo** [comment] 2020-09-02 08:22
> 
> 
> Thanks for reminding me about this one. There's clearly an air feedback loop going on there, but I've never been able to trigger it myself. However, something did occur to me...
> 
> I've made an experimental change and would be interested to know if it helps. Can you try out build 28 from [jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16](https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/) and see if that helps any?

Tried this myself and had absolutely no issues that I found previously.

**Comment by desht** [comment] 2020-09-26 13:09
Was fixed in 2.2.0 release

**Closed as completed by desht** 2020-09-26 13:09 UTC
Labels: Bug, Can't Reproduce
