### ISSUE TITLE
Possible issue with Spawner Extractor

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#653] opened 2020-11-17 17:34 UTC
#Minecraft Version
1.16.4
### Forge Version
35.0.18
### Mod Version
1.16.4-2.6.0-70
### Describe your problem, including steps to reproduce it

Got a rather unexpected crash while doing some testing with the Spawner Extractor. 

Steps I took to leading up to this:

1. Place down default spawner
1. Place down a vacuum pump and connected that to my air source
1. Place down the spawner extractor atop the vanilla spawner such that it immediately connects to the pump. 

It crashed immediately upon placing the extractor.

### Any other comments?

Layout was similar to this.

![image](https://user-images.githubusercontent.com/9543430/99425053-5fc53380-28d0-11eb-8daf-bff70182f62e.png)

 I've tried reproducing the issue in a single player world of the same pack and am unable to. This occurred on a server. It's the first time I've tried using it on a server and, unfortunately they have not yet been able to get it running again (admin is offline) so I don't know if I can reproduce it again there. 

Crash Log:

[crash-2020-11-17_17.47.10-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5555101/crash-2020-11-17_17.47.10-server.txt)

**Comment by desht** [comment] 2020-11-17 18:26
Damn, looks like I used a client only method there. I'll get a fix out soon...

**Comment by desht** [comment] 2020-11-18 00:18
Build 71 should fix the problem. I'll get a 2.6.1 release out tomorrow...

**Comment by desht** [comment] 2020-11-18 11:37
Fixed in 2.6.1 release (confirmed working on dedicated server)

**Closed as completed by desht** 2020-11-18 11:37 UTC
Labels: Bug
