### ISSUE TITLE
Lapis multiplication with TPP and Upgrade Matrix Recipe

### ISSUE THREAD

**Issue by dashkal16** [TeamPneumatic/pnc-repressurized#808] opened 2021-05-17 04:10 UTC
### Minecraft Version
1.16.5

### Forge Version
36.1.16

### Mod Version
2.12.2-186

### Describe your problem, including steps to reproduce it
I created an Upgrade Matrix in the Thermopneumatic Processing Plant.
The recipe ran fine, one lapis and a bucket of water made four matrices.
There's an active provider on the right hand side that immediately extracted them.
4 Lapis appeared in my default storage marked chest.

If I grab the output before the provider frame does, I get matrices.

I can reproduce this perfectly in my actual single player game.
The issue persisted across world changes and a full client restart.

### Any other comments?
The bad news:
I cannot reproduce this in my test world.
I cannot reproduce this by sticking matrices in another inventory with an export.
I can't even begin to make a guess as to what's going on.

**Comment by dashkal16** [comment] 2021-05-17 04:13
Bonus.  It specifically has to be 4 matrices being pulled.  I crafted 8 before the frame got it an matrices ended up in the chest.

**Comment by dashkal16** [comment] 2021-05-17 04:17
And it stopped doing it.  So... yeah.  Keep an eye out I guess?  No idea what happened, and by all means just close this if you're not inclined to rabbit hole over it.  I'm just going to keep being confused.

**Comment by desht** [comment] 2021-05-17 08:13
This could be... fun... to track down.  So far I've not been able to reproduce it in my test world.  Are you using drones or modules to do the logistics?

Will keep it open for now since there's probably something going on, even if I can't spot it yet...

**Comment by desht** [comment] 2021-05-17 08:22
Update: actually, I think can I how this would break (although I haven't been able to make it break yet).  If I'm right, it's a super simple fix...

**Comment by desht** [comment] 2021-05-17 09:23
Should be fixed in 2.12.3 (feel free to reopen if you see a recurrence)

**Closed as completed by desht** 2021-05-17 09:23 UTC
Labels: Can't Reproduce

**Comment by dashkal16** [comment] 2021-05-17 17:17
I am no longer able to reproduce this at all.  Thanks!
