### ISSUE TITLE
Trouble Batch Crafting Transistors

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#575] opened 2020-08-14 13:47 UTC
### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
2.0.1-7
### Describe your problem, including steps to reproduce it

If you drop in a large batch of items to craft Transistors, the Pressure Chamber seems to get stuck on the last one. 

At first I thought I was goofing stuff up since I was always doing it manually, but I've recently hooked up a refined storage system to auto craft these and am still seeing the same behavior.

Queue up 64
![image](https://user-images.githubusercontent.com/9543430/90255467-54b2c100-de12-11ea-8bec-2715f4eb3e2d.png)

The craft goes pretty quick, but one is left
![image](https://user-images.githubusercontent.com/9543430/90255565-714ef900-de12-11ea-94e0-34f00d82cc01.png)

If I then go over to the output interface, and switch it from Crafted to All, I get the remaining ingredients out. One redstone, three gold nuggets, and a plastic sheet. It's like it somehow decided it couldn't craft with them

Capacitors work fine, however. As do any other large batch crafts I've tried. Seems to be just the Transistors.

**Comment by desht** [comment] 2020-08-15 08:48
Confirmed.  Didn't happen when I made 21 transistors, but did happen with 22, so something to do with it having over a stack of gold nuggets.  Not sure yet, but I suspect something to do with it deciding there isn't a valid recipe after the first stack of nuggets is used up (and it won't check again for a recipe until there's an inventory change - performance reasons).

If I had to take another wild guess, the capacitors work because they need 2 nuggets and that divides evenly into 64, whereas 3 doesn't.  And I'm guessing the code is looking at the stack of 1 gold nugget and thinking "nope, that doesn't craft anything, I'm done here".

Time to fire up the debugger...

**Comment by desht** [comment] 2020-08-15 10:06
Give build 15 a go, should fix it.  (I was right by the way - the chamber ended up with a stack of 1 nugget and a stack of 2 nuggets and didn't recognise that as 3 nuggets)

**Comment by MuteTiefling** [comment] 2020-08-15 13:53
Super weird. Won't be able to test myself though. Going offline for a bit!

**Comment by desht** [comment] 2020-09-03 09:03
Fixed in 2.2.0  release

**Closed as completed by desht** 2020-09-03 09:03 UTC
Labels: Bug, Fixed in Dev
