### ISSUE TITLE
Drone Area Widget and Place not working too well

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#731] opened 2021-01-30 15:44 UTC
### Minecraft Version
1.16.4

### Forge Version
35.1.37

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.9.4-124

### Describe your problem, including steps to reproduce it
I'm looking at why the greenhouse program written by Tek Stack is not working well in 1.16
original video: https://youtu.be/sGnLgVPfxmE my and video https://youtu.be/Krq0BM_GA_M
program: https://pastebin.com/qLMM2w04

The first thing to notice is that the drone fails to place the sign or aphorism tile, the sign is one block west of the centre chest and the drone should place it on the east side of this block.

![Screen Shot 01-30-21 at 04 05 PM](https://user-images.githubusercontent.com/4198031/106360137-199c3f80-6317-11eb-84b9-608f59ccef3b.PNG)

If you change to place to the west side, then the drone places it correctly on the west side of the block.

![Screen Shot 01-30-21 at 04 31 PM](https://user-images.githubusercontent.com/4198031/106360445-b9a69880-6318-11eb-9c1e-059053e40f10.PNG)

Here is an example for cylinders, black shows missing or added blocks and blue shows a thickness of two instead on one. I would also expect each row to be identical. The program is consistent if the shape is either a hollow cylinder or one cylinder minus a one block smaller cylinder - nice that this is consistent. It is also strange that the north and south sides are identical but do not match the west and east side.

![2021-01-29_15 37 38](https://user-images.githubusercontent.com/4198031/106359213-7eed3200-6311-11eb-9c91-debc0c986076.png)

The done which is a filled sphere minus a one block filled sphere and minus a filled cylinder should result in a one block think spherical dome which needs about 1200 blocks but in the current version it needs 2008 block of glass.

The road is two rectangles three wide and 31 blocks long placed perpendicular to each other. When the drone is placing slabs, then it is placing them on top of each other but four blocks wide. Instead of using place the right click block is used then it works for the first 64 blocks. It then fails as the "hand" of the drone is empty instead of being refilled. I think this is a change in behaviour as I would expect the next inventory slot to be transferred to the "hand".

The centre column should be 3x3x3 but the drone builds a 4x3x3 structure. The program should place down two 3x3x3 box frames.

That's where I am at the moment.

### Any other comments?
There is a duplicate bug with the smart chest with maxed magnet, speed and ranged upgrades. When an item is broken near the chest items can be duplicated. 

There is another duplication bug with the program controller placing an aphorism tile. I swapped over the sides for the sign, so it places the tile on the east side of the chest. The done places the tile correctly, but the program controller duplicates the tile and places two down the two tiles.

![Screen Shot 01-30-21 at 03 47 PM](https://user-images.githubusercontent.com/4198031/106360567-66811580-6319-11eb-9b48-4c86ba169b7d.PNG)

I fully understand if you don't want to do anything about this as it is an old program. However, what it is doing is reasonable and the drone should still work.

**Comment by duncanwebb** [comment] 2021-01-30 16:26
Just saw the jack hammer duplicated
![Screen Shot 01-30-21 at 04 52 PM](https://user-images.githubusercontent.com/4198031/106361005-dd1f1280-631b-11eb-94b7-27d3502eaff4.PNG)

**Comment by duncanwebb** [comment] 2021-01-30 16:27
Forgot to mention that the preview area is no longer working from the drone debugger.

**Comment by desht** [comment] 2021-01-31 09:53
Probably better to have multiple issues for separate problems (aphorism tile placement, cylinder shape, smart chest dupe, programmable controller dupe, debugger area preview).  It gets hard to manage multiple threads in a single issue, but we'll manage this time.

I'll try to take a look at the various problems today...

**Comment by desht** [comment] 2021-01-31 10:30
I think the smart chest dupe issue is probably the same basic problem as #332 (which was drone magnet item duping).  If so, that'll be easy to fix.  Haven't been able to reproduce this dupe, but I can see how it could happen.  I'm also going to add magnet suppression support, which will prevent items on conveyor belts (e.g. Immersive Engineering) or near a Botania Solegnolia, being pulled.

**Comment by duncanwebb** [comment] 2021-01-31 10:49
It's easy to reproduce the dupe bug. Break a drone with 35 inventory upgrades and some magnet upgrades. There is a bug in the greenhouse program in that it imports everything from the chest before starting the clearing section, so the drone is full of items. Once the area has already been cleaned the drone sits by the chest full of items then wrench the drone.

Of course, it could be the drone that is duplicating the items.

Sorry, next time I'll split the issue up to one per each task.

**Comment by desht** [comment] 2021-01-31 11:11
The cylinder area problem seems awfully familiar with #609 which we never quite got to the bottom of.   But I can definitely reproduce this now, so just need to figure out what's going on here...

Update: yep, think I've nailed that one - problem with block raytracing to get the placement context (a lot changed in vanilla since 1.12.2 and some of the drone block interaction code needed to be significantly rewritten to cope).  Also fixed a bug where block place was using no air (now uses 100mL per placement as it used to - sorry!).  And fixed drone's held item not syncing to client when it became empty.

**Comment by desht** [comment] 2021-01-31 11:50
I was able to reproduce and fix the sign placement problem with drones - the drone was ignoring the specified side in the progwidget and using the first side it was able to raytrace to (which was generally what face was closest when it got in range of the block).  Now it will only right-click the exact face of the block that is specified in the progwidget (and if it can't get to a place where it can "see" that face, it won't right-click at all).

I couldn't reproduce the sign dupe issue with the programmable controller (using the same test program I used to fix the orientation problem), but it's very possible the fixes I made there helped with this too.

**Comment by desht** [comment] 2021-01-31 12:05
>  Instead of using place the right click block is used then it works for the first 64 blocks. It then fails as the "hand" of the drone is empty instead of being refilled. I think this is a change in behaviour as I would expect the next inventory slot to be transferred to the "hand".

It doesn't work this way right now (and looking at historical 1.12 & 1.7 code, I don't think it ever did), and this could open a huge can of worms.  As it stands, the drone will only attempt to use the "held" item, which is the item in slot 0 of its inventory.

This is one of the reasons why the right-click widget isn't recommended for block placing.  Fortunately the fixes I made to the cylinder *should* help with this too and make the block place widget work as expected.  I will be pushing a build shortly for you to test out...

**Comment by desht** [comment] 2021-01-31 12:07
> Forgot to mention that the preview area is no longer working from the drone debugger.

I can't reproduce this one.  It's working fine here...

**Comment by desht** [comment] 2021-01-31 12:20
Give build 130 a go when you get a chance...

**Comment by duncanwebb** [comment] 2021-01-31 13:00
Wow! That was rapid. I'll give build 130 a try after lunch :-)

**Comment by duncanwebb** [comment] 2021-01-31 18:04
Amazing, the building is perfect, many thanks.

Haven't reproduced the duplication bug again.

It is strange that the positions are shown for you and not for me, could this have something to do with variables?

The build ran out of dirt and glass
![2021-01-31_18 21 56](https://user-images.githubusercontent.com/4198031/106392264-4fadf200-63f1-11eb-8435-94ca4c6b4dcd.png)

I still have a problem placing the aphorism tile, can't get this to place either at all or randomly.

The other part that does not work is placing the water, not sure quite why. The drone imports the four water buckets correctly and places a bucket at a time and then puts the empty bucket in the chest. The positions are 6, -1, 6 from the chest. In this image, I renamed the positions. I'm sort of surprised that this worked in the past as you say the inventory slot 0 is not automatically replaced.

![Screen Shot 01-31-21 at 06 13 PM](https://user-images.githubusercontent.com/4198031/106392084-9e0ec100-63f0-11eb-9e01-9c3967b1b6a0.PNG)

Again many thanks.

**Comment by desht** [comment] 2021-02-01 08:42
> I still have a problem placing the aphorism tile, can't get this to place either at all or randomly.

I had no problems placing a tile - Right Click Block widget, use "Click Item" mode, choose the side of the block, and make sure the "Sneaking" box is checked if the block has a GUI, like a Chest.

**Comment by desht** [comment] 2021-02-01 08:44
> The other part that does not work is placing the water, not sure quite why. The drone imports the four water buckets correctly and places a bucket at a time and then puts the empty bucket in the chest. The positions are 6, -1, 6 from the chest. In this image, I renamed the positions. I'm sort of surprised that this worked in the past as you say the inventory slot 0 is not automatically replaced.

I could be reading the old code wrong.  I will take a look at the right click code again and check the feasibility of auto-equipping the filtered item...

**Comment by desht** [comment] 2021-02-01 09:29
Not sure how that program worked before.  What it appears to be doing:
* Import 4 water buckets (OK)
* Right-click hole 1 - fills it, because it's holding a water bucket (OK)
* Export an empty bucket to the chest (OK)
* Right-click hole 2- nothing happens!  Because there's no item filter, the drone just right-clicks with an empty "hand", which is a valid operation.

I've updated the code to check for and swap in (if necessary) a valid item, and added a "water bucket" item filter to the right-click widget.  Now it *almost* works, but seems to fail unpredictably - I think the problem might be that the drone can sometimes dip into the block space it's trying to click the bucket in, and that messes things up a bit.

The *best* option is probably a water tank with 4 buckets of water in it, and use the drone liquid import and export widgets to fill the holes...

I appreciate this has changed quite a bit since 1.7.10 days when this program was written, but unfortunately vanilla code around block interaction is also very different these days, and drones do need to work with that to a large degree.

**Comment by desht** [comment] 2021-02-01 10:43
Update: with a little more tweaking, I think I have the drone now reliably placing water bucket, with the position of the air block in each hole (i.e. existing functionality).  It wasn't a positioning problem, just a little bug in the code I'm adding.

So next build should handle the existing program reliably...

**Comment by desht** [comment] 2021-02-01 10:56
> It is strange that the positions are shown for you and not for me, could this have something to do with variables?

Yep, I think you're right there.  A drone's variable values aren't sync'd to client, and there is no variable manager object client-side.  Again, I think this has always been the case, at least from looking at the original 1.7.10 code.  It *might* be possible to add this, but performance is a concern (needing to sync the variables of a debugged drone on a regular basis...).

**Comment by desht** [comment] 2021-02-01 12:02
Build 131 should handle water buckets a lot better...

**Comment by duncanwebb** [comment] 2021-02-01 14:47
There is another way to place buckets and this is like this, it might use fewer pieces:
![image](https://user-images.githubusercontent.com/4198031/106473673-56497180-64a4-11eb-8b6d-a3c4a4a3c927.png)
However, with build 131 the drone drops into each hole and doesn't place the water.

Didn't know that you can export fluids into the world, will have to try that, thanks.

**Comment by duncanwebb** [comment] 2021-02-01 15:00
Still have a problem placing the tile, this is what it is doing, and it doesn't matter if either east of west side is used. I've tried right click item and block with and without a filtered item.

https://user-images.githubusercontent.com/4198031/106474221-f901f000-64a4-11eb-8838-ceecb8c09b19.mp4

The code is:
![image](https://user-images.githubusercontent.com/4198031/106474645-6ada3980-64a5-11eb-9eed-bdb028ed906e.png)

**Comment by desht** [comment] 2021-02-01 15:09
> However, with build 131 the drone drops into each hole and doesn't place the water.

I believe the Right Click widget needs a filter of a water bucket there.  Otherwise it will attempt to just right-click the block with whatever it's holding at the time - and if it's just dropped an empty bucket off, that will be an empty hand.  By adding a filter piece of a water bucket, you're forcing the drone to find a water bucket in its inventory and equip that before right-clicking.

> Still have a problem placing the tile

The problem here I think is that the drone is trying to right click the block adjacent to the chest, i.e. the air block.  It should be sneak-right-clicking the chest itself, same as you would if you were trying to place a sign on a chest.

**Comment by duncanwebb** [comment] 2021-02-01 17:48
Thanks, can't get it to work, here's a test program https://pastebin.com/knRZUXbf and this is what it does.

https://user-images.githubusercontent.com/4198031/106497035-dd571380-64bd-11eb-8403-659503e1d8a1.mp4

Seems to double right click, no idea what it is doing with the tile.

**Comment by desht** [comment] 2021-02-01 17:57
Problem with the tile is you have "Click Block" when it should be "Click Item".

**Comment by duncanwebb** [comment] 2021-02-01 18:04
Already tried Click Item and Click Block for both the tile and the water buckets, unfortunately it doesn't place the tile or the water.

**Comment by desht** [comment] 2021-02-01 18:12
Yeah, found another little problem - raytracing again; the drone is above the chest, so can't see the east side.  But it's close enough that it doesn't think it needs to move.  I think I can fix that easily enough so I'll push another build shortly.

Your test program worked fine with placing the 4 water holes, though.  The drone dug out and filled all 4 holes as expected.

**Comment by desht** [comment] 2021-02-01 18:14
Build 132 will be ready momentarily...

**Comment by duncanwebb** [comment] 2021-02-02 14:34
Placing the sign now works as expected. Many thanks again.

Placing water buckets doesn't work. The green house program right-clicks the bucket on the top of the block on the floor of the water hole. What is happening is that the drone places the water bucket in whole and then drops into the hole and voids off the water.

What I have also tried is to right-click item and right-click block on the north side of the block south of the hole. 

![image](https://user-images.githubusercontent.com/4198031/106614259-64ae9080-656b-11eb-9801-f6efc3ff7784.png)

As an aid, the right click puzzle price could show which side is being clicked and if sneaking.

Right-clicking does seem to be a bit of a problem, it will right-click wheat seeds and potatoes but not melon and pumpkin seeds, which is really strange.

**Comment by desht** [comment] 2021-02-02 14:58
I honestly don't know.  It works fine for me (right-clicking filled bucket into the hole position itself, that is).  I think when I tried clicking the side of a block in the hole, it didn't work very well (probably because the drone is in that block space already).

Update: yeah.  the changes I made to get sign placement working broke water bucket placement :(  Alright, let's see if I can find a way to get both working...

**Comment by desht** [comment] 2021-02-02 17:26
Build 133 might be the charm... who knows!

**Comment by duncanwebb** [comment] 2021-02-02 19:07
This is the drone click item on the block below the hole

https://user-images.githubusercontent.com/4198031/106649459-e9aca080-6591-11eb-8588-4734613a7d4e.mp4

This is the drone click item in the hole

https://user-images.githubusercontent.com/4198031/106649467-eb766400-6591-11eb-8b80-57e431032304.mp4

**Comment by duncanwebb** [comment] 2021-02-02 19:11
https://pastebin.com/Ytb4CWRP this is the program for the second video.

![image](https://user-images.githubusercontent.com/4198031/106650054-b7e80980-6592-11eb-9177-d24c25ca87b1.png)

Maybe you have a test program?

**Comment by desht** [comment] 2021-02-03 08:44
This is the program I'm using, which works fine for both placing the Aphorism Tile and filling the water holes: https://pastebin.com/PqjQaXcv

**Comment by duncanwebb** [comment] 2021-02-03 10:56
Figured it out...

![Screen Shot 02-03-21 at 11 51 AM](https://user-images.githubusercontent.com/4198031/106737042-8284ff80-6616-11eb-9b94-a972c3931549.PNG)

Not sure why this drone has three security upgrades, normally I have only one per drone.

Very sorry about that.

**Comment by desht** [comment] 2021-02-03 11:53
No worries, it happens!  Good to know my code isn't broken after all :)

Would you consider this issue resolved?  Did we miss anything?

**Comment by duncanwebb** [comment] 2021-02-03 13:58
![2021-02-03_14 18 56](https://user-images.githubusercontent.com/4198031/106755596-98062380-662e-11eb-8caf-ecbf77da648d.png)

Almost but the water is placed one extra block away from the centre with the program controller, I moved the water blocks in the above picture.

![2021-02-03_14 45 16](https://user-images.githubusercontent.com/4198031/106755756-cab01c00-662e-11eb-8ffa-945819d62085.png)

The only other thing that bothers me a little is placing down the tile. Drones are not like players in that they can place anything anywhere in an air block, such as the diagonal glass in the dome. 

So, the drone should be able to place the tile on any face of an air block. The reason is that it make the position on the sign trickier than it needs to be. We need two positions, the block to place the tile against and the position on the tile to write on.

Thanks again and thanks for your patience.

**Comment by duncanwebb** [comment] 2021-02-03 17:24
I know how to fix this, by right-clicking the bucket on the top of the block below the water source.

![image](https://user-images.githubusercontent.com/4198031/106784877-196cae80-664d-11eb-875f-c6dc7d4fdac4.png)

**Comment by duncanwebb** [comment] 2021-02-03 17:30
https://pastebin.com/LneqsDW9 Greenhouse for 1.16

**Comment by desht** [comment] 2021-02-04 10:06
Excellent.  Yeah, it actually makes more sense to right-click the bucket there.  The whole right-click (and place) system has changed a bit, both in 1.12 and again in 1.16, due to the way vanilla has changed the system (to actually do stuff as a fake player, I need to go through the same raytracing procedure as a real player would).  So it has been a bit of a pain to get working reliably, and a lot of stuff still feels a bit kludgy there.

I'll take a look at the place code too and ensure there's a way for drones to continue placing blocks in mid-air.

**Comment by duncanwebb** [comment] 2021-02-04 21:10
I tested the placement of signs as well as the tile, they work flawlessly.

The greenhouse built correctly and may have uses less blocks than the original.

Thanks again.

**Comment by desht** [comment] 2021-02-08 09:51
Fixed in 2.10.0 release

**Closed as completed by desht** 2021-02-08 09:51 UTC
Labels: Bug, Fixed in Dev
