### ISSUE TITLE
Aerial Interface can't seem to charge armor

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#469] opened 2020-05-07 16:14 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-8
### Describe your problem, including steps to reproduce it

I've got a charging module pointed into the bottom of the aerial interface and it just won't charge my armor. Also, the Side selection may be bugged. I had originally configured it to be Back for Armor and that kept charging the inventory as well. 

### Any other comments?

Interfacing through the top does seem to get my armor charged.

**Comment by desht** [comment] 2020-05-08 09:00
Yeah, something is screwy with the side configuration.

**Comment by desht** [comment] 2020-05-08 09:21
Are you testing on a dedicated server?

I ask because I can reproduce the problem on my dedicated test server, but not in my IDE environment (yeah, one of those bugs...)

**Comment by MuteTiefling** [comment] 2020-05-08 14:22
single player, not open to LAN

**Comment by desht** [comment] 2020-05-08 14:35
Should be fixed in build 11+

**Comment by desht** [comment] 2020-05-11 10:14
Fixed in 1.1.2 release

**Closed by desht** 2020-05-11 10:14 UTC
Labels: Bug, Fixed in Dev
