### ISSUE TITLE
Drones won't filter items by NBT that don't currently have NBT

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#559] opened 2020-07-31 04:05 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.4.0-53
### Describe your problem, including steps to reproduce it

I was hoping to use a drone to move tanks of plastic into a cooling chest. I had thought I'd pick up empty tanks from an inventory, click it on the TPP to fill it with plastic, then drop it in the cooling chest. I'd then have the drone sit and wait until it found an empty tank in the cooling chest. Once it finds it, it should pick it up and turn off the cooling.

The trouble is, I can't filter by NBT if the item has no NBT. So I can't differentiate between a full and an empty tank. 

### Any other comments?

![Capture](https://user-images.githubusercontent.com/9543430/88998713-aca0e200-d2c0-11ea-8044-11ead4dfae4b.PNG)

My current workaround to this is to have a smart chest pulling plastic and tanks from the cooling chamber. I then leave a spare empty tank in that smart chest and lock all of the slots. This way the only place that can accept a tank is one that has one in it already, so if it can't stack, it can't pull. 

On a side note, I notice that the smart chest seems to get 'stuck' when pulling. If it decides it wants to pull the tank, it will never pull plastic until it has successfully pulled the tank. Seems like it should try, fail, and simply move on to the next inventory slot.

**Comment by desht** [comment] 2020-07-31 09:44
Try build 59.

I couldn't reproduce the Smart Chest getting stuck - I created a chest allowing 64 plastic and 1 small fluid tank, and nothing else, set to pull from an adjacent chest.  It behaved itself no matter what combination of plastic and tanks I left in the adjacent chest, the smart chest happily pulled whatever it had space for.

**Comment by MuteTiefling** [comment] 2020-07-31 11:48
Confirmed fixed. 

Test program: https://gist.github.com/MuteTiefling/314de0c913221d9cc176739437d5e612

Drone in action: https://streamable.com/gxyzjm

I can also no longer reproduce the Smart Chest thing, so that's good too! 

Thanks!

**Comment by desht** [comment] 2020-08-06 17:03
Fixed in 1.4.3 release

**Closed as completed by desht** 2020-08-06 17:03 UTC
Labels: Bug, Fixed in Dev
