### ISSUE TITLE
Items vanish while using logistic drones/ programmable controller

### ISSUE THREAD

**Issue by gamelnderGamler** [TeamPneumatic/pnc-repressurized#244] opened 2018-08-18 16:16 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
forge-14.23.4.2729
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.7.6-254
### Describe your problem, including steps to reproduce it
I wanted to built a lot of solar arrays from environmental Tech with a programmable controller. since it contains of different blocks, i used logistic drones and a requester frame to get the right ammount of different blocks into the programmable controller. I had enough ressources for 100 solar arrays, but after 10 i missed the first blocks. (the first missing blocks are on the bottom of the arrays. (
![solar arrays1 1](https://user-images.githubusercontent.com/22398257/44300859-dcda5a80-a30d-11e8-843a-fa08600e33f9.PNG))

I tried to pipe items out of the programmable controller, but there werent any.
So somewhere something lost the items. 
I had definitive enough items in the AE system (17k solar cells, 5600 frames etc.)

The logistic frames were mostly black when i put them on the inventorys and flickered some time between the right color and black. (
![logistic1 2](https://user-images.githubusercontent.com/22398257/44300839-8a00a300-a30d-11e8-88d3-826e814d84fe.PNG))
When i came back after a while they were mostly the right color, but still flickered between black sometime. (i didnt screenshot it). After a reelog they are back to black again. 

I have a Request Frame:
![requester1 1](https://user-images.githubusercontent.com/22398257/44300898-802b6f80-a30e-11e8-9cda-f9dc3feafa92.PNG)

 on the programmable controller, A passive provider Frame on the me Interface wich looks like this: 
![interface1 1](https://user-images.githubusercontent.com/22398257/44300878-304ca880-a30e-11e8-9383-1ae5409496c4.PNG)
and a default storage frame on an empty interface right next to the other interface.

I tried to reproduce the bug by puting cobblestone and redstone into the controller, but i couldnt do it. Maybe if i would start the programm with different materials. maybe i lose some there too. 
I used this programm: (https://pastebin.com/ggZk4DPJ  to use it in a programmable controller, only set a new "start" coordinate)

I dont know what the problem is/was but the black logistic frames were odd, so i pointed them out. But cant know if they are the problem. maybe because they are only black because of other mods i have on the server. 

### Any other comments?
A friend said, it could be that the arrays are above the world spawn, but we can built there so i dont think thats a problem.
Iam really sorry that i couldnt reproduce it. 
So dont feel forced to do something about it.

**Comment by gamelnderGamler** [comment] 2018-08-18 20:29
Update:

Our server performance went down and we had huge fps drops near a certain area. 
We had this since shortly after my items vanished. 
After that i had a dig programm in a programmable controller wich was digging with a Draconic Staff of Power.
At first i was wondering, that the drone wasnt droping items while digging blocks, but i thought maybe they void the stuff wich were dug. But then we found this at the spot with the fps drops: 
![random items](https://user-images.githubusercontent.com/22398257/44302905-f04bec80-a332-11e8-90e6-dc9aabbb0308.PNG)

The black balls are the stuff wich lies on the ground after you use the Draconic Staff of Power to dig blocks. But they werent droped near the programmable controller wich dug a area, they were teleported to the coordinate -38, 69, 221 from the diggin area: 544, 79, -336 X 505,100,-410  and felt to the ground there and made masive laggs. (diggin program: https://pastebin.com/gu8wTgfa)
Thats quite far away.

If i use other tools for diging, the programmable controller throws the items on the ground, like it is supposed to be. Only with the Draconic Staff of Power the item "teleports" away.

I dont think this is draconics fault, since my solar stuff vanished aswell. I cant prove that the solar stuff went there too, since the item despawned before we found the laggy spot, but the laggs before are a indicator. 

We used pneumaticcraft drones and stuff in the area where the items get teleported too aswell.

I have absolutly no clue whats going on, but it took us some time to find this xD

The client consol (dont know how it is called) had a lot of this errors: "pneumaticcraft | main | error | No Area type found for id ''! Substituting Box!"
Dont know if that error has something to do with the problem tho.

So the logistic drones should be fine. Looks like a problem with the programmable controller?

**Comment by gamelnderGamler** [comment] 2018-08-19 13:04
Update: 

The description of the Programmable controller says, that it can by default transfer one stack of items. (max Dispenser upgrades = 35 so max 36 stacks)
But iam able to pipe 37 stacks into the programmable controller without any dispenser upgrade. 
If i put more than 1 stack into the programmable controller without any dispenser upgrade i get the error again. (pneumaticcraft | main | error | No Area type found for id ''! Substituting Box!)

With 35 dispenser upgrades i can also put 37 stacks in the controller, but i dont get the error.

Dont know if this has something to do with my vanished and teleported items, but it should at least be a pneumaticcraft bug xD

**Comment by Sewef** [comment] 2018-08-20 06:53
Haven't play with the Programmable Controller for a while, but nothing changed since, so...

→ The Fake Drone (drone made by the Programmable Controller) uses the tool you piped in to dig
→ If there's no space in the Drone Inventory (there's only 1 slot without Dispenser Upgrade), the dug blocks will drop on the floor, as if a player break the block
→ You can pipe items in and out from the Fake Drone inventory through the PC (haven't tried this, only piped the tool)

**Comment by desht** [comment] 2018-08-20 11:37
I'll be spending some time on the Programmable controller as the next major bit of work to be done on the mod. Looks like there are some issues to get to the bottom of...

**Comment by desht** [comment] 2018-08-23 12:33
Update: think I can see where some of these problems are coming from.  There should be a dev release in the next 24 hours or so.

* Programmable controller's fake player inventory isn't smart enough right now.  Can use the same code as the actual drone's fake player here.
* Draconic staff dropping item cores in odd places: yeah, the fake player's position isn't getting updated to the controller's fake drone position.  Easy fix.
* Odd logistics lighting.  This is probably due to a recent change I added to stop logistics (and heat) frames looking unnaturally bright in low-light conditions. Seems for some reason your client thinks those blocks (that the frames are on) have a light level of 0.  I've spent some time on this and can't reproduce it in my test worlds.  I might add a client-side config setting to disable this, in case of problems like this.

**Comment by desht** [comment] 2018-08-24 15:08
Can you give build 258 a go please?  I've made quite a few changes to how the P.Controller handles its inventory, which seems to working well here, but I haven't tested as heavily as I could yet.  Would be good to know how that works in your more demanding setting...

Also, the Staff of Power should now drop the item cores at the digging position, not some random place in the world.

And if your logistics frames are rendering weirdly, you can set 'B:semiBlockLighting' to false in your config (client side setting).

**Comment by desht** [comment] 2018-08-28 19:02
0.7.8 is out now, should hopefully fix your problems. Please let me know...

**Comment by gamelnderGamler** [comment] 2018-09-05 17:50
Sorry, i was a bit bussy lately, i will test the new version and give feedback as soon as iam done.

I just did read the bug from golrith with losing items. I think my first problem was the same. I tried to reproduce, but only with "vanila" items and it was working with them. Should have done it with mod items, but they were quite expensive and i wasnt in creative :/

**Comment by desht** [comment] 2018-09-05 21:43
Actually, I can reproduce Golrith's problem with just dirt, so that's about as vanilla as it gets :)  Looking at it now...

**Comment by gamelnderGamler** [comment] 2018-09-06 16:56
As far as i have seen the bugs are all fixed. 

- The controllers inventory size is as big as it should be.

- If iam using the Staff of Power the items are getting droped on the ground as they should.

- If i set the Lighting to false i get the colors on the frame.

So thank you a lot :)

I only found 1 minor thing:

If i use a dig programm with a controller and i take the api with the programm out of it while it is mining a block, the red "digging laser" wont disapear and the controller will continue to dig the last block. After it has finished the laser is still there.

Just wanted you to know since i was writing something anyway ;-)

![digging1](https://user-images.githubusercontent.com/22398257/45172528-e4529c80-b205-11e8-9ac5-b8bfac219d79.PNG)

**Comment by desht** [comment] 2018-09-07 10:05
Think I may have tracked down your older items-disappearing problem - see #249 

I'll take a look into that phantom laser problem in the next day or two, shouldn't be hard to fix, hopefully.

**Comment by desht** [comment] 2018-09-17 16:12
Phantom laser & logistics item loss fixed in 0.8.0

**Closed by desht** 2018-09-17 16:12 UTC
Labels: Fixed in Dev
