### ISSUE TITLE
issues with Collector drones

### ISSUE THREAD

**Issue by KrAzYGEEK32** [TeamPneumatic/pnc-repressurized#569] opened 2020-08-07 10:07 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.88
### Mod Version
2.0.0-4
### Describe your problem, including steps to reproduce it
collector drones seem to randomly teleport short distances even if they have clear way to proceed,
![2020-08-07_02 34 56](https://user-images.githubusercontent.com/59537798/89634689-66044680-d8c3-11ea-892f-26db2bc9aa11.png)
in this pic, the drone randomly teleported two blocks to the left (as seen by the trail), and this occurs frequently, and in random spots, 
one more issue is with inventory upgrades for collector drones
those dont seem to change the collection behavior of the collector drone, it still picks up only one type of item, and only picks another kind after depositing the first type.
### Any other comments?
i dont know if the second issue is a bug or not, but it would definitely be nicer if it filled its inventory before proceding to deposit the items

**Comment by desht** [comment] 2020-08-07 13:24
I'd guess the drone is having problems pathfind back to the chest in the centre (I presume that's where you deployed the drone - also, which face of the chest did you click when deploying the drone?)

Inventory upgrades should be having an effect, so I'll double-check that as well.

**Comment by desht** [comment] 2020-08-07 13:47
Inventory upgrade issue was indeed a bug, and is fixed in dev now.

I was able to reproduce the pathing problem by throwing items on top of a wall - I'm guessing maybe some harvested items are landing on top of your wall there?  I'd guess the drone is getting confused about the wall's bounding box - I should be able to debug this now I have a way to reproduce it.

**Comment by desht** [comment] 2020-08-07 15:00
Yep, definitely wall (and fences, and indeed any "tall" block - i.e. collision box with a maxY > 1.0).  The drones hate trying to pathfind to the space above those blocks - for some arcane vanilla reasons which I can't figure out (vanilla pathfinding is really complex, and not well deobfuscated).

But I think I have a decent workaround by just allowing the drones to stop short of the face directly above the wall/fence.  They'll still be able to pick up items there, so that should be fine.  Need to do a lot of testing since this could possibly have knock-on effects, but hopefully the problem will be solved.

**Comment by KrAzYGEEK32** [comment] 2020-08-07 15:39
Yea now that you mentioned it, it seems like walls cause this a lot, thanks for the quick response and I'm happy to have helped :)

**Comment by desht** [comment] 2020-08-11 10:57
Fixed in 2.1.0 release

**Closed as completed by desht** 2020-08-11 10:57 UTC
Labels: Bug, Fixed in Dev
