### ISSUE TITLE
Framerate crippled after using compression chamber

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#258] opened 2018-10-13 20:58 UTC
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.7.8-259

### Describe your problem, including steps to reproduce it
Just starting out with Pneumaticraft, I have build a 3x3x3 compression chamber as my first machine. It has two interfaces on opposing faces, one in, one out. It also has a valve on the third face and a glass on the fourth. The rest is standard walls. From the valve, there are two pipes leading to a normal, coal-fired air compressor. Finally, there's a hopper and a chest for the interfaces. The system is pressurized to 4 bar, and the compressor is not running (no fuel).

Whenever the compression chamber processes something, my framerate takes a nosedive. It goes from being capped at 70, all the way down to 10. And it keeps dropping down there whenever I look anywhere near the chamber, even long after it has stopped processing. The only "safe" direction, where my framerate is normal, is looking directly away from it.

Relogging fixes the problem. I can then reproduce it effortlessly by putting another piece of iron into the chamber. One item processed -> the problem is back.

### Any other comments?
This is a singleplayer world.

Modlist: https://pastebin.com/PWfyeFz2

**Comment by desht** [comment] 2018-10-14 09:33
I haven't been able to reproduce this.  I did add some performance improvements to the pressure chamber in 0.8.1, but they're really server-side efficiency improvements.  Would be interested to see if it helps any (although I suspect not).

When your FPS drops, is it due to the item conversion, or the item extraction, I wonder? If you disable the extracting interface (e.g. by making it only run on a redstone signal or giving it an unmatchable filter), do you still see an FPS drop?

**Comment by lOmicronl** [comment] 2018-10-14 10:16
First test: exporting interface set to only accept cobblestone.

Result: the FPS drop indeed happens when the interface exports. A piece of iron was turned into compressed iron without problems, but as soon as the filter in the interface was removed and it pushed the ingot into the adjacent chest, FPS plummeted.

Second test: Removed Sound Filters, SmoothWater, Mo' Bends, ItemZoom, FastWorkbench, FastFurnace, Dynamic Surroundings, Cloud Control, Better Foliage

Result: FPS drop still happens. However, because there is less load on the renderer, FPS now only drops to 40 instead of 10.

Third test: reactivated all those, removed Serene Seasons instead.

Result: FPS drop to 17.

Further tests are ongoing...

**Comment by desht** [comment] 2018-10-14 12:38
Yeah, that is very weird.  The interface itself doesn't do any special client-side rendering, although there is a TESR attached to the primary pressure chamber valve to render items in the chamber (but that doesn't sound related - your FPS is fine with items in the chamber before extraction).

I'll try and do some testing with OTG/BB and see if the slowdown is in PNC:R or elsewhere - if elsewhere, you might need to take it up with the OTG folks.  I'll let you know anyway...

**Comment by desht** [comment] 2018-10-16 07:54
I've just tested with Forge 2757 and OTG 1.12.2-v6, and... no slowdown.  FPS stayed at a constant 60fps before, during and after the pressure chamber did its work.  (I know you said 2760, but I had 2757 installed, and none of the next 3 versions actually changed anything in code).

I'm not sure what more I can do here.  It may be done to some weird mod combo you've got but I can't think what would cause this... as you say, OTG is just worldgen.  Maybe somehow related to the biome you're in? (I tested in a Mesa)

**Comment by lOmicronl** [comment] 2018-10-16 11:19
Thank you for trying, anyway. Maybe it's something that only happens when half a dozen or more mods come together and the stars align to boot. Who knows. I'll just defer all my pressure chamber stuff for right before I log off for the day for now. I can try in a different biome once I find a nice place to move to (I've been looking).

Are you interested in overall gameplay feedback, by the way? I went into Pneumaticraft completely blind, never having touched it before, and I've hit a few frustrating snags along the way where I felt like a bit of tweaking might improve the experience. Though if you want to keep the issue tracker for bugs only, that's okay.

**Comment by desht** [comment] 2018-10-16 13:00
I'll do some more testing with the pressure chamber and see if I can trigger anything.  The only possible thing might be the client-side rendering of items in the chamber and/or the particle rendering - I do plan to push a change very soon to skip those if there's a) no glass in the chamber, or b) they're disabled via a client-side setting.  I'll let you know when that build is available - never know, it might help.

Yeah, I'm absolutely interested in overall feedback.  Feel free to raise an issue for that - the tracker isn't just for bugs.  Enhancement requests and general usability feedback are totally welcome.

**Comment by RedBlockFilms** [comment] 2018-12-14 00:30
I've encountered this same bug recently, using the latest version of pneumaticraft (0.8.4) and nothing else in a blank minecraft instance. The moment the item goes out of the outbound interface the lag starts.

**Comment by desht** [comment] 2018-12-14 07:36
* Can you confirm this is specifically FPS drop and not TPS lag?
* Does your pressure chamber have any glass (actually a screenshot would be useful, showing where your valve(s), interfaces, etc. are) ?
* Is there an inventory beside your outbound interface?
* What OS & video card are you using?  Just to confirm, you don't have Optifine installed, right?

**Comment by desht** [comment] 2018-12-14 07:57
Note: just tried again in an instance with only PNCR & JEI - still can't reproduce the problem.  This is with a Linux Mint installation & Nvidia GTX 760.

**Comment by desht** [comment] 2018-12-14 08:37
I think I may have found the problem, but would appreciate some feedback from both of you if you're prepared to try out dev build 306 from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/

**Comment by RedBlockFilms** [comment] 2018-12-14 22:43
Yep, that update fixed it to the best of my knowledge. If you still need some information, here's the pressure chamber I was using and my OS is Windows 10, Nvidia 1050Ti
![2018-12-14_16 42 11](https://user-images.githubusercontent.com/30029228/50033720-5550df80-ffbf-11e8-9712-036efcfff3af.png)

**Comment by desht** [comment] 2018-12-28 17:46
Fixed in 0.9.0 release

**Closed by desht** 2018-12-28 17:46 UTC
Labels: Fixed in Dev
