### ISSUE TITLE
Crash when broken refinery output

### ISSUE THREAD

**Issue by winterSteve25** [TeamPneumatic/pnc-repressurized#782] opened 2021-04-04 19:01 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.1.2
### Mod Version
2.11.3-168
### Describe your problem, including steps to reproduce it
Crash when broken refinery output, I think it only happens if you break it before you break the controller
1.Put down the controller and refinery output on top of it
2.Break the refinery output
### Any other comments?
Unfortunately, I can not get the crash log because I am playing on a server and the owner doesn't seem to care that much about it

Thanks!

**Comment by desht** [comment] 2021-04-04 19:59
Duplicate of #777 and already fixed in 2.11.4

**Closed as completed by desht** 2021-04-04 19:59 UTC
Labels: duplicate
