### ISSUE TITLE
2D HUD Greyed out.

### ISSUE THREAD

**Issue by CraXyOW3** [TeamPneumatic/pnc-repressurized#395] opened 2019-10-23 17:45 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2844
### Mod Version
ATM Remix 1.5.1
### Describe your problem, including steps to reproduce it
![minecraftbug](https://user-images.githubusercontent.com/4594692/67419651-626e3000-f5cd-11e9-89c4-c203772d59e8.png)
Most but not all HUD info bubbles are in grey.
### Any other comments?
Tried to remove BetterFPS, no change.
Tried with Optifine OptiFine_1.12.2_HD_U_E3, no change.

**Comment by desht** [comment] 2019-10-24 06:38
Please include your complete mod list.

**Comment by CraXyOW3** [comment] 2019-10-26 08:07
> ActuallyAdditions-1.12.2-r150.jar
ActuallyBaubles-1.12-1.1.jar
actuallycomputers-2.1.0.jar
AdvancedRocketry-1.12.2-1.6.0-180-universal.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AE2WTLib-1.12.2-1.0.30.jar
AgriCraft-2.12.0-1.12.0-a6.jar
AIImprovements-1.12.1-0.0.1b1.jar
AkashicTome-1.2-12.jar
AppleCore-mc1.12.2-3.2.0.jar
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv6-stable-7.jar
armoryexpansion-1.3.4b.jar
Aroma1997Core-1.12.2-2.0.0.2.b165.jar
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89.jar
astralsorcery-1.12.2-1.10.20.jar
atmtweaks-1.2.jar
AttributeFix-1.12.2-1.0.9.jar
AutoRegLib-1.3-32.jar
backpack-3.0.2-1.12.2.jar
base-1.12.2-3.13.0.jar
Baubles-1.12-1.5.2.jar
baubley-heart-canisters-1.12.2-2.0.3.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
BetterFps-1.4.8.jar
BetterThanMending-1.1.2.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
binnie-mods-1.12.2-2.5.1.188.jar
BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar
birdsfoods-1.12 - 3.1.jar
blockcraftery-1.12.2-1.3.1.jar
BloodMagic-1.12.2-2.4.2-104.jar
bloodylib-1.0.1-beta.jar
bonsaitrees-1.1.3-b156.jar
Bookshelf-1.12.2-2.3.585.jar
Born In A Barn V1.8-1.12-1.1.jar
Botania r1.10-361.jar
BrandonsCore-1.12.2-2.4.17.208-universal.jar
BuildingGadgets-2.7.3.jar
capabilityadapter-1.0.1.jar
careerbees-0.4.0.jar
cc-tweaked-1.12.2-1.84.0.jar
Chameleon-1.12-4.1.3.jar
ChatFlow-1.4-7.jar
ChickenChunks-1.12.2-2.4.2.74-universal.jar
Chisel-MC1.12.2-0.2.1.35.jar
chiselsandbits-14.33.jar
classicbar-0.4.1.jar
ClientTweaks_1.12.2-3.1.11.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.3.27-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar
CommonCapabilities-1.12.2-2.4.4.jar
compactmachines3-1.12.2-3.0.18-b278.jar
compatlayer-1.11.2-0.3.0.jar
Computronics-1.12.2-1.6.6.jar
conarm-1.12.2-1.2.4.jar
ContentTweaker-1.12.2-4.9.1.jar
Controlling-3.0.7.jar
CookingForBlockheads_1.12.2-6.4.71.jar
CosmeticArmorReworked-1.12.2-v4a.jar
CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker2-1.12-4.1.19.jar
CTM-MC1.12.2-0.3.3.22.jar
Cucumber-1.12.2-1.1.3.jar
culinaryconstruct-1.3.3.1.jar
Currency-1.12.0-1.3.11.jar
CustomBackgrounds-MC1.12-1.1.1.jar
CustomMainMenu-MC1.12.2-2.0.9.jar
Cyclic-1.12.2-1.19.16.jar
CyclopsCore-1.12.2-1.5.0.jar
DarkUtils-1.12.2-1.8.226.jar
deepresonance-1.12-1.8.0.jar
DefaultOptions_1.12.2-9.2.8.jar
diethopper-1.1.jar
dirlist.txt
DiscordSuite-2.2.4.jar
dl_overrides.py
Draconic-Evolution-1.12.2-2.3.24.349-universal.jar
ElecCore-1.12.2-1.9.452.jar
ElectroblobsWizardry-4.2.3-MC1.12.2.jar
EmbersRekindled-1.13-hotfix2.jar
EnderCore-1.12.2-0.5.69.jar
EnderIO-1.12.2-5.1.51.jar
EnderIO-endergy-1.12.2-5.1.51.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
environmentalcreepers-1.12.2-1.5.0.jar
environmentaltech-1.12.2-2.0.20.1.jar
etlunar-1.12.2-2.0.20.1.jar
ExtraCells-1.12.2-2.6.2a.jar
ExtraRails-1.12-1.3.0.jar
extrautils2-1.12-1.9.9.jar
ExtremeReactors-1.12.2-0.4.5.67.jar
FastFurnace-1.12.2-1.3.1.jar
FastWorkbench-1.12.2-1.7.2.jar
fencejumper-1.12-1.0.5.jar
Flamingo-1.12-v1.11.jar
flatcoloredblocks-mc1.12-6.8.jar
Floralchemy-1.12.2-1.0.1.jar
foamfix-0.10.5-1.12.2.jar
forestry_1.12.2-5.8.2.394.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
FTBLib-5.4.3.138.jar
FTBUtilities-5.4.0.105.jar
FTBUtilitiesBackups-1.0.0.5.jar
funky-locomotion-1.12.2-1.1.2.jar
gendustry-1.6.5.8-mc1.12.2.jar
generators-0.9.20.12-mc1.12.2.jar
Guide-API-1.12-2.1.8-63.jar
Guidebook-1.12.2-2.9.2.jar
hooked-1.0.3.jar
iChunUtil-1.12.2-7.2.1.jar
ieclochecompat-2.0.6.jar
ImmersiveEngineering-0.12-91.jar
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.10.jar
incontrol-1.12-3.9.16.jar
industrialcraft-2-2.8.187-ex112.jar
industrialforegoing-1.12.2-1.12.13-237.jar
IndustrialWires-1.7-36.jar
infinitylib-1.12.0.jar
InitialInventory-3.0.0.jar
IntegratedCrafting-1.12.2-1.0.8.jar
IntegratedDynamics-1.12.2-1.1.0.jar
IntegratedTerminals-1.12.2-1.0.10.jar
IntegratedTunnels-1.12.2-1.6.10.jar
IntegrationForegoing-1.12.2-1.9.jar
inventorygenerators-1.2.2.jar
InventoryTweaks-1.64+dev.146.jar
ironchest-1.12.2-7.0.72.847.jar
JAOPCA-1.12.2-2.2.8.103.jar
JAOPCAAdditions-1.12.2-2.2.1.9.jar
JAOPCAAgriculture-1.12.2-1.2.1.16.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.5.1.36.jar
jei_1.12.2-4.15.0.289.jar
journeymap-1.12.2-5.5.5.jar
justenoughdimensions-1.12.2-1.6.0-dev.20190711.220109.jar
JustEnoughEnergistics-1.12.2-1.0.7.jar
JustEnoughPetroleum-0.1.jar
JustEnoughReactors-1.12.2-1.1.3.61.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
kjlib-1.0.4.jar
KleeSlabs_1.12.2-5.4.12.jar
LagGoggles-FAT-1.12.2-4.8.jar
librarianlib-1.12.2-4.19.2-release.jar
LibraryEx-1.12.2-1.0.11.jar
LibVulpes-1.12.2-0.4.1-62-universal.jar
lostcities-1.12-2.0.21.jar
lostsouls-1.12-1.1.4.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
MagicBees-1.12.2-3.1.10.jar
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
Mantle-1.12-1.3.3.55.jar
matc-1.0.1-hotfix.jar
mcjtylib-1.12-3.5.4.jar
Mekanism-1.12.2-9.8.1.383.jar
MekanismGenerators-1.12.2-9.8.1.383.jar
MekanismTools-1.12.2-9.8.1.383.jar
memory_repo
mobtotems-1.12.1-0.3.0.jar
modnametooltip_1.12.2-1.10.1.jar
Modpack Configuration Checker-1.12.2-v1.8.1.jar
modtweaker-4.0.17.jar
moreoverlays-1.15.1-mc1.12.2.jar
Morph-o-Tool-1.2-21.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10-mc1.12.2.jar
mpbasic-1.12.2-1.4.11.jar
MPUtils-1.12.2-1.5.7.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
MTLib-3.0.6.jar
MysticalAgradditions-1.12.2-1.3.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
mysticallib-1.12.2-1.3.7.jar
MysticWorld-1.12.2-1.4.4.jar
NaturesCompass-1.12.2-1.5.1.jar
NetherEx-1.12.2-2.0.15.jar
NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar
NotEnoughIDs-1.5.4.4.jar
notenoughwands-1.12-1.8.1.jar
NuclearCraft-2.18h-1.12.2.jar
Nutrition-1.12.2-4.4.0.jar
oeintegration-2.3.4.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenComputers-MC1.12.2-1.7.4.153.jar
OpenModsLib-1.12.2-0.12.2.jar
OptiFine_1.12.2_HD_U_E3.jar
OreExcavation-1.4.140.jar
Overloaded-1.12.2-0.0.58.jar
override_mods.txt
p455w0rdslib-1.12.2-2.2.156.jar
packcrashinfo-1.0.1.jar
packmode-1.12.2-1.2.0.jar
parry-1.0-hotfix.jar
Patchouli-1.0-20.jar
phosphor-1.12.2-0.2.6+build50-universal.jar
Placebo-1.12.2-1.6.0.jar
Plants-1.12.2-2.10.7.jar
plustic-7.1.4.1.jar
pneumaticcraft-repressurized-1.12.2-0.11.5-371.jar
PortalGun-1.12.2-7.1.0.jar
portality-1.12.2-1.2.3-15.jar
pressure-1.3.1.9-mc1.12.2.jar
ProjectIntelligence-1.12.2-1.0.8.25-universal.jar
ProjectRed-1.12.2-4.9.4.120-Base.jar
ProjectRed-1.12.2-4.9.4.120-compat.jar
ProjectRed-1.12.2-4.9.4.120-fabrication.jar
ProjectRed-1.12.2-4.9.4.120-integration.jar
ProjectRed-1.12.2-4.9.4.120-lighting.jar
ProjectRed-1.12.2-4.9.4.120-mechanical.jar
ProjectRed-1.12.2-4.9.4.120-world.jar
Psi-r1.1-77.jar
Quark-r1.6-177.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
randompatches-1.12.2-1.18.1.1.jar
RandomThings-MC1.12.2-4.2.7.3.jar
randomtweaks-1.12.2-2.7.1.0.jar
rangedpumps-0.5.jar
reauth-3.6.0.jar
RebornCore-1.12.2-3.16.2.473-universal.jar
RebornStorage-1.12.2-3.3.4.85.jar
RedstoneArsenal-1.12.2-2.6.3.18-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
refinedstorage-1.6.15.jar
refinedstorageaddons-0.4.4.jar
Reliquary-1.12.2-1.3.4.796.jar
ResourceLoader-MC1.12.1-1.5.3.jar
rftools-1.12-7.72.jar
rftoolsctrl-1.12-2.0.2.jar
rftoolsdim-1.12-5.71.jar
rftoolspower-1.12-1.2.0.jar
rftpwr_oc-0.2.jar
RoguelikeDungeons-1.12.2-1.8.0.jar
Roots-1.12.2-3.0.12.jar
rustic-1.1.1.jar
Schematica-1.12.2-1.8.0.169-universal.jar
ShadowMC-1.12-3.8.0.jar
SimplyJetpacks2-1.12.2-2.2.13.66.jar
SoulShardsRespawn-1.12.2-1.1.1-13.jar
SplashAnimation-0.2.1.jar
StevesCarts-1.12.2-2.4.31.135.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.4.0.jar
StorageDrawersExtras-1.12-3.1.0.jar
SuperiorShields-1.12.2-1.0.2.jar
Tatw-1.12.2-1.0.1.2.b27.jar
tc6aspects4jei-0.0.2a.jar
TConstruct-1.12.2-2.12.0.157.jar
TechReborn-1.12.2-2.24.1.1032-universal.jar
tesla-core-lib-1.12.2-1.0.15.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicComputers-MC1.12.2-0.5.1.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThaumicJEI-1.12.2-1.6.0-27.jar
thaumicperiphery-0.3.1.jar
TheBetweenlands-3.4.11-universal.jar
theoneprobe-1.12-1.4.28.jar
ThermalCultivation-1.12.2-0.3.3.12-universal.jar
ThermalDynamics-1.12.2-2.5.5.21-universal.jar
ThermalExpansion-1.12.2-5.5.4.43-universal.jar
ThermalFoundation-1.12.2-2.6.3.27-universal.jar
ThermalInnovation-1.12.2-0.3.3.12-universal.jar
thermallogistics-0.2-26.jar
tinkersjei-1.2.jar
tinkersoc-0.6.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
Toast Control-1.12.2-1.8.1.jar
tombstone-3.5.8-1.12.2.jar
topaddons-1.12.2-1.11.0.jar
Transport-1.12.2-1.0.0.jar
Traverse-1.12.2-1.6.0-69.jar
twilightforest-1.12.2-3.9.984-universal.jar
UniDict-1.12.2-2.9.2.jar
unloader-1.2.0.jar
valkyrielib-1.12.2-2.0.20.1.jar
WAIM-1.0.0.jar
WanionLib-1.12.2-2.2.jar
WaterStrainer-1.12-3.2.0.jar
Waystones_1.12.2-4.0.72.jar
wetstone-1.0.jar
WirelessCharger-1.12.2-1.0.6.jar
WirelessCraftingTerminal-1.12.2-3.12.93.jar
WirelessFluidTerminal-1.12.2-1.0.1.jar
WirelessInterfaceTerminal-1.12.2-1.0.0.jar
WirelessPatternTerminal-1.12.2-1.0.1.jar
wizardry-0.10.8.jar
woot-1.12.2-1.4.11.jar
worldprimer-1.12.2-0.6.0-dev.20190525.121747.jar
worleycaves-1.5.1.jar
WrapUp-1.12-1.1.3.jar
XL-Food-Mod-1.12.2-1.9.2.jar
xnet-1.12-1.8.2.jar
Xtones-1.12-1.0.8-11.jar
YNot-0.2.4.jar
zerocore-1.12.2-0.1.2.8.jar

**Comment by desht** [comment] 2019-10-27 16:06
And does this problem happen with no Optifine installed?

**Comment by CraXyOW3** [comment] 2019-10-27 19:51
It happens with optifine and without optifine.
with and without betterfps too.

It happens to all 2D HUD bubbles, but if is dismantle a Drone and replace it, sometimes the 2D HUD returns to normal. Sometimes it doesn't.

**Comment by desht** [comment] 2019-10-28 08:25
Hmm, this will be hard to track down, especially as I can't reproduce it (and have never seen this happen before).  It's almost certainly due to one of the other mods you have there, but very hard to know which one without repeatedly testing with one or mods removed...

I'll keep this open and see if I can track anything down related to this.

**Comment by CraXyOW3** [comment] 2019-10-28 12:01
I will try some things too. Starting with graphics drivers and settings.
Weird is that it is intermediate.

One thing I did notice when I tracked mobs, it depends on field of view, when mobs are out of center, the HUD renders perfectly, while the HUD was in center it was greyed out.

**Comment by desht** [comment] 2020-09-28 15:31
Closing this due to age (and 1.12.2 is no longer supported)

**Closed by desht** 2020-09-28 15:31 UTC
Labels: Can't Reproduce
