### ISSUE TITLE
Server crash when breaking double chest with a heat frame on

### ISSUE THREAD

**Issue by jona23E** [TeamPneumatic/pnc-repressurized#1196] opened 2023-08-08 22:10 UTC
### Describe the bug

Players are using this to dupe items on my server (and crash it over and over again)

### How to reproduce the bug

- Place a chest
- Place a heat frame on it
- Heat up the heat frame
- Put smeltable items inside the chest
- Place another chest next to the chest with a heat frame on it in a way so it connects to it
- Break the chest (not the one with the heat frame)
- crash after 1-2 seconds

### Expected behavior

The heat frame works on the entire double chest

### Additional details

We are playing on an aternos server

### Which Minecraft version are you using?

1.18 - critical bugs only

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.6.0-19

### Crash log

https://mclo.gs/abe6kMc

**Comment by desht** [comment] 2023-08-10 10:46
I can't see anything in your posted log which is a stacktrace?

**Comment by desht** [comment] 2023-08-10 14:48
However, I was able to reproduce it.  Since it's a server crash, I'll release a fix for 1.18.2 for this one.

**Comment by desht** [comment] 2023-08-10 15:32
Fixed in 3.6.1 release (Curseforge approval pending, or get it now from Modrinth)

**Closed as completed by desht** 2023-08-10 15:32 UTC
Labels: Bug
