### ISSUE TITLE
Issue with Redstone Control in the End. 

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#550] opened 2020-07-12 19:55 UTC
### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.15.2-1.3.2-49
### Describe your problem, including steps to reproduce it

I recently moved my Aerial Interfaces to the End just to get them out of my base. 

![2020-07-12_15 36 49](https://user-images.githubusercontent.com/9543430/87255117-f92d9600-c455-11ea-938c-1783c8d50b3f.png)

The setup is pretty straight forward, just a Flux Compressor being fed energy from a Powah! Generator that then feeds two Aerial Interfaces. One is configured to feed me, the other is set up for charging my armor and to provide the smart chest access to my ender chest. It pulls food from there and sends it to the Interface on the right. 

The compressor itself is set to run on High Redstone. The Gauge is configured to output a signal at less than 19 bar. 

All works great while I'm hanging around. Things seem to get odd upon leaving the End. I think that the Redstone module is getting stuck in an on state somehow. I've now rebuilt this all three times since shortly after returning to the overworld I find my armor is running out of air and I'm no longer being fed. Upon my return to the End I find the compressor, most or all of the tubes, and at least one interface has blown up. In one instance, I actually caught it in the act as I had popped back to the overworld quick to get something I had forgotten, only to have it all go up in my face as I teleported in. 

Chunk loading is being provided by an Anchor Upgrade in the Quantum Entangloporter. The entire build is in one chunk. 

### Any other comments?

I'm currently testing with FTB chunk loading instead to see if it's actually just an issue with the QE's anchor upgrade. Will come back and update if using FTB actually fixes it.

**Comment by MuteTiefling** [comment] 2020-07-12 20:04
Update: It happened again with FTB Chunks, this time, however, it happened after logging out and back in. 

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/4909332/latest.log)

Did not see the explosion, but I did end up with all the 'extra' bits in my inventory as I had logged out right in front of the setup. So I recovered some of my volume upgrades.

I should note that this was never an issue in the overworld. I had almost the exact same setup there. The only difference now compared to then is that the aerial interface is accessing my ender chest where it was not before. That seems an unlikely cause for this, but I'm now going to test without that.

**Comment by MuteTiefling** [comment] 2020-07-12 20:05
![2020-07-12_16 04 32](https://user-images.githubusercontent.com/9543430/87255513-6c84d700-c459-11ea-981f-2cb34cfa264f.png)

Just noticed this from the remains as well. Two pieces of pipe are left in place, both at > 29 bar.

**Comment by MuteTiefling** [comment] 2020-07-12 20:10
![2020-07-12_16 06 27](https://user-images.githubusercontent.com/9543430/87255532-a950ce00-c459-11ea-8771-fd015cabfd08.png)

And this. You can see that The One Probe is reporting 28 bar, but the interface is reporting 2.8. That interface is also slowly losing air. 

https://streamable.com/mn2kku

**Comment by MuteTiefling** [comment] 2020-07-12 20:54
Happens consistently on restart. I had thought, like with previous times that I've struggled with strange explosions, that it was due to leaving some old pieces in place (like the interface that hadn't exploded) but this last time I tore out everything from PNC and rebuilt. Still exploded.

**Comment by desht** [comment] 2020-07-13 14:18
Have you tried this in any other dimensions?  Nether, custom dimensions, etc.?

Going to have a play with this and see what I can find...

Pretty sure the TOP display is wrong there, since any tube > 25 bar will instantly explode.  Some kind of factor-of-10 error going on there, maybe?  Very weird.

**Comment by desht** [comment] 2020-07-13 14:55
OK, set this up in my dev world, chunkloaded with the vanilla `/forceload` command:
![2020-07-13_15 50 42](https://user-images.githubusercontent.com/736831/87318772-ad93ee80-c520-11ea-98f5-42a223c03d8b.png)

Advanced liquid compressor burning LPG, set to run on a high signal.  Pressure gauge on left-hand tube with advanced PCB, set to emit at <10 bar.  Receiving redstone module on the right-hand tube, and a corresponding emitting module back at the compressor end.  I filled the compressor with fuel, and went back to the overworld for a few minutes.  When I returned to the end, it was stopped at 10.05 bar, i.e. pretty much where it should do.  So the modules seem to be behaving themselves fine so far...

I'd advise testing with vanilla chunkloading too and see if that makes a difference.  I'll do some more tests in the meantime.

Also, I'm using command blocks to port between the End and the Overworld (with the `/forge setdimension` command).  Seems unlikely that using modded methods of transferring dimensions would have an effect, but who knows...

Update: also added an Aerial Interface and charging module to keep my armor charged (and boosted the pressure level to 15 bar).  I can fly around in the Overworld and it keeps me charged.  Changing dimensions, logging out, restarting the client... can't make it break so far :(

**Comment by desht** [comment] 2020-07-13 14:59
Also, are you on dedicated server, or is this a local single-player world?

**Comment by MuteTiefling** [comment] 2020-07-13 16:54
Local Single player world, though I'm increasingly starting to believe this world has become corrupt somehow as there have been some other really weird things happening. 

I'll try to get back in and test with vanilla chunk loading tonight. Can also try it in the Nether to see what it does there. 

I don't know if this makes any difference either, but for me I've been putting the gauge right up against the compressor, rather than passing it through vanilla redstone or redstone tube modules. So it's signal directly controls the on/off of the compressor.

**Comment by MuteTiefling** [comment] 2020-07-14 00:04
Update: I have rebuilt the same setup in the End in a fresh world and used /forceload to chunk load it. After rebuilding it and letting stabilize up to 19 bar, I logged out and back in. It immediately blew up.

This was also in my small testing pack that's got considerably fewer mods than my primary play world. 

I'll try to set it up in the Nether now that I know it's not just my main pack.

I'm seeing the same weirdness with The One Probe too, with it reporting 30 bar while looking at the one remaining Aerial Interface.

**Comment by MuteTiefling** [comment] 2020-07-14 00:17
![2020-07-13_20 15 06](https://user-images.githubusercontent.com/9543430/87365986-94516900-c545-11ea-899d-51b6875cce43.png)

Here's the setup in my test pack. All stable prior to logging out. Upon logging back in, everything is fine. So I'm only having trouble in the end.

Also, I just realized that I wrote the title to this wrong. That's what I get for doing this in the middle of the night.

**Comment by MuteTiefling** [comment] 2020-07-14 00:26
bleh, just realized my build in the end wasn't all in one chunk, nor chunk loaded.... 

![2020-07-13_20 25 03](https://user-images.githubusercontent.com/9543430/87366551-f52d7100-c546-11ea-8152-250f97f47d37.png)

Rebuilt it here. Let it stabilize up to 19. Put myself in survival, logged out. Logged back in and it all blew up.

![2020-07-13_20 26 29](https://user-images.githubusercontent.com/9543430/87366616-273ed300-c547-11ea-8544-782212ccb957.png)

![2020-07-13_20 28 41](https://user-images.githubusercontent.com/9543430/87366795-91577800-c547-11ea-9ec0-b166f9def04f.png)

**Comment by MuteTiefling** [comment] 2020-07-14 00:28
One more note and I'll stop spamming this thread: This test pack is using pneumaticcraft-repressurized-1.15.2-1.4.0-51 since it's where I was testing the drone changes. 

Also, on a positive note, I love the changes to the heat gauge in the compressor. Very clean.

**Comment by MuteTiefling** [comment] 2020-07-14 00:36
Ok, I know I said I'd stop updating, but I just noticed something new.

This last time when it blew, both aerial interfaces survived, and they both had the funky pressure display.

So I thought I'd pop a creative compressor in between them to see if it can zero out and fix the pressure in them. Note that the compressor is set to 20 bar.


![2020-07-13_20 33 51](https://user-images.githubusercontent.com/9543430/87367126-2ce8e880-c548-11ea-8491-ee50d49034fb.png)

TOP is showing 20 on all 3 blocks, but the internal display on the interfaces is showing 2.

So I've probably thrown you off the mark completely, I don't think it's anything to do with the redstone control. I think the Aerial Interfaces may be initializing incorrectly upon loading, but only if the chunk is force loaded (note the nether setup didn't blow when it wasn't force loaded).

**Comment by desht** [comment] 2020-07-14 06:50
Thanks, there's some potentially useful info to go on there. I'll keep trying to reproduce it. 

Figured out that the discrepancy between the TOP and GUI display is that for some reason, TOP isn't taking your 25 volume upgrades into account (which increases the volume by 10).  Explains that, at least - the GUI display is correct.  Not sure why TOP isn't using the upgrades there, could be related, though.  Maybe the air handler logic isn't seeing the volume upgrades on reload... that would certainly cause an explosion.

**Comment by desht** [comment] 2020-07-14 08:21
Think I may have nailed it.  I was able to reproduce the problem, with machines at 19 bar and 25 volume upgrades installed.  The fix I applied seems to have sorted it for me - can you try build 52 please?

**Comment by MuteTiefling** [comment] 2020-07-14 12:15
Lookin good! Rebuilt it all the same way, logged out and back in and no earth-shattering kaboom. Awesome job! Sorry for my scattered reporting on this one.

**Comment by desht** [comment] 2020-07-14 14:49
That's OK, problems like this can be a pain to track down... better loads of info than not enough :)

**Comment by desht** [comment] 2020-07-14 15:19
Fixed in 1.4.0 release

**Closed as completed by desht** 2020-07-14 15:19 UTC
Labels: Bug, Fixed in Dev
