### ISSUE TITLE
Instant Crash on Forge 1.18.2 40.0.18

### ISSUE THREAD

**Issue by zachsai** [TeamPneumatic/pnc-repressurized#976] opened 2022-03-20 20:21 UTC
### Describe the bug

https://pastebin.com/kNrdiBMg

### How to reproduce the bug

add mod, be on same version, launch

### Expected behavior

not crash

### Which Minecraft version are you using?

1.18

### Crash log

https://pastebin.com/kNrdiBMg

**Comment by desht** [comment] 2022-03-21 07:10
Duplicate of #972

**Closed as completed by desht** 2022-03-21 07:10 UTC
Labels: Bug, duplicate
