### ISSUE TITLE
Crash upon using the armor's config GUI

### ISSUE THREAD

**Issue by Lucr1** [TeamPneumatic/pnc-repressurized#260] opened 2018-10-19 05:00 UTC
Minecraft Version
1.12.2

Forge Version
14.23.5.2768

Mod Version
1.12.2-0.8.1-274
1.12.2-0.8.0-268
1.12.2-0.8.0-267
1.12.2-0.7.8-259
1.12.2-0.7.6-254
1.12.2-0.7.5-248

Describe your problem, including steps to reproduce it
Upon pressing U [the key bound to this mod's armor config screen], the game crashes every time.

Any other comments?
Using the Gregblock 1.2.0 pack. It didn't seem to happen in Gregblock 1.1.3.
Dupe of https://github.com/TeamPneumatic/pnc-repressurized/issues/254 but I reproduced the crash with debug build 268 (attached log). 

[2018-10-18-5.log](https://github.com/TeamPneumatic/pnc-repressurized/files/2494537/2018-10-18-5.log)

**Comment by desht** [comment] 2018-10-19 15:56
A couple more questions for you (I'm going to download Gregblock later and see if I can reproduce it):

* Are you in single player or on a server?
* Which armor pieces were you wearing, and what upgrades (if any) were in each piece?
* Your log file suggests the crash happened almost immediately after you logged in - is that the case?  Did you try to open the GUI immediately on login?

I'm also going to upload another build to Jenkins soon with a couple of tweaks that may or may not help - would be useful if you could try that out.  I'll let you know when it's available.

**Comment by Lucr1** [comment] 2018-10-19 20:55
Whatever you changed seemed to have done the trick. I'm not crashing at all with build 278 anymore and everything's working. Thank you!

**Comment by desht** [comment] 2018-10-19 21:03
Well that was easier than I hoped :)

**Comment by desht** [comment] 2018-10-30 20:57
Fixed in 0.8.2 release

**Closed by desht** 2018-10-30 20:57 UTC
Labels: Fixed in Dev

**Comment by Famous5000** [comment] 2019-01-07 16:42
Thank you, Lucr1. I'll have to hop back on MC again soon, as I loved playing with this mod and flying around like a lunatic.

And thank you desht for fixing the bug. Not doing any mentions because this is long closed. Sorry, I was ultra busy over the past few months so that's why I wasn't able to reply.
