### ISSUE TITLE
Etching tank does not accept acid.

### ISSUE THREAD

**Issue by ClaymooreEOC** [TeamPneumatic/pnc-repressurized#1341] opened 2024-08-29 12:32 UTC
### Describe the bug

I am unable to insert etching acid into the etching tank either manually (clicking with bucket) or piping with mekanism pipes from a tank.

### How to reproduce the bug

Place etching tank, click with bucket of etching acid.

### Expected behavior

Acid should fill into the internal tank of the etching tank

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.0.2

**Comment by desht** [comment] 2024-08-30 16:04
Etching Tank definitely does accept Etching Acid, I've just tested.  Are you sure you're using the right fluid?  Etching Acid from PneumaticCraft: Repressurized?

**Comment by ClaymooreEOC** [comment] 2024-08-30 16:06
Yep. I also tested it in creative mode.
It was in the 1.21 FTB Unstable modpack.
Think its a modpack issue then?
I also had trouble getting the laser assembly to work properly.
I assumed it was just an issue with neoforge.

**Comment by desht** [comment] 2024-08-30 16:19
Actually, there something a little strange going on. It's working fine in my dev environment, but on my test server, it's not looking so good.  I'll do some investigation.  Saw a similar problem with the Huge Fluid Tank (although not the other tanks, oddly).

**Comment by desht** [comment] 2024-08-30 16:35
Actually, no - more testing on a server shows it is in fact working fine (my original testing was invalid). So I definitely can't reproduce this problem.  I can right-click acid in with a bucket, and I've transferred acid from a PNC tank into the etching tank with both a PNC Liquid Hopper and Mekanism fluid pipes. All worked fine.

It _might_ be an issue with Unstable, although it seems unlikely (they're pretty up to date with PNC and I haven't made any relevant changes recently).

Only other thing I can suggest is making sure there's no other fluid already in the etching tank? Shouldn't be possible, but not sure what else to suggest at this point...

**Comment by ClaymooreEOC** [comment] 2024-08-30 17:04
Ok thanks for checking it out.
Ill go poke the FTB folks and see if they have any idea.

**Comment by This-Is-Alex** [comment] 2024-10-08 03:46
Having this issue too with FTB Unstable 1.21

When I right click on the etching tank, there is no error on the server, but my client has the following stack trace:
```
[16:41:50] [Render thread/INFO] [de.ke.fa.cu.la.ScreenCustomizationLayerHandler/]: [FANCYMENU] ScreenCustomizationLayer registered: me.desht.pneumaticcraft.client.gui.FluidTankScreen
[16:41:54] [Render thread/ERROR] [de.ke.fa.ne.PacketHandler/]: [FANCYMENU] Failed to send packet to server!
java.lang.UnsupportedOperationException: Payload {} may not be sent to the server!
	at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:464) ~[neoforge-21.0.167-universal.jar%23427!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl.send(ClientCommonPacketListenerImpl.java:312) ~[client-1.21-20240613.152323-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/neoforge@21.0.167/net.neoforged.neoforge.common.extensions.IClientCommonPacketListenerExtension.send(IClientCommonPacketListenerExtension.java:24) ~[neoforge-21.0.167-universal.jar%23427!/:?] {re:computing_frames,re:mixin,re:classloading}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.networking.PacketHandlerNeoForge.sendToServer(PacketHandlerNeoForge.java:17) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:classloading}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.networking.PacketsNeoForge.lambda$init$1(PacketsNeoForge.java:30) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:classloading}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.networking.PacketHandler.sendToServer(PacketHandler.java:28) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:classloading}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.networking.packets.commands.variable.suggestions.VariableCommandSuggestionsPacketCodec.onClientTick(VariableCommandSuggestionsPacketCodec.java:38) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:classloading}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.util.event.acara.EventHandler.lambda$registerListenerMethods$1(EventHandler.java:100) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:mixin,re:classloading}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.util.event.acara.EventHandler$ListenerContainer.notifyListener(EventHandler.java:184) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:classloading}
	at TRANSFORMER/fancymenu@3.2.5/de.keksuccino.fancymenu.util.event.acara.EventHandler.postEvent(EventHandler.java:57) ~[fancymenu_neoforge_3.2.5_MC_1.21.jar%23501!/:3.2.5] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.handler$clb000$fancymenu$afterGameTickFancyMenu(Minecraft.java:17048) ~[client-1.21-20240613.152323-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.tick(Minecraft.java:1916) ~[client-1.21-20240613.152323-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[client-1.21-20240613.152323-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21-20240613.152323-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.MinecraftMixin from mod resourcepackoverrides,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:drippyloadingscreen.mixins.json:client.IMixinMinecraft from mod drippyloadingscreen,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod ars_nouveau,pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod prism,pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadEnd from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinResourceReload from mod entity_texture_features,pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod bridgingmod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:ichunutil.mixins.json:client.MinecraftMixin from mod ichunutil,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod ae2wtlib,pl:mixin:APP:armorposer.neoforge.mixins.json:MinecraftMixin from mod armorposer,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod iceberg,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod ars_nouveau,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23426!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.23.jar%23122!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.23.jar%23122!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.23.jar%23122!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.23.jar%23122!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23104!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23104!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23104!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23104!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23104!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23104!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23104!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
```

Similar deal with the assembly controller

**Comment by This-Is-Alex** [comment] 2024-10-08 03:55
```
[16:52:37] [Render thread/INFO] [de.ke.fa.cu.la.ScreenCustomizationLayerHandler/]: [FANCYMENU] ScreenCustomizationLayer registered: me.desht.pneumaticcraft.client.gui.EtchingTankScreen
[16:52:46] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
```

These log lines might actually be more helpful

**Comment by desht** [comment] 2024-10-08 09:08
Yeah, complain to the author of Fancy Menu. No idea what they're doing (the mod is not open source and I'm not in the mood to trawl through decompiled bytecode), but there's a problem with their packet handling.

**Closed as completed by desht** 2024-10-08 09:08 UTC
Labels: Bug, other mod issue, Can't Reproduce

**Comment by This-Is-Alex** [comment] 2024-10-08 10:40
Confirmed this issue is still present when removing the fancy menu mod

These lines still showed up multiple times in the logs, with no other relevant stacktraces
```
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[23:25:20] [Render thread/ERROR] [pneumaticcraft/]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
```

Some other lines from latest.log to do with pneumaticcraft:
```
[08Oct2024 23:24:19.434] [main/WARN] [mixin/]: Reference map 'mixins.pneumaticcraft.refmap.json' for mixins.pneumaticcraft.json could not be read. If this is a development environment you can ignore this message
...
[08Oct2024 23:24:32.269] [modloading-sync-worker/INFO] [pneumaticcraft/]: Third party integration activated for [jei,mekanism,curios,patchouli]
...
[08Oct2024 23:25:19.975] [Render thread/WARN] [mezz.jei.library.plugins.vanilla.ingredients.ItemStackListFactory/]: 4 duplicate items were found in creative tab: PneumaticCraft: Repressurized
This may indicate that these types of item need a subtype interpreter added to JEI:
[pneumaticcraft:pneumatic_chestplate, pneumaticcraft:pneumatic_leggings, pneumaticcraft:pneumatic_helmet, pneumaticcraft:pneumatic_boots]
...
[08Oct2024 23:25:24.831] [Render thread/WARN] [patchouli/]: Invalid icon item stack: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'pneumaticcraft:pneumatic_generator' at position 0: <--[HERE]
[08Oct2024 23:25:24.834] [Render thread/WARN] [patchouli/]: Invalid icon item stack: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'pneumaticcraft:electric_compressor' at position 0: <--[HERE]
...
[08Oct2024 23:25:24.916] [Render thread/WARN] [patchouli/]: Recipe pneumaticcraft:radiation_shielding_upgrade (of type minecraft:crafting) not found
```

Some additional context not present in the original bug report:

- When you right click on the etching tank with a bucket of etching acid, the inventory for the etching tank simply opens, instead of the fluid being put into it
- Piping the fluid into the etching tank does not work with fluid pipe from modern industrialization, or the basic mechanical pipe from mekanism
