### ISSUE TITLE
Oddly unable to create new Amadron trades

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#619] opened 2020-09-22 22:21 UTC
### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
1.16.1-2.2.2-35
### Describe your problem, including steps to reproduce it

Any GUI element I click in the Custom Trades interface just drops me back to the main menu to purchase items. Unable to pick GPS coordinates, search items, etc. 

If I drag items in from JEI and hit OK, it crashes entirely.

### Any other comments?

[crash-2020-09-22_18.20.09-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5264315/crash-2020-09-22_18.20.09-server.txt)

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/5264317/latest.log)

**Comment by desht** [comment] 2020-09-22 22:48
Confirmed.

**Comment by desht** [comment] 2020-09-22 23:07
The GUI problem's fixed (not sure where or when it went wrong, but the problem was pretty obvious), but I can't reproduce the crash at all.  Looks like somehow you managed to get a trade of 0 items added, which is clearly invalid (and the "Add Trade" button even greys out if you enter an item size of 0 in the GUI).  Not sure how that can happen; I didn't have any trouble adding a trade via JEI items.

**Comment by desht** [comment] 2020-09-26 13:05
Fixed in 2.2.3 release

**Closed as completed by desht** 2020-09-26 13:05 UTC
Labels: Bug
