### ISSUE TITLE
The Omnidirectional Hopper Doesn't Consistently Export From Certain Mods' Machines

### ISSUE THREAD

**Issue by EmosewaPixel** [TeamPneumatic/pnc-repressurized#266] opened 2018-11-02 19:13 UTC
### Describe your problem, including steps to reproduce it
 So while in my case it's GregTech CE's machines, I'm sure there are some other mods' machines that this happens with. The Omnidirectional Hopper doesn't start exporting immediately. Sometimes it starts exporting once the machine's output is full (which isn't practical in many cases), but sometimes it never does. Seeing that this does not happen with vanilla Hoppers or TE's Servos, I believe it's safe to say it's related to the Omnidirectional Hopper itself. (It also doesn't happen when exporting fluids with the Fluid Hopper, but that's different).

### Any extra comments
 This issue https://github.com/EmosewaPixel/GregBlock/issues/58 has some more information about it. (yes, I did replace the vanilla Hopper with the PnC:R one)

**Comment by desht** [comment] 2018-11-03 09:07
I can't reproduce this with vanilla or any other mods right now, and while I'd love to test GTCE with my dev instance, it just crashes it, which is a bit of a problem...

**Comment by EmosewaPixel** [comment] 2018-11-03 09:45
I actually did test the exact same mods. That's why I said "Certain Mods' Machines", as it's GTCE and surely some other mod that we wouldn't think about testing. Anyways, it's interesting that it crashes with EIO in the dev environment. No one's used it together with EIO to know that. :P

**Comment by desht** [comment] 2018-11-03 10:46
I've seen problems like this before, some kind of obfuscation issue.  Can be difficult to track down, but I can probably test with another world without EIO.

**Comment by desht** [comment] 2018-11-03 10:54
I got GTCE working with a test instance I use, but I have no clue how these machines are supposed to work.  I thought a Basic Furnace beside a Diesel Generator would get powered, but no.  Tried various GT cables too, no dice.

I did test with a GT Stainless Steel chest and the Omnihopper had no problem pulling from that.

**Comment by EmosewaPixel** [comment] 2018-11-03 10:58
Oh, it does work, you just need to place it so the white dot is facing the machine. The generators output from only one side.

**Comment by desht** [comment] 2018-11-03 11:00
OK, figured it out.  Yeah, the omnihopper isn't pulling from below the Basic Furnace.  I'll see if I can make this work in my dev instance so I can debug.

**Comment by desht** [comment] 2018-11-03 11:29
Build 297 will contain this fix (as well as a fix for a dumb Amadron GUI crash I introduced in 0.8.2).

**Comment by desht** [comment] 2018-11-05 16:09
Fixed in 0.8.3 release

**Closed by desht** 2018-11-05 16:09 UTC
Labels: Bug, Fixed in Dev
