### ISSUE TITLE
Oil doesn't have any physics

### ISSUE THREAD

**Issue by mrlol4ever** [TeamPneumatic/pnc-repressurized#861] opened 2021-07-24 18:43 UTC
1.16.5

forge-36.2.0

pneumaticcraft-repressurized-1.16.5-2.13.2-205.jar

whenever i go into oil i don't swim i just fall thru it.

**Comment by desht** [comment] 2021-07-24 22:12
Duplicate of #792

**Closed as completed by desht** 2021-07-24 22:12 UTC
Labels: duplicate, wontfix
