### ISSUE TITLE
Hang and crash when player joins. 

### ISSUE THREAD

**Issue by djnifos** [TeamPneumatic/pnc-repressurized#1325] opened 2024-08-07 01:38 UTC
### Describe the bug

When a player joins, Refinery ticks endlessly, watchdog terminates. 

### How to reproduce the bug

User states they've placed the tank and controller and it has a resistive heater.  Hard to remember without being able to join. 

### Expected behavior

Not Crash

### Additional details

neo 21.0.151
ATM10

### Which Minecraft version are you using?

1.20.4

### Which version of PneumaticCraft: Repressurized are you using?

8.0

### Crash log

https://mclo.gs/F0sgnyv

**Comment by desht** [comment] 2024-08-08 21:46
I can't reproduce this myself, but I've added some extra checks to that part of the code, so this hopefully not happen in the next release (which will be out soon).

**Comment by desht** [comment] 2024-08-08 22:08
Should be fixed in 8.0.2

**Closed as completed by desht** 2024-08-08 22:08 UTC
Labels: Bug
