### ISSUE TITLE
Thermopnuematic Processing Plant won't run on its own

### ISSUE THREAD

**Issue by TheUnderTaker11** [TeamPneumatic/pnc-repressurized#321] opened 2019-04-01 03:57 UTC
Using latest version of Project Ozone 3
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2815 I think
### Mod Version
0.9.3-324
### Describe your problem, including steps to reproduce it
I have been setting up automation for the thermopnuematic processing plant, and for some reason, it doesn't run until I manually change the amount of coal in its inventory.
Coal being pushed in with Ender IO item conduits.

Video showing my exact problem as giving as much info as I could is [here](https://www.youtube.com/watch?v=1uDEGirIxRo&feature=youtu.be)
### Any other comments?
Watching the video should explain the exact problem I am having.

**Comment by desht** [comment] 2019-04-01 07:08
I can't reproduce this right now, although your video does show the problem very clearly.  I've tested with both EnderIO conduits and vanilla hoppers to push the coal in; when I tried, the TPP started running as soon as coal entered the machine.

I'll do some more testing and see if I can turn up anything.

**Comment by TheUnderTaker11** [comment] 2019-04-01 13:45
You need to reproduce it by already having the coal in the machine, and
then pumping in LPG, the number of coal changing is the only way to make it
run currently.

**Comment by desht** [comment] 2019-04-01 16:49
I just tried that too, it started processing as soon as the LPG entered the machine.

**Comment by desht** [comment] 2019-04-02 06:39
Your video shows the LPG and the coal in the machine at the beginning, and the machine not running.  Can you step me through the exact sequence of steps you took to get to that point?  I.e. what order the resources were inserted, how they were inserted (i.e. piped or manual), etc.?  Or was there already some fluid in the machine when it was placed down?

**Comment by DevTimur** [comment] 2019-04-09 11:12
Yeap, had same issue.
I think with version 332. Need to test it again. I think it's something to do with me leaving chunk, and coming back again. Or with leaving PPT runing for a long time undistrubled. PPT just forgets it have items inside, and start processing Diesel into Kerosene even with redstone inside.

Here is how i remember it was working. I have PPT for lubricant, inserted redstone, gave heat. While it had Diesel all worked fine, then run out of diesel, stopped, had some spare redstone inside. Distillery keep making more diesel slowly. I left for a while. I come to take more lubricant later, but there was no lubricant, only Kerosene and redstone in slot. Instead of making Lubricant it forget about redstone and start refining Diesel into Kerosene becasuse it had enough of heat.

**Comment by Dusty-Sprinkles** [comment] 2019-04-15 02:35
I also have this problem, I have had my processing plant for a while and every time I close its menu after replacing the coal, it will fail to run on its own 

Also I've been running PO3, so it's an issue on whichever version that pack is using for sure.

**Comment by desht** [comment] 2019-04-15 13:38
I'm away in RL for a bit, but I'll take a closer look at this when I get back, hopefully next week. I have a couple of ideas on what's going on here (not being properly triggered to rescan for the correct recipe to use).

**Comment by Sakata-MC** [comment] 2019-04-17 15:06
I'm having this issue as well, even when staying in the chunk.  For me though, the TPP stops producing anything until I empty the tank. (possibly different because my TPP for plastic actually works)

**Comment by desht** [comment] 2019-04-21 17:20
933da03fa8c8d8293b6cfe4fdd33f2b36ea6f6d4

**Comment by desht** [comment] 2019-04-28 16:33
Fixed in 0.10.4 release.

**Closed by desht** 2019-04-28 16:33 UTC
Labels: Bug, Fixed in Dev
