### ISSUE TITLE
Can't make certain plastics

### ISSUE THREAD

**Issue by Hasan2143** [TeamPneumatic/pnc-repressurized#370] opened 2019-07-11 01:24 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

Minecraft Version - 1.12.2

 Forge Version - forge1.12.2-14.23.5.2768

Mod Version - 0.11.3-366

Can't seem to craft brown or green plastic as I hover over them, they do not highlight and sometimes the gui will freeze on the text of the last thing I hovered on such as another plastic. However changing from full screen to a window seems to fix it or changing the gui scale from auto to anything else, but that then makes the gui too small to play for my size monitor which is 27 inch and a 1920 x 1080p resolution.

![2019-07-11_02 14 30](https://user-images.githubusercontent.com/52745279/61015316-ff8cbc00-a382-11e9-8008-3f5db071ab4a.png)

![2019-07-11_02 14 22](https://user-images.githubusercontent.com/52745279/61015310-f4399080-a382-11e9-8475-685c72413d1e.png)

![2019-07-11_02 14 43](https://user-images.githubusercontent.com/52745279/61015320-07e4f700-a383-11e9-9da1-3f696c21ebe7.png)

**Comment by Nethet** [comment] 2019-07-13 09:22
do you tried it without the texture pack ?

**Comment by Hasan2143** [comment] 2019-07-14 19:00
Yes I just tried it there same issue unfortunately

**Comment by desht** [comment] 2019-07-15 08:33
I've just tested at 1920x1080 with Auto GUI scale, and I don't see the problem; green and brown buttons are working fine here.

**Comment by Hasan2143** [comment] 2019-07-15 11:56
Idk what the problem is on my end just that changing the gui scale from
auto or pressing F11 to exit fullscreen fixes it

**Comment by desht** [comment] 2019-07-15 15:43
I'll keep this open for now and see if I can reproduce it somehow.  Not sure what the difference is here, other than the texture pack (which *shouldn't* make a difference, but...)

**Comment by Hasan2143** [comment] 2019-07-15 16:19
If you want and it helps I can send a list of the mods I have installed in
case the problem lies in there

**Comment by dovisutu** [comment] 2019-08-08 15:07
I can't reproduce it either, despite from the language I'm using.

**Comment by desht** [comment] 2021-03-26 17:08
Closing, 1.12.2 is long out of support.

**Closed by desht** 2021-03-26 17:08 UTC
Labels: Can't Reproduce
