### ISSUE TITLE
Chinese paragraph segmentation

### ISSUE THREAD

**Issue by djkcyl** [TeamPneumatic/pnc-repressurized#585] opened 2020-08-22 11:16 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
2020.8.22 Github Source code Compile
### Describe your problem, including steps to reproduce it
When using lang with Chinese characters, gui.tooltip.block and gui.tab.info cannot automatically wrap, and the font is too small to see clearly

like this
![6 A 3UEXYT6KC88F`$DZZ$X](https://user-images.githubusercontent.com/59153990/90954905-61d34e00-e4ab-11ea-8aad-4be2fc2d8a53.png)

![C_ 1NMPI@HN~I$SQEP `NJ2](https://user-images.githubusercontent.com/59153990/90954911-6dbf1000-e4ab-11ea-8133-8599e4bc41a4.png)

And when using Chinese characters, it will display format error
![U GRP)~FSP3M71DXNEGZJ$C](https://user-images.githubusercontent.com/59153990/90954947-b8408c80-e4ab-11ea-9a06-c37f11653c2d.png)

### Any other comments?
NO

**Comment by desht** [comment] 2020-08-22 15:16
Where did you get Chinese translations for 1.16?  1.16.2 only ships with en_us translations.

**Comment by djkcyl** [comment] 2020-08-22 15:19
> Where did you get Chinese translations for 1.16? 1.16.2 only ships with en_us translations.

I am a member of https://github.com/CFPAOrg/Minecraft-Mod-Language-Package, I am making Chinese translations, and now I have a little problem

**Comment by desht** [comment] 2020-08-22 15:40
I think the problem is your translated text doesn't contain any ASCII space characters, which is what the mod uses to split up text for formatting.  If there's a particular Unicode character (or characters) commonly used in Chinese text as whitespace, let me know what and I can add that to the list of word delimiters in the text formatting code.

**Comment by djkcyl** [comment] 2020-08-22 15:56
There is no such space in Chinese

**Comment by djkcyl** [comment] 2020-08-22 15:57
There are no spaces for separating characters in Chinese paragraphs
But if you can break lines by judging the number of characters, it may be helpful for Chinese paragraphs

**Comment by desht** [comment] 2020-08-22 17:19
Yeah I could force a break after a certain number of characters, even when there's no whitespace, I suppose.

**Comment by djkcyl** [comment] 2020-08-22 17:21
Ok, looking forward to the new version

**Comment by desht** [comment] 2020-08-23 08:56
Regarding the format error problem, I would need to see the text you're providing, but you probably have the wrong number of "%" characters - "%" is used as a formatting marker and needs to be escaped.

**Comment by djkcyl** [comment] 2020-08-23 08:58
> Regarding the format error problem, I would need to see the text you're providing, but you probably have the wrong number of "%" characters - "%" is used as a formatting marker and needs to be escaped.

I have fixed the format error, just use %%

**Comment by djkcyl** [comment] 2020-08-23 08:59
"gui.tooltip.block.pneumaticcraft.advanced_air_compressor" : "这个机器是空气压缩机的二级版本。 像他的稍逊一筹的兄弟那样， 它可以使用任何能在熔炉中燃烧的燃料产生压缩空气。 但是， 这台机器的生产速率为50ML/TICK，他同时也产生热量。 热量越高，效率也就越低。 GUI内温度条底部的箭头指示了效率将开始下降的位置， 而顶部的箭头指示了效率降至0%%的标记。你可能会失望， 此机器不会在温度过高时爆炸。",

**Comment by desht** [comment] 2020-08-23 11:35
Yep, that should do it!

**Comment by desht** [comment] 2020-09-03 09:02
Fixed in 2.2.0 and 1.4.5 release

**Closed as completed by desht** 2020-09-03 09:02 UTC
Labels: Bug, Fixed in Dev, Documentation
