### ISSUE TITLE
Disappearing Logistics Frames

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#439] opened 2020-03-21 20:28 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.11-390
### Describe your problem, including steps to reproduce it
Logistics frames are disappearing from my logistics pipe setup. It seems to happen when the chunks are unloaded and re-loaded. I've had them placed on modded blocks from other mods, pneumaticcraft omni-hoppers, and vanilla chests and in all cases they just vanish when I come back to the chunk. 

If it changes anything, I've got the chunks claimed with FTB utilities. This is also an Enigmatica 2 Expert world that I've manually added PNC to.

**Comment by desht** [comment] 2020-03-22 11:19
Sigh. Semiblocks are the bane of my existence. At least in 1.14.4 these problems should be largely gone since I did a complete rewrite (they're now just regular entities instead of a bunch of custom code). Doesn't help in 1.12 though, I appreciate.

Is there anything in your log file about this? Any errors? This could be very hard to track down if I can't reproduce it (which I can't, right now)...

**Comment by MuteTiefling** [comment] 2020-03-22 18:31
I'll try to reproduce it again and get the logs. Sorry, didn't think to include them at the time.

**Comment by MuteTiefling** [comment] 2020-03-22 19:08
Logs: https://gist.github.com/MuteTiefling/9a160d1bab06c6919dba6b20648d27df

I'm not seeing anything. At 14:54 I wrenched a drone with a logic issue in it's programming. I then set up a miniature logistics setup similar to what I had before. It's just an active provider pushing stone to a storage. I then flew away (pneumatic armor flight, so pretty speedy) and flew back. 

The difference this time is that they kept functioning (items were moving), but were no longer configurable with the configurator. I couldn't remove the frame either and breaking the inventory they were on doesn't return the frame.

**Comment by MuteTiefling** [comment] 2020-03-30 10:20
After observing this for a while longer, it really seems to be related to chunk loading. I had two other logistics pipes setups back in the main area of my base that've been fine for weeks. The only glitch being that the frames would occasionally start showing even though they were flagged invisible.

Both of those have been chunk loaded the entire time. 

Anything new I set up outside of permanently loaded chunks, however, breaks when I leave.

**Comment by desht** [comment] 2020-03-30 10:59
I can't reproduce this behaviour at all.  What other mods do you have loaded?

**Comment by MuteTiefling** [comment] 2020-03-30 12:22
It's enigmatica 2 expert with pneumaticcraft added. That's the only modification to the pack.

**Comment by desht** [comment] 2020-03-31 07:46
Update: I set up a E2E instance plus PneumaticCraft and did a bunch of testing with various combinations of claimed and loaded chunks.  Set up a few chests with various frames on them, and then teleported 1000 blocks away, went to the nether etc., came back... and the logistics frames were fine.

I've no idea how to reproduce your problem, sorry :(  Just can't get them to break in the way you're seeing.

Just as an experiment, can you try loading the world without Foamfix & BetterFPS enabled?  (Not sure if there are any other optimisation mods in E2E...)  Foamfix in particular can trigger odd problems in other mods.

**Comment by MuteTiefling** [comment] 2020-04-04 13:59
Alright, I'll give that a try. If it doesn't work I"ll just give up on it I guess. I do really appreciate your attempts to figure this out though. Thank you very much!

**Comment by desht** [comment] 2021-03-17 10:52
Gonna close this, logistic frames use a completely different implementation in 1.14+ (they're entities now) and are way more robust than in 1.12.

**Closed by desht** 2021-03-17 10:52 UTC
Labels: Can't Reproduce

**Comment by ErnestoPeroPezzi** [comment] 2021-04-23 20:24
Apologies for posting to a closed issue, but I have done a bunch of testing on this myself (also on Enigmatica 2 with +100 mods added). 

This happens because of Forges own chunk caching. If you set the cache to 0, blocks will not dissapear. Something about keeping metadata about attached blocks does not sit well when they are cached. This is also an issue with the Transfer gadget, as well as Thaumcraft seals and other "blocks" that occupy the same space as standard blocks.

I do not know what interaction causes this, as I assume this normally does not happen. But once again, disabling Forge chunk caching will stop it from happening
