### ISSUE TITLE
Can't seem to get Heat Frame to work

### ISSUE THREAD

**Issue by pharaun** [TeamPneumatic/pnc-repressurized#192] opened 2018-06-18 00:25 UTC
### Minecraft Version
- 1.12.2

### Forge Version
- 14.23.3.2702

### Mod Version
- 1.12.2-0.6.7-210

### Describe your problem, including steps to reproduce it
Right clicking any inventory with a heatframe seems to cause a stacktrace: https://gist.github.com/pharaun/4d2b906d18c46e7a4f4feb29aca04a88

**Comment by desht** [comment] 2018-06-18 07:13
Confirmed.  Looks like an easy fix though.

**Comment by desht** [comment] 2018-06-18 07:56
Fixed in build 213+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/changes

Will be in the 0.6.8 bugfix release out fairly soon

**Comment by desht** [comment] 2018-07-02 07:52
Fixed in 0.6.8 release

**Closed by desht** 2018-07-02 07:52 UTC
Labels: Bug, Fixed in Dev

**Comment by pharaun** [comment] 2018-07-14 19:02
This is confirmed to work, thank you :)
