### ISSUE TITLE
Server crashes when villager house worldgen is overwritten by another feature

### ISSUE THREAD

**Issue by jeremiahwinsley** [TeamPneumatic/pnc-repressurized#717] opened 2021-01-16 00:18 UTC
### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
2.9.2-116
### Describe your problem, including steps to reproduce it
[crash-2021-01-15_23.54.11-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5823483/crash-2021-01-15_23.54.11-server.txt)

Seems to be caused by worldgen from other mods overwriting parts of the villager house, causing the tubes/air compressor to be in an invalid state.

### Any other comments?
Another crashlog from previous version here: https://github.com/AllTheMods/ATM-6/issues/233

**Comment by desht** [comment] 2021-01-16 10:48
I couldn't reproduce this myself (worldgen-related problems are usually very random in nature), but I have added some extra validation to hopefully prevent this occurring.  Fix is in build 118 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/, or wait till 2.9.3 is released (probably in next couple of days).

**Comment by desht** [comment] 2021-01-18 12:50
Fixed in 2.9.3

**Closed as completed by desht** 2021-01-18 12:50 UTC
Labels: Bug, Fixed in Dev
