### ISSUE TITLE
Items In The Pressure Chamber Disappearing

### ISSUE THREAD

**Issue by EmosewaGamer** [TeamPneumatic/pnc-repressurized#56] opened 2017-11-17 18:58 UTC
So to test out the mod, the first thing I did was put a few Iron Ingots in a Pressure Chamber. I went ahead to test out some other things and when I came back to the chamber, they were gone. At first, I thought that they had despawned, but after 3 tests, I realized that they disappear once the arrow reaches 1. I have yet to test it with other items.

**Comment by desht** [comment] 2017-11-17 22:06
Just to be clear, you put the ingots in an unpressurized chamber and then raised the pressure, right?

I'll do some testing on this..

**Comment by EmosewaGamer** [comment] 2017-11-17 22:17
I believe that there was a bit of pressure in it so start with.

**Comment by desht** [comment] 2017-11-18 09:18
Hmm.  Do you have an interface in this pressure chamber?  Because as soon as the interface (one with the 'I' facing into the chamber) gets enough pressure it will pull whatever is in the chamber out. It doesn't distinguish between ingredients and finished products - you have to filter it, and/or use redstone to control when it pulls.

**Comment by EmosewaGamer** [comment] 2017-11-18 10:14
Nope.

**Comment by desht** [comment] 2017-11-18 11:16
OK, I don't know what to say then. I can't reproduce it at this point.

**Comment by MineMaarten** [comment] 2017-11-19 09:51
Could it still be the items despawned? Have you put in an 'Item Life Upgrade' into the Pressure Chamber to make sure?

**Comment by EmosewaGamer** [comment] 2017-11-19 13:17
Nope, they were in there for less than a minute and it always happened once the pressure reached 1bar.

**Comment by desht** [comment] 2017-11-19 13:20
Any chance of some images or even a video of your setup? Might make it easier to reproduce.

**Comment by desht** [comment] 2017-11-23 19:49
Any updates please? This can't be reproduced, I really need to see what your setup looks like.

**Comment by EmosewaGamer** [comment] 2017-11-24 09:47
This is my setup:
![image](https://user-images.githubusercontent.com/25333164/33204113-bb94f700-d102-11e7-9d90-3c5a9c6f3633.png)

 The first time I tested it today, it reached 1 and 1/3 the bar became green again, but the ingot were still there. When it reached 1 and 2/3 they disappeared. Should I have mentioned that I always  put a full stack of Iron Ingots in?

 The second time I tested it, I started using the Manometer and it seemed that the ingots disappeared when the pressure reached 1.8bar.

 The third time I tested it, it worked, but it only gave me 3 Compressed Iron Ingots from that full stack of Iron Ingots.

  On my 4th test they disappeared when it read 1.2bar.

 On my 5th test they disappeared when it reached 1.5bar.
![image](https://user-images.githubusercontent.com/25333164/33204713-a9fe3752-d104-11e7-9583-b883a0656313.png)
![image](https://user-images.githubusercontent.com/25333164/33204721-af33b210-d104-11e7-9257-26c7ae6fdf19.png)

**Comment by desht** [comment] 2017-11-24 10:32
I honestly don't know.  I've tried everything and I cannot make any ingots disappear under any circumstances, regardless of pressure.  And you *definitely* have no interface in this setup?

**Comment by desht** [comment] 2017-11-24 10:33
And what other mods do you have installed?  Can you test this out in a minimal instance with as few mods as possible?

**Comment by desht** [comment] 2017-11-28 07:45
I could still use a mod list here...

**Comment by MineMaarten** [comment] 2017-12-02 14:21
Working on https://github.com/TeamPneumatic/pnc-repressurized/issues/52, which is expected to resolve this, as we will be getting rid of any item entities.

**Comment by desht** [comment] 2017-12-09 11:45
#52 is merged to master now, and should make this a non-issue since items in the chamber are not entities any more.

**Closed by desht** 2017-12-09 11:45 UTC
