### ISSUE TITLE
Smart Chest with Magnet Upgrade is not working

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#613] opened 2020-09-15 14:01 UTC
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.4.5-69

### Describe your problem, including steps to reproduce it
A smart chest with a magnet upgrades does not seem to be picking up items and the show area does not show an area.

### Any other comments?
Of course, I could be doing something wrong.

**Comment by desht** [comment] 2020-09-15 14:56
Have you configured one or more of the sides to pull items? (use the Side Configuration tab in the GUI to control which sides push or pull)

**Comment by duncanwebb** [comment] 2020-09-16 16:34
Thanks, that works but is a bit confusing. I expected that these buttons are for adjacent inventories.
With a dispenser upgrade it pushes (jettisons) into the world 
With a magnet upgrade it pulls (collects) from the world
If there is an adjacent inventory then the smart chest pushes or pulls with or without an upgrade.

BTW, when I sort the inventory it moves the upgrades into the inventory and sort these.

**Comment by desht** [comment] 2020-09-17 07:05
No, the buttons affect all forms of item pushing & pulling.  It is arguably a bit counter-intuitive but it does allow for a huge amount of flexibility.

What mod are you using to sort the inventory?  Upgrades are stored in their own item handler internally, so I'm surprised they're being sorted with the main inventory.

**Comment by duncanwebb** [comment] 2020-09-17 17:37
I agree that the smart chest is a mighty block, very useful.

The sorting mod is https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed

Thanks again for your help.

**Comment by desht** [comment] 2020-09-18 07:19
Just had a look at Inv Tweaks renewed source code, and I would say the problem is on their side.  Looks like they just take every single slot that isn't a player slot and sort all the items from those slots.  So it doesn't differentiate between items in the main  chest inventory and items in the upgrade inventory.  I'd raise an issue with them about that (and point them at the `Slot#isSameInventory()` method...)

Gonna close this one since I think everything's working?  Feel free to reopen if there are any more issues.

**Closed as completed by desht** 2020-09-18 07:19 UTC

**Comment by duncanwebb** [comment] 2020-09-18 15:34
On a smart chest with a magnet and range upgrades I placed a sentry turret and the chest pulled the ammo out turret, it makes sense that it works this way as all sides were set to pull. 

Would it be possible to have a second set of buttons when upgrades are installed in the smart chest?

**Comment by duncanwebb** [comment] 2020-09-24 11:51
https://github.com/reo-ar/InvTweaksRenewed/issues/20
