### ISSUE TITLE
Any fluid can be placed in the memory stick and converted to XP

### ISSUE THREAD

**Issue by Random832** [TeamPneumatic/pnc-repressurized#851] opened 2021-07-12 06:49 UTC
### Minecraft Version
1.16.5

### Forge Version
36.1.32

### Mod Version
1.16.5-2.13.1-202

### Describe your problem, including steps to reproduce it
- Fill a tank with water or any other fluid
- Click an empty memory stick on it [or if in creative mode, fill it via the bucket slot of the tank]
- At this point, note that:
  - the memory stick says it has 1600 XP (31 levels) stored
  - you cannot place player levels in the stick by right clicking, and it will no longer absorb xp orbs
  - if you empty the stick into a tank, it still contains water
- shift right click with the stick to retrieve the water as player XP. this works.

### Any other comments?
As an enhancement suggestion I would like for the memory stick to be able to legitimately contain (or perhaps convert to memory essence stored internally) other mods' XP fluids, but obviously water is not an XP fluid. This would obviously require a significant rewrite though.

I do see that the capability is initialized with a predicate "fluid -> fluid == ModFluids.MEMORY_ESSENCE.get()", but this clearly isn't working correctly. It seems the real issue lies with the predicate not being called where necessary by the fluid handler itself or by other code that interacts with it [including the pneumaticcraft small fluid tank].

**Comment by desht** [comment] 2021-07-12 07:57
Confirmed.  That's definitely not right...!

**Comment by desht** [comment] 2021-07-12 08:12
That'll be fixed in 2.13.2 release.  The enhancement idea (accepting other XP fluids) won't be going in at this point for both technical and gameplay reasons:
* XP in the memory stick is currently stored as a fluid, not as an XP count.  This makes it more complex to store other fluids in there.
* The Aerial Interface is really the intended way of converting XP type in PneumaticCraft, and that's quite late game.  This would be far earlier in the game.

Not saying it'll never happen, but not right now...

**Comment by desht** [comment] 2021-07-21 08:30
Fixed in 2.13.2 release

**Closed as completed by desht** 2021-07-21 08:30 UTC
Labels: Bug, Fixed in Dev
