### ISSUE TITLE
Flowing Ether Gas (Industrial Foregoing) over heat sinks causes NPE and crash

### ISSUE THREAD

**Issue by ZeMilkmann** [TeamPneumatic/pnc-repressurized#902] opened 2021-10-02 00:02 UTC
### Minecraft Version
1.16.5

### Forge Version
forge-1.16.5-36.2.6

### Mod Version
1.16.5-2.14.4-258

### Describe your problem, including steps to reproduce it
Flowing Ether Gas (Industrial Foregoing) over heat sinks causes crash

To reproduce,
1.  Build something like this: ![AsPowerBar_CMBMAh5qQg](https://user-images.githubusercontent.com/25730514/135696432-7e5fe924-a118-4740-af27-b27047f12fc7.png)
? 

2. Place Ether Gas like this: 
![image](https://user-images.githubusercontent.com/25730514/135696823-aae0d907-a362-4527-aec9-87dacf8bd307.png)

3. Minecraft immediately crashes, the crash report looks like this: 
[crash-2021-10-02_01.56.32-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7270600/crash-2021-10-02_01.56.32-server.txt)

**Comment by desht** [comment] 2021-10-02 12:01
I can't reproduce this in my dev world - flowing fluids never cause a crash when flowing across heat sinks.  I'm also very suspicious of the `MixinWorldRedstone` in the stacktrace, but I don't know what mod that is coming from.

Having said that, if you can try build 262 from https://jenkins.k-4u.nl/view/Desht/job/PneumaticCraft-Repressurized-1.16/, it would be useful to know if that helps.  If there's still a crash, I'm going to go ahead and blame that mixin, whatever it is.

**Comment by ZeMilkmann** [comment] 2021-10-02 15:07
First of all: Your fix absolutely works, thanks!

### Further investigation

Since you said you didn't know what mod the MixinWorldRedstone is from, I unpacked all my mod JAR files to find the MixinWorldRedstone.java and the only thing I found was from https://github.com/shBLOCK/IntegratedProxy

I removed IntegratedProxy, and using build 258 the crash still occurs just the same, the stack trace now makes reference to World.java instead of MixinWorldRedstone.java. [crash-2021-10-02_16.46.04-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7271671/crash-2021-10-02_16.46.04-server.txt)

**Comment by desht** [comment] 2021-10-02 17:10
Ok, was my fault then! Fix will be in the next PNC release.

**Comment by desht** [comment] 2021-11-10 10:49
Fixed in 2.14.5 release

**Closed as completed by desht** 2021-11-10 10:49 UTC
Labels: Bug, Fixed in Dev
