### ISSUE TITLE
Crash: after joining multiplayer or singelplayer world

### ISSUE THREAD

**Issue by Kevin1710** [TeamPneumatic/pnc-repressurized#818] opened 2021-06-08 11:16 UTC
Hello,
I want to report a bug. 
When I enter a singleplayer or multiplayer world and then re-enter a singleplayer world, the game crashes. When I re-enter a multiplayer world, this does not happen.

I attached the crash report. 
[crash-2021-06-08_13.03.27-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6615991/crash-2021-06-08_13.03.27-client.txt)

kind regards
Kevin1710

**Comment by desht** [comment] 2021-06-08 11:56
Duplicate of #811

**Comment by desht** [comment] 2021-06-08 11:56
Already fixed in 2.12.5.  Also, please don't overwrite the issue template.  It's there for a reason.

**Comment by Kevin1710** [comment] 2021-06-08 11:57
Ah okay sorry and thank you. Didn't see the duplicate.

**Closed as completed by desht** 2021-06-08 11:56 UTC
Labels: duplicate
