### ISSUE TITLE
Bucket of molten plastic won't cool in an inventory with cooled heat frame (dedicated server)

### ISSUE THREAD

**Issue by RealTraxData** [TeamPneumatic/pnc-repressurized#997] opened 2022-05-02 04:38 UTC
![image_2022-05-02_073855074](https://user-images.githubusercontent.com/104749192/166185053-b02ad414-279a-4394-996b-be5a62c37863.png)
![image](https://user-images.githubusercontent.com/104749192/166185058-2441a520-a381-4740-b543-cbce48c5497e.png)
### Describe the bug

the molten plastic won't cool chest with cooled heat frame

### How to reproduce the bug

molten plastic in a chest with cooled heat frame

### Expected behavior

molten plastic turning in plastic sheet

### Additional details

if i place in world it will become in plastic but not in chest
the mod is in valhelsia volatile modpack

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment] 2022-05-02 11:56
Confirmed.

**Comment by desht** [comment] 2022-05-02 12:04
Looks like the Forge `FluidUtil.getFluidContained()` method is broken and failing to find plastic in a bucket item.

**Comment by desht** [comment] 2022-05-09 07:45
Fixed in 3.2.2 release

**Closed as completed by desht** 2022-05-09 07:45 UTC
Labels: Bug, Fixed in Dev
