### ISSUE TITLE
Iron got destroyed after being blown up

### ISSUE THREAD

**Issue by ChromaPIE** [TeamPneumatic/pnc-repressurized#824] opened 2021-06-19 07:39 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.1.32

### Mod Version
2.12.5-190

### Describe your problem, including steps to reproduce it
As has been described here: https://github.com/henkelmax/delivery-inc/issues/19
The environment is Delivery Inc. modpack, in case it turns out to be caused by some other mods.

**Comment by desht** [comment] 2021-06-19 08:10
Can you confirm that `explosionCrafting` isn't disabled in the config (`pneumaticcraft-common.toml`) and that explosion crafting recipes haven't been removed in this pack?

Otherwise, it's pretty much certainly caused by some other mod (possibly cancelling an `EntityJoinWorldEvent` for item spawing... ItemPhysic maybe?)

I've never seen this happen, and with no way to reproduce it, there's very little I can do about it.

**Comment by ChromaPIE** [comment] 2021-06-19 09:27
Neither the config nor datapacks got that disabled, and ItemPhysic is not present in the modpack. One noticeable thing is that there exists a mod or a feature seemingly causing every single blocks broken by explosions to drop themselves, that is to say, none of them got voided, and this is the only non-vanilla behavior witnessed that is related to explosion. I'll give it a deeper look.

**Comment by desht** [comment] 2021-06-19 09:34
Yeah, that sounds like a very likely culprit.  If you can find out which mod that is, I can take a closer look at what it's doing.

**Comment by ChromaPIE** [comment] 2021-06-19 14:14
It's Sodium Reforged. CurseForge page here: https://www.curseforge.com/minecraft/mc-mods/sodium-reforged
From its config I'm not able to find anything related. I've opened an issue on their side as can be seen above.

**Comment by desht** [comment] 2021-06-25 07:16
Gonna close this since I'm pretty sure this is all down to Sodium.

**Closed as completed by desht** 2021-06-25 07:16 UTC
Labels: other mod issue, Can't Reproduce
