### ISSUE TITLE
Applied Energistics does not consume Lubricant buckets...

### ISSUE THREAD

**Issue by Xiaminou** [TeamPneumatic/pnc-repressurized#46] opened 2017-11-15 22:00 UTC
When crafting the speed upgrade with Applied Energistics' crafting method it does not consume the Lubricant bucket.
Normal crafting table crafting does consume the bucket.

**Comment by desht** [comment] 2017-11-16 08:58
I can't reproduce this.  The lubricant is always consumed in my testing, leaving an empty bucket.  Tried this both with crafting in the AE2 crafting terminal, and via a stored pattern.  Works as expected both ways.

**Comment by Xiaminou** [comment] 2017-11-16 13:44
Yeah it does not consume the lubricant in the bucket is what I meant.
I thought it was a weird one, I can't think of a reason why this is happening.

**Comment by desht** [comment] 2017-11-16 14:08
Can you still reproduce this?  I have not been able to.

**Comment by Xiaminou** [comment] 2017-11-16 14:23
I will try in a new instance, but it occurred to me that it might just be because my version of PNC:R is outdated.

**Comment by KamranMackey** [comment] 2017-11-16 14:26
@Xiaminou Yes, its most likely still in the approval stage. Frickin CurseForge. I get they need to sleep but I hate this new approval time BS.

**Comment by Xiaminou** [comment] 2017-11-16 14:31
Oh, I think I found a clue.
The Lubricant buckets I'm getting are from Immersive Petroleum.
![2017-11-16_15 30 03](https://user-images.githubusercontent.com/8670392/32896366-24d054b0-cae3-11e7-9a74-1809623c75a9.png)

**Comment by KamranMackey** [comment] 2017-11-16 14:37
@Xiaminou Try updating your PNC:R version, as I think the Immersive Petroleum conflicts were already fixed.

**Comment by Xiaminou** [comment] 2017-11-16 14:38
I tried updating but can't seem to be able to build it anymore which is why I'm waiting for Curseforge.

**Comment by KamranMackey** [comment] 2017-11-16 14:39
@Xiaminou Just recreate your dev environment and try building again.

**Comment by Xiaminou** [comment] 2017-11-16 14:40
That's what I did.

**Comment by KamranMackey** [comment] 2017-11-16 14:50
@Xiaminou Here, try this. I just compiled it. Should work. https://drive.google.com/open?id=1CNNLjPkOTm4a8c9s2idLjD9o6TD7Izh1

**Comment by Xiaminou** [comment] 2017-11-16 15:05
@KamranMackey Thanks.

**Comment by KamranMackey** [comment] 2017-11-16 15:08
@Xiaminou No problem. 👍

**Comment by Xiaminou** [comment] 2017-11-16 15:18
So it happened once more, and now it works.
The one time that it happened the "crafting plan" window was showing a PNC:R Bucket instead of a IP Bucket.

**Comment by desht** [comment] 2017-11-16 15:46
Interesting.  Not sure I can do much about it.

Upload of the first alpha is gonna be delayed a little, since I'm waiting on MineMaarten to upload a new version of IGW (current released version will crash in conjunction with this version of PNC:R).  Hopefully soon, but not under my control :)

**Comment by KamranMackey** [comment] 2017-11-16 16:01
@desht The gradle.properties file has 1.4.1-10 listed though, not -8.

**Comment by desht** [comment] 2017-11-16 16:31
I know, but the current IGW release on CurseForge is **-8**.  **-10** is what it's currently being built against, and there has been an API change.

**Comment by KamranMackey** [comment] 2017-11-16 19:37
@desht MineMaarten has updated the IGW Mod on CF to build 1.4.2-11. :) Just wanted to let you know.

**Comment by desht** [comment] 2017-11-17 13:43
Yep, alpha release is uploaded to CF now, just waiting on approval.

**Comment by desht** [comment] 2017-11-26 20:03
As far as I can tell, this is all working OK now. Closing.

**Closed by desht** 2017-11-26 20:03 UTC
