### ISSUE TITLE
Oil Transparent when inside of it

### ISSUE THREAD

**Issue by zachsai** [TeamPneumatic/pnc-repressurized#970] opened 2022-03-15 07:22 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/63996164/158326279-b7af7036-6e4a-4817-b23a-71e995458fea.png)
![image](https://user-images.githubusercontent.com/63996164/158326712-3c856bea-f88b-4d16-9ddc-78ec8499f2cf.png)

You can see here, also it happens without optifine installed

### How to reproduce the bug

Go in oil 2 deep blocks

### Expected behavior

not be transparent

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment] 2022-03-15 08:11
Duplicate of #861 and others

**Closed as completed by desht** 2022-03-15 08:11 UTC
Labels: Bug, duplicate, wontfix

**Comment by Lgmrszd** [comment] 2022-07-30 18:52
It's not a duplicate since the original issue was made for 1.16 and was closed with this comment
> Modded fluids simply don't behave like water, and won't until at least Minecraft 1.17.
While this one was made for 1.18

I also believe you can add water-like physics to fluids by adding them to the `#minecraft:water` tag now :smile:

**Comment by desht** [comment] 2022-07-30 21:52
The fluid update is in Forge 1.19, and recent 1.19 PNC builds use that for proper fluid physics. There is zero possibility of that ever appearing in any earlier version of the mod.

You can indeed add water-like physics to fluids via tagging, but that could cause unexpected side effects, which I have no intention of supporting...
