### ISSUE TITLE
dig widget blacklist not working

### ISSUE THREAD

**Issue by kbruins** [TeamPneumatic/pnc-repressurized#634] opened 2020-10-14 15:51 UTC
16.3 Minecraft Version

34.1.0 Forge Version

2.4.2-49 Mod Version

i am making a digging program that needs to ingore ores that are affected by the fortune enchantment. so i try to blacklist those affected ores but when i let the program run the ores still get mined. whitelisting does work correctly.

to reproduce simply try blacklisting a block in the dig widget and let the drone do its work.

**Comment by desht** [comment] 2020-10-14 16:23
Confirmed.  Added diamond ore to the blacklist (and checked the "Blockstate" checkbox) but the drone mined diamond ore anyway.

**Comment by desht** [comment] 2020-10-14 16:28
I think I see the problem.  Matching by blockstate was originally intended for blocks that never dropped an item (I believe Shoggoth slime from Abyssalcraft was the motivator), so the the filter doesn't match blocks that *do* drop an item.

I *think* it will be OK to ignore the item, and always match by block only if the Blockstate option is checked, but I'll need to do a bit more testing...

**Comment by desht** [comment] 2020-10-14 16:40
Build 57 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ should fix your problem.  Or you can wait for the 2.4.3 release in the next day or two.

**Comment by kbruins** [comment] 2020-10-14 16:58
thank you for responding.

**Comment by desht** [comment] 2020-10-15 10:21
Fixed in 2.4.3 release

**Closed as completed by desht** 2020-10-15 10:21 UTC
Labels: Bug, Fixed in Dev
