### ISSUE TITLE
Logistics Drones

### ISSUE THREAD

**Issue by Greysakk** [TeamPneumatic/pnc-repressurized#1305] opened 2024-05-17 22:38 UTC
### Describe the bug

Placing down a logistics drone breaks water pumping to a create steam engine.  Removing the drone and manipulating the water source restore water flow.  Suspect the drone interacts with liquids creating some conflict with nearby fluid inventories?
Also, breaking the drone duplicates the drone.

### How to reproduce the bug

Build create steam engine with sufficient water source.  Place logistics drone near the engine.

### Expected behavior

Drones should not interact with inventories and machines they are not assigned to.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.15

**Comment by desht** [comment] 2024-05-18 12:28
There's not enough info to go on here.  Please provide specific instructions on reproducing the problem (a video might be helpful).

> Drones should not interact with inventories and machines they are not assigned to.

They don't, but what do you mean exactly by "assigned to" ?  You don't "assign" a logisitics drone to anything; it looks for inventories and fluid tanks with logistics frames attached to them, and handles requests for those.

**Comment by Greysakk** [comment] 2024-05-19 05:23
I tried uploading a larger video, but file size limitations are what they are.
Hopefully this helps, a little.

https://github.com/TeamPneumatic/pnc-repressurized/assets/170145635/f0d44173-4d82-420f-bb98-0e1a9b86de99

**Comment by desht** [comment] 2024-05-19 07:44
It doesn't.  What am I supposed to be seeing?

**Comment by Greysakk** [comment] 2024-05-19 17:17
The gauge indicating capacity water and heat level in the tank indicates that it has water before the drone is put down.  immediately after the drone is put down the water goes down to nothing.  this only happens when a drone is put down.  tested with both a logistics drone and a programmable one.

**Comment by Greysakk** [comment] 2024-05-19 17:19
As an aside.  I haven't made any logistics frames as of yet.  I don't know what the drone is supposed to attaching to.  but it thinks that a water tank/ steam engine is something that it should be interacting with.

**Comment by Greysakk** [comment] 2024-05-19 17:30
I think I found the root offender.  I uninstalled a mod called Nightmare Mobs.  And that seems to have corrected the issue.  I have no idea why that particular mod has that interaction.  But removing that mod seems to have corrected the issue.

**Comment by desht** [comment] 2024-05-20 09:34
Interesting.  If there isn't a logistics frame on the tank/machine, then I can categorically state that the drone will not interact with it in any way. It simply isn't interested in blocks that don't have a frame attached.

Gonna close this, since I don't think there's anything I can (or need to) do here.

**Closed as completed by desht** 2024-05-20 09:34 UTC
Labels: Bug, other mod issue
