### ISSUE TITLE
In world rendering issue with tanks when Rubidium installed

### ISSUE THREAD

**Issue by Branjoman** [TeamPneumatic/pnc-repressurized#1150] opened 2023-03-04 23:57 UTC
### Describe the bug

When any of the tanks are placed in the world, the rendering of them does not function correctly. Instead of the window being transparent and rendering fluids inside, the window is instead opaque with vertical white and black lines. Screenshot of the issue:
https://i.imgur.com/Tly8k58.jpg
Note that the rendering of the tanks when in your inventory works fine.

Duplicate of the issue over on the rubidium github for reference:
https://github.com/Asek3/Rubidium/issues/427

### How to reproduce the bug

 - Install Pneumaticcraft:Repressurized version 4.3.3-22
 - Install Rubidium version 0.6.2
 - Place any tank down in the world

### Expected behavior

The tank window should be transparent and render any fluids placed inside

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.3-22

**Comment by desht** [comment] 2023-03-05 09:14
Rubidium issue, not PNC issue.  Also, dupe of #1121

**Closed as completed by desht** 2023-03-05 09:14 UTC
Labels: Bug
