### ISSUE TITLE
Crashed: Non-fluid definitions must have a temperature field!

### ISSUE THREAD

**Issue by coldReactive** [TeamPneumatic/pnc-repressurized#313] opened 2019-03-28 12:45 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2824
### Mod Version
1.12.2-0.9.3-324.jar
### Describe your problem, including steps to reproduce it
Tried to load the mod, crashed in Later mod loading phase (5-6/7)
### Any other comments?
Crash Log: https://pastebin.com/XZQa0jLc

**Comment by desht** [comment] 2019-03-28 13:49
Could you pastebin a copy of ``config/pneumaticcraft/BlockHeatProperties.cfg`` please?

**Comment by desht** [comment] 2019-03-28 14:03
Actually, I think I know what's going on - can you test out build 329 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and let me know if it loads (not at my dev machine to test right now).  I believe the problem is the new BlockHeatProperties.cfg file referencing blocks from unloaded mods, IC2 in your case.

**Comment by coldReactive** [comment] 2019-03-28 15:14
Yes, that new jar file does load properly.

**Comment by desht** [comment] 2019-03-28 15:40
Cool, I'll get a hotfix release out later today.

**Comment by desht** [comment] 2019-03-28 23:14
FIxed in 0.10.1 release

**Comment by utoxin** [comment] 2019-04-04 01:59
This just happened to me, running 0.10.2

**Comment by desht** [comment] 2019-04-04 06:35
@utoxin is this same issue as in #324 or a specific repeat of the "non-fluid definitions must have a temperature field" error?

**Comment by utoxin** [comment] 2019-04-04 17:24
Sorry, yeah. This was #324. I posted here first, then decided I should probably just open a new issue. Looking at the fix for this one, and my traceback, they weren't actually the same issue.

**Comment by desht** [comment] 2019-04-04 18:09
Ok

**Closed by desht** 2019-04-04 18:09 UTC
Labels: Bug
