### ISSUE TITLE
GPS tool tooltip not showing correct coordinates

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#655] opened 2020-11-23 15:12 UTC
### Minecraft Version
1.16.4

### Forge Version
35.1.0

### Mod Version
pneumaticcraft-repressurized-1.16.3-2.5.0-66

### Describe your problem, including steps to reproduce it
The GPS tool has one value but the tool tip shows another. This might be when the point has been edited.

![gps-tool-values](https://user-images.githubusercontent.com/4198031/99978509-52afb500-2da6-11eb-9b88-a707faf9ddf0.gif)

### Any other comments?
Would it be possible to use both point1 and point2 when setting coordinates from coordinate puzzle piece?

**Comment by desht** [comment] 2020-11-23 15:39
Ah yeah, I have a feeling this is fixed in dev.  Can you try build 74 from jenkins?  (That has a bunch of Programmable controller fixes too...)  And don't worry that the file has "1.16.4" in its name, it should run fine on 1.16.3 too (1.16.3 & .4 are very compatible with each other).

> Would it be possible to use both point1 and point2 when setting coordinates from coordinate puzzle piece?

I don't understand.  A coordinate is just a single point.  "Both point1 and point2" implies an area, not a coordinate.

**Comment by duncanwebb** [comment] 2020-11-23 20:54
I meant using the GPS Area tool, has two coordinates and I wanted to use both points to set two coordinate puzzle pieces. As this can show the area it is handy visualization of the area.

**Comment by desht** [comment] 2020-11-24 10:11
Build 77 should do you want, I think...

**Comment by duncanwebb** [comment] 2020-11-24 12:29
![gps-area-tool](https://user-images.githubusercontent.com/4198031/100093754-4421d600-2e58-11eb-85dd-197466d88a19.gif)

The numbers might be hard to see, so I uploaded it here.
https://streamable.com/kjkpt6

Hmm, doesn't look correct, no value is stored on the coordinate piece plus the position show was different from the tool tip. 

What I was expecting is if you click the left button it places point2 in the puzzle piece and the right-button puts point1 in the puzzle piece.

The pressure screen in the bottom-right corner.

![image](https://user-images.githubusercontent.com/4198031/100093884-72071a80-2e58-11eb-99e0-ad03278168dc.png)

**Comment by desht** [comment] 2020-11-24 13:58
I'm not seeing that pressure window behaviour, no.  No idea why it's doing that for you, I can't make it do that no matter how I move around or resize my screen.  What exact resolution and scaling are you using?

Area GPS Tools have never really worked for selecting a single coordinate, and I should probably just stop allowing them for such purposes.  Area GPS Tool provides an area, and when you try to get a coordinate from it, it will be an arbitrary coordinate within the tool's area.  Changing this would require a bunch of special-case code and a lot of ugliness.

Similarly, using right-click in the programmer gui to paste P1 vs P2 would also get pretty ugly due to the way the right mouse button is intended for opening the widget options gui.  I could possibly do left-click & shift-lift-click, though...

**Comment by duncanwebb** [comment] 2020-11-24 15:27
The screen is 1920x1080 and the video settings are
![image](https://user-images.githubusercontent.com/4198031/100114547-d4204980-2e71-11eb-9cd9-427d063fca93.png)

Does this help?

**Comment by duncanwebb** [comment] 2020-11-24 15:37
I don't think I was clear enough. In the following image, the coordinate widget has been right-clicked to open the setting screen and then the GPS tool is selected to choose a point, the area tool is chosen. When you left or right click it, then it puts point1 into the field. (Currently this is not working, it shows the coordinate but does not set the widget). All I was asking for was if you left-click it then it puts point2 into the widget and right click behaves as is.

![image](https://user-images.githubusercontent.com/4198031/100115063-60327100-2e72-11eb-8bb4-997a790a33ca.png)

I didn't mean to place a coordinate widget down, that wouldn't be so intuitive.

**Comment by desht** [comment] 2020-11-24 17:57
Give build 78 a go... should address both of the problems you're seeing here.

(I can't reproduce the pressure screen text wrapping problem no matter what resolution & scaling I use, but I forced a minimum width on the stat widget.  If it's still wrapping for you, I can increase it by a few pixels more...)

**Comment by duncanwebb** [comment] 2020-11-24 22:09
The area tool is working as expected to set the coordinates, many thanks. The only problem is that they are not saved in the coordinate piece.

Changing the GUI scale causes the numbers to display incorrectly. 1 it is fine and 4 it looks like this:
![image](https://user-images.githubusercontent.com/4198031/100156904-051c7080-2eaa-11eb-9f53-d735c06f7202.png)

**Comment by duncanwebb** [comment] 2020-11-24 22:12
Having said that I change the GUI scale back to 2 and it worked correctly but the pressure screen needed moving. Something strange here. The non-numeric screen looks odd.

**Comment by duncanwebb** [comment] 2020-11-24 22:15
It might be better to swap left and right about as right is red and left is green on the area tool.

**Comment by desht** [comment] 2020-11-25 08:02
This is really weird.  I can't make the pressure screen break at all. Looking at the code, it should only happen if that stat would be off the right-hand edge of the screen, but the stat positioning code should prevent that.  Try moving the stat to the left a bit and see if that makes a difference...

The 1.16 stat widget does do dynamic text wrapping dependent on how much horizontal space the widget has, and for some reason on your setup it thinks it has much less space than it actually does. I'll try something else and let you know when there's a build to test. 

> It might be better to swap left and right about as right is red and left is green on the area tool.

I'm aware of the GPS area tool buttons being the wrong way round, but I'm concerned about switching them now (sudden change of behaviour).  Maybe make it a config setting so people can keep the old behaviour if they prefer...

**Comment by duncanwebb** [comment] 2020-11-25 11:36
Not generally just when select the coordinate to put in the coordinate puzzle piece. The tool has a red and a green button, green button is on the left and red on the right so it makes sense that the right button is point1
![image](https://user-images.githubusercontent.com/4198031/100222514-7eec4280-2f1a-11eb-8628-f3e42799d610.png)

**Comment by desht** [comment] 2020-11-25 14:23
OK build 79 should hopefully resolve both of your issues.  LMB/RMB should function as expected on the area tool now, and I *hope* you won't see any more text wrapping on the pressure stat.

**Comment by duncanwebb** [comment] 2020-11-25 19:31
When I cycle through the GUI sizes and it gets fixed then it stays fixed. It looks better on the RHS, I was having more overlap on the LHS.

The GPS area tools is working just as I would expect that it does **not** set the constant, see https://streamable.com/4arb8j

Interesting that the Amadron tablet can be also used.

**Comment by desht** [comment] 2020-11-26 08:11
Oops, I forgot about the coordinate GUI, just tested the area GUI.  Easy fix though.

The Amadron tablet works because it too can store a blockpos (the tablet and the GPS tool implement [the same java interface](https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.3/src/main/java/me/desht/pneumaticcraft/api/item/IPositionProvider.java) , which is why they both work for selecting a blockpos, and also what makes them render the block preview in-world).

**Comment by desht** [comment] 2020-11-30 10:53
Fixed in 2.7.0 release (and 1.5.3 for 1.15.2)

**Closed as completed by desht** 2020-11-30 10:53 UTC
Labels: Bug, Fixed in Dev
