### ISSUE TITLE
Uneasy pipe module placement

### ISSUE THREAD

**Issue by Naheulf** [TeamPneumatic/pnc-repressurized#916] opened 2021-11-21 10:24 UTC
### Minecraft Version
MC 1.16.5
### Forge Version
Forge 36.2.4 (MCP 20210115.111550)
### Mod Version
1.16.5-2.14.4-258

### Description of the Issue

Add module to tubes is not as easy as it should be.

### Steps to Reproduce the Issue (Case 1)

1. Place a tube
2. Add a flow module
3. Place another tube in front of the flow module

### Expected Behaviour (Case 1)

The new tube should connect to the old one

### Actual Behaviour (Case 1)

The tube did not connect. (However  it did not reproduce in the video)

### Steps to Reproduce the Issue (Case 2)
1. Place at least 3 tubes in a row
2. Try to place a flow module  on the middle tube

### Expected Behaviour (Case 2)
Flow module should go on the targeted flow pipe

### Actual Behaviour (Case 2)
Flow module go on the tube side

### Steps to Reproduce the Issue (Case 3) (not on the video)
1. Connect a tube to some air provider
2. Air escape from the other tube side
3. Now place a flow module on that side

### Expected Behaviour (Case 3)
Air continue to escape

### Actual Behaviour (Case 3)
Air stop escape as if flow module act as cap.

### Any other comments?
First seen on a dedicated server with a large modpack. But able to reproduce in single player with only pneumaticraft.
Evidence video at https://www.youtube.com/watch?v=_QjUQIeenKs&t=157s
Inline module should go on the tube center to explain why we can't connect other tubes to the sides (see video)

**Comment by desht** [comment] 2021-11-22 09:35
Case 1: seems to be working for you. I couldn't reproduce this problem either.

Case 2: working as intended.  Inline tube modules (which are the flow and regulator modules) are not supposed to be placeable on a connected tube section, only on an open tube end, similar to how placing a flow meter on a pipe in real life would work - you need to break and reform the tube.  What is a bug is that workaround you used to place a flow meter on a tube section at right angles to the one you wanted...

Case 3: can't reproduce this.  The flow module always prevents air leakage once correctly attached to the end of a tube:

![2021-11-22_08 55 02](https://user-images.githubusercontent.com/736831/142831578-0319f431-96a9-4675-b3ba-6ca7538116b1.png)

**Comment by Naheulf** [comment] 2021-11-22 14:03
> Case 3: can't reproduce this. The flow module ~~always~~ prevents air leakage once correctly attached to the end of a tube:

That what i said. Both flow module and regulator module should __NEVER__ prevent air leakage similar to how they works in real life.

**Comment by desht** [comment] 2021-11-22 16:41
Ah, OK.  Yes, it might be more logical, but I'm not convinced it's worth actually changing (and would be negative from a QoL point of view).  So I'm not inclined to change that behaviour.

(From a "realism" point of view, imagine that inline modules have a built-in valve which shuts off air flow until a tube is connected to them...)

**Comment by desht** [comment] 2021-11-24 11:38
Fixed in 2.14.6 release

**Closed as completed by desht** 2021-11-24 11:38 UTC
Labels: Bug, Fixed in Dev
