### ISSUE TITLE
Flux Compressor Redstone Control Trouble

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#465] opened 2020-05-06 18:56 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-8
### Describe your problem, including steps to reproduce it
Two things here. 

First, the flux compressor doesn't seem to respect redstone control. When set to Enable on High it just keeps running without a signal. 

Second, the redstone control options are missing Enable on Low, contrary to other compressors. 
 
### Any other comments?

Oddly, the first issue only appears to happen when I have a charging module on the first pressure tube out of the compressor.... maybe this is outputting a redstone signal of its own that I'm unaware of?
![2020-05-06_14 54 09](https://user-images.githubusercontent.com/9543430/81216932-c674a680-8fa9-11ea-966b-e5e1089bcb17.png)

**Comment by MuteTiefling** [comment] 2020-05-06 20:25
![2020-05-06_16 24 33](https://user-images.githubusercontent.com/9543430/81224692-1bb6b500-8fb6-11ea-82b6-1c8cadefb25a.png)

Really seems to be related to the layout of the pipes. This layout works fine, for instance, but getting rid of that one extra pipe between the charging module and the compressor seems to make the redstone control fail

**Comment by desht** [comment] 2020-05-07 08:53
Well, the lack of "Low Signal" in the redstone tab is definitely a mistake, but I can't reproduce the main problem.  I put together a similar setup:
![image](https://user-images.githubusercontent.com/736831/81273850-67656f00-9047-11ea-8490-0721e590ef44.png)
...and it works fine.  Shuts off at 15 bar, where I set the Pressure Gauge to start emitting.

I can confirm that the Charging Module never emits redstone signals (nor does it care about incoming redstone levels).

**Comment by MuteTiefling** [comment] 2020-05-07 10:30
so weird. I just had it blow up on me again. I didn't even do anything to it... My armor had been sitting in the chest charging overnight and I just took it out. walked away and boom. 

I had it set to emit below 19, however. Figured that was enough. I'll keep an eye on it some more. I've got a security upgrade in it now though

**Comment by MuteTiefling** [comment] 2020-05-07 10:55
So I just started hearing the security upgrade. Startled me a bit, but here's what happened.

I had rebuilt everything and set the gauge to emit below 18 bar. I then dropped in my armor to charge again and puttered about my base a bit building some stuff. I wanted to go back to the nether and try to get some Ghast tears for the next flight upgrade (so hard to find these today). I went up to my charging setup and confirmed that the pressure was stable and the compressor was off. I then grabbed my armor out of the chest and a few moments later started hearing the hiss of the security upgrade firing. 

I took a look at the gui again for the compressor and saw it still said 'disabled by redstone' but it was building pressure and venting it. 

![2020-05-07_06 46 29](https://user-images.githubusercontent.com/9543430/81286738-8c4de800-902f-11ea-9316-4d8ff798c56c.png)

It eventually stopped again, but it would have blown for sure without that security upgrade in there.

**Comment by MuteTiefling** [comment] 2020-05-07 12:05
I'm able to reproduce this now consistently in this pack. I'll try in my test pack as well.

**Comment by MuteTiefling** [comment] 2020-05-07 13:06
I'm baffled. In my playthrough world, it's built with the back of the compressor facing west. All in one chunk. The heat sink is directly on the compressor, as is the windmill/solar generator. I even took the trouble of putting gravel under it in case it was some weird thing with it all being sitting on gravity blocks....

Recreating all of these conditions in my test world results in it working just fine. :(

Yet in the playthrough world, every time I remove items from the chest it starts acting up again. It's as if that update is triggering it to go somehow. It was the same with my original configuration too, where the charging module was right up against the compressor. Just placing it on the pipe was enough to trigger the bug. So maybe some weird block update thing?

Something new I've noticed as well is that in my playthrough world the little redstone particle effect on the pressure gauge never seems to go away... even when it reports it is outputting 0 signal. This is not the case in my test world. The particle goes away as expected when the target pressure is reached.

**Comment by desht** [comment] 2020-05-07 14:13
Yeah there's something really weird going on there.  I'll keep this open and see if I can reproduce it at any point.

Regarding the redstone particles, I've noticed that on occasion too, but it's another one of those annoying problems that disappears when I get set up to debug it :)  As far as I can tell it's just a sync issue (clientside module wrongly thinks there's a signal and plays particles).

**Comment by desht** [comment] 2020-05-07 14:17
Had a quick thought: you said it's generating even though the GUI says it's disabled by redstone.  Can you open the green tab (top right) and check how much air/tick it appears to be generating?  Also, try disconnecting the RF source (wind turbine) and see if the RF meter starts dropping.

I'm wondering if air is entering the system through some phantom source (aka a bug) rather than being generated by the Flux Compressor itself...

**Comment by desht** [comment] 2020-05-07 14:51
The other experiment to try would be to replace the flux compressor with an advanced liquid compressor and an infinite source of fuel (Liquid Hopper + Creative Upgrade can do this), but keep everything else the same.  That would give a clue as to whether it's a flux compressor problem or a more general problem...

**Comment by MuteTiefling** [comment] 2020-05-07 15:57
> I'm wondering if air is entering the system through some phantom source (aka a bug) rather than being generated by the Flux Compressor itself...

That would make a lot of sense because the pressure was coming in -very- fast. I'll see if I can get that set up here and let you know.

**Comment by MuteTiefling** [comment] 2020-05-07 16:03
Whelp, it's stopped doing it in my main world. But the phantom source of air sounds very plausible. Probably by adding the security upgrade it's eventually been able to 'empty' whatever that source is...

**Comment by desht** [comment] 2020-07-20 09:17
Going to close this one.  Feel free to reopen if you see it happen again :)

**Closed by desht** 2020-07-20 09:17 UTC
Labels: Bug
