### ISSUE TITLE
Drone not storing fluid

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#690] opened 2020-12-22 07:49 UTC
### Minecraft Version
1.16.4

### Forge Version
35.1.13

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.1-96

### Describe your problem, including steps to reproduce it

A simple program to import lava and to export this to a tank.

![image](https://user-images.githubusercontent.com/4198031/102861916-a1e21780-4430-11eb-9f86-ce5fadac387d.png)

What happened was the drone imported the lava but didn't export it to the tank. Right-clicking the drone with a tank didn't transfer any lava. Picking up the drone also showed that it contained no fluid.

![image](https://user-images.githubusercontent.com/4198031/102862263-1c129c00-4431-11eb-83af-9c6c4860d9ac.png)

### Any other comments?

This observation came from mining in the nether with a program controller. It looked like lava was being collected but there was nothing in the tank. Also, with the program controller I expected that it would mine all blocks but it seems to be behaving strangely with lava and maybe oil. Since the mini drone is a virtual drone it can go through walls it should be impervious to lava and other fluids. This can be problematic with the odd lava source block that is in a wall as the lava spreads out and covers the whole area.

You know what would be useful is a void puzzle piece to delete items and fluid.

Many thanks for all your hard work.

**Comment by desht** [comment] 2020-12-22 09:48
Confirmed.  Something's not right with fluid import from the world.

There is actually already a "Void Items" piece (added quite recently), which will void any items the drone is carrying (it takes item filters too).  This is pretty much intended for quarry-type programs.   It doesn't void fluids, though.  Maybe a separate "Void Fluids" piece would be useful.

**Comment by desht** [comment] 2020-12-22 09:57
Possibly a "void fluids" option in the "Dig" widget?  That feels fairly balanced for a quarry - there's the easy option of just voiding any water/lava/etc. you're digging, or if you actually want the fluids, you need to write a slightly more complex program which tries to import fluids before digging blocks out.  Although voiding water probably wouldn't work too well (infinite sources).

**Comment by duncanwebb** [comment] 2020-12-22 11:08
Definitely a puzzle piece to void fluids as this is consistent with void items. Maybe you don't want to void all fluids like Crude Oil (the Nether has oil - new?). Originally, I thought that it would be easy to mine in the nether but it turned out to have quite a few gotchas, first is the maximum number of blocks (can't remember the limit 2^x), next was not pulling the tools from the programmable controller, tricky with smart chests, third was lava source blocks in the sides of the quarry. (Need to increase the area of import fluid by a number of blocks)

This is the current iteration.

![image](https://user-images.githubusercontent.com/4198031/102882139-3ad35b80-444e-11eb-92c9-f7bd1fb310d5.png)

**Comment by desht** [comment] 2020-12-22 11:50
Yeah oil in the nether is new in 1.16.  You should only ever see oil lakes in Basalt Delta biomes, though.  Figured I'd add it to celebrate the big vanilla nether revamp in 1.16 :)

TBH, you'll probably have a much better time using a gas lift to suck up oil lakes (possibly also lava) than drones.  I have however fixed the bug that completely breaks fluid importing from the world (was a really dumb one - one line fix).  Will be pushing a new dev build today hopefully.

The maximum limit for drone areas is 250,000 blocks by default, though you can raise this in the config (pneumaticcraft-common.toml -> General -> `max_programming_area`).  Be careful, though - too high a limit will chew up RAM.  These areas are stored in memory so the drone can sort/iterate through them.

Is the smart chest tool pulling issue due to the inability to specify item NBT?  By the way, if you're using a Programmable Controller, there is a *much* simpler option: in one of the right-hand tabs, there's a checkbox to make the PC charge the "drone's" held tool (both pressure and RF items are supported).  Tick this, and the tool won't need to be extracted for recharging at all, although the PC will of course consume more air (or RF) to keep the tool charged.

**Comment by duncanwebb** [comment] 2020-12-22 15:30
Found a small oil lake in nether wastes 18 buckets. Normally, I use a gas life for oil but in this case, the program controller was being used to quarry an area and so it is possible to run into an unexpected oil lake.

Thanks for the fix.

I want the smart chest not to pull the mining tools from the program controller (unbreakable supremium pickaxe and paxel) so the main items are whitelisted and the remaining slots are closed. Other items, like mushrooms, are collected by a drone and put into a chest. Logistics would be a better solution but requires air.

I was watching how the mini-drone behaved in this case, it was mining underneath the lava but missed some blocks. The pattern was up and down until it hit the lava and then mined an arbitrary pattern.
![2020-12-22_12 38 48](https://user-images.githubusercontent.com/4198031/102904741-6ff1a500-4472-11eb-883b-520360d5f6a6.png)
![2020-12-22_15 54 26](https://user-images.githubusercontent.com/4198031/102904753-73852c00-4472-11eb-8cd3-e4694ddb04c3.png)
![2020-12-22_15 55 43](https://user-images.githubusercontent.com/4198031/102904767-78e27680-4472-11eb-9198-981004a4af82.png)

**Comment by desht** [comment] 2020-12-22 16:16
I'll look into that odd mining behaviour.  Not sure what's going on there.

Did you know there's a trick to doing wireless pressure transfer via the Aerial Interface?  Put some Reinforced Canisters in a 
vanilla Ender Chest, and get two Aerial Interfaces, plus two Charging Modules.  Set one side of each Aerial Interface to "Ender Inventory" - the Charging Modules will point at those sides.

One Aerial Interface will be on your main high-pressure network in your base, and it will charge up the canisters (that's your air buffer), and the other will be in the nether, using the air from those canisters.  This does need you to stay online, since the vanilla ender inventory is attached to the player.

You can of course also use other ender storage mods to do the same thing, and that doesn't require you to be online, assuming everything is properly chunkloaded...

**Comment by duncanwebb** [comment] 2020-12-22 16:47
Ah cool, I've been reading the hints in the manual for Reinforced Canisters but wasn't quite sure how to implement it. I'll give this a try and demonstrate it in the next video.

**Comment by duncanwebb** [comment] 2020-12-23 10:41
Do you mean like this?

The provider side
![2020-12-23_11 29 40](https://user-images.githubusercontent.com/4198031/102987305-69b30580-4512-11eb-8764-a5e4e6919281.png)

The consumer side
![2020-12-23_11 28 59](https://user-images.githubusercontent.com/4198031/102987487-ada60a80-4512-11eb-8892-c156f9ab22ce.png)

The two Reinforced Canisters have 7.5 bar, they charged up and then stopped, The consumer side shows the advanced pipe has 7.5 bar. But the Aerial Interface has 0 bar.

I placed an unpressured vortex cannon on the compressed iron block, it cooled the compressor very effectively - not sure if this is what is intended.

**Comment by desht** [comment] 2020-12-23 13:09
No, more like this:

![2020-12-23_13 08 40](https://user-images.githubusercontent.com/736831/102998892-ff08c680-451f-11eb-875e-2f3c08481fbe.png)

It's necessary to loop the Charging Module connector back into each Aerial Interface, as above.

> I placed an unpressured vortex cannon on the compressed iron block, it cooled the compressor very effectively - not sure if this is what is intended.

Not sure what you're referring to here; separate issue for this please?

**Comment by duncanwebb** [comment] 2020-12-23 16:09
Oh I see, this works. Many thanks. BTW, when two ender chests are placed down the canister stops charging. At least in the same dimension.

Forget the comment about the vortex tube, it retained some pressure from a previous installation.

**Comment by desht** [comment] 2020-12-23 16:31
> Oh I see, this works. Many thanks. BTW, when two ender chests are placed down the canister stops charging. At least in the same dimension.

That's very weird, since ender chests don't really have an inventory of their own.  They are just a view into the player's own ender inventory, which is just a single inventory (which is why every player sees a different inventory when they open it, and why hoppers can't insert/extract from them).  I'll do some testing on that, though.

Update: tested and confirmed canisters in the ender chest charge just fine regardless of how many ender chest blocks are actually placed.  Must be something else on your end stopping the charging, I suspect it was just a coincidence that you placed a second ender chest down.

**Comment by duncanwebb** [comment] 2020-12-24 14:30
One thing I discovered is when I leave the nether the charging module stops working which is expected as I forgot to load the chunk. When returning the pressure has dropped to 10 bar and is not filling the reinforced canisters, which show a pressure of 19 Bar. Breaking and replacing the aerial interface and everything works again.

**Comment by desht** [comment] 2020-12-24 14:57
Possibly because the aerial interface lacks enough pressure to do the transfer, though it's interesting that it started again when replaced...

Also possible there's a caching issue with the interface being unloaded and reloaded. I'll do some testing on that.

**Comment by desht** [comment] 2020-12-28 15:42
Fixed in 2.8.2 release

**Closed as completed by desht** 2020-12-28 15:42 UTC
Labels: Bug, Fixed in Dev
