### ISSUE TITLE
java.lang.NullPointerException: Feature placement

### ISSUE THREAD

**Issue by lordudi** [TeamPneumatic/pnc-repressurized#1066] opened 2022-08-02 09:54 UTC
### Describe the bug

[crash-2022-08-02_12.39.59-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9241022/crash-2022-08-02_12.39.59-server.txt)
I uploaded the crash report to here cause it's to big to pastebin I don't understand the bug only that it connected to world generation feature placement and it is a problem with pneumaticcraft and mekanism

### How to reproduce the bug

don't know

### Expected behavior

not crash the game

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.16.5-2.15.11-334.jar

**Comment by desht** [comment] 2022-08-02 12:32
Dupe of #1052

**Closed as completed by desht** 2022-08-02 12:32 UTC
Labels: Bug, duplicate
