### ISSUE TITLE
ATM9 server: Exception ticking world

### ISSUE THREAD

**Issue by wolekhenryk** [TeamPneumatic/pnc-repressurized#1389] opened 2024-12-28 20:52 UTC
### Describe the bug

Minecraft server version: 1.20.1
Full error: [https://pastebin.com/67ELb7jX](pastebin)

This occurred during server startup (hosted on Ubuntu server with OpenJDK 21 and 32GB of RAM available). The server was running smoothly until today.

### How to reproduce the bug

Running the standard `./run.sh` script available inside ATM9 folder

### Expected behavior

Smooth server startup

### Which Minecraft version are you using?

1.20.1

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.18+mc1.20.1.jar

### Crash log

https://pastebin.com/67ELb7jX

**Comment by desht** [comment] 2024-12-28 22:31
Dupe of #1387

**Closed as completed by desht** 2024-12-28 22:31 UTC
Labels: Bug
