### ISSUE TITLE
ATM 9 Pnuematic Craft Crash Report

### ISSUE THREAD

**Issue by mikez556** [TeamPneumatic/pnc-repressurized#1388] opened 2024-12-28 12:41 UTC
### Describe the bug

Clients DC from server and Server Crashes and reboots,  This repeats everytime when users is in the area of the fault,

temporary fix is to relocate the players away but problem occurs each time the problem chunk gets rendered.

### How to reproduce the bug

unable to easily reproduce as it's a rendered chunk

### Expected behavior

no crashing 

### Additional details

This is on All the Mods 9 - ATM9 1.20.1 (All the Mods 9-1.0.0)

### Which Minecraft version are you using?

1.20.1

### Which version of PneumaticCraft: Repressurized are you using?

6.0.18+mc1.20.1

### Crash log

https://pastebin.com/gy6BtP0H

**Comment by desht** [comment] 2024-12-28 22:32
Dupe of #1387

**Closed as completed by desht** 2024-12-28 22:32 UTC
Labels: Bug
