### ISSUE TITLE
Cannot craft Yeast with Brown Mushrooms in TPP

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1345] opened 2024-09-01 23:48 UTC
### Describe the bug

Red mushrooms work fine. Brown mushrooms never trigger the recipe.

Both mushrooms still have the `#c:mushrooms` tag required by the recipe.

### How to reproduce the bug

1. Setup TPP for yeast with water/brown mushrooms
2. Supply required heat
3. Nothing happens
4. Swap to Red Mushrooms and it works immediately

### Expected behavior

Either mushroom should work

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.1.1

**Comment by desht** [comment] 2024-09-03 09:58
Can't reproduce this, sorry. Both red and brown mushrooms working fine here, in dev and on a test server.

Sure you haven't done something to the item tags?

**Comment by MuteTiefling** [comment] 2024-09-03 10:52
Quite sure. The recipe cycles between both and I double checked with advanced tooltips.

**Comment by desht** [comment] 2024-09-03 11:36
Not sure what to say then... definitely working here :/

**Comment by desht** [comment] 2024-09-05 15:54
Oh, I've just spotted the problem. Pure chance that it failed with the brown mushrooms and not the red ones...

I'm guessing you piped in water at less than a bucket a time, and the machine negatively cached a failed recipe with insufficient water and brown mushrooms. By the time you added a red mushroom, there was >= 1000mB water in the machine so it worked.

My fault, taking the amount of water in the machine into account when checking for a valid recipe; should only be checking the fluid, not the quantity at that stage. Will fix this for the next release (out in the next day or so).

**Comment by MuteTiefling** [comment] 2024-09-05 17:20
Ah nice. Yeah, that sounds like what would have happened.

**Comment by desht** [comment] 2024-09-07 07:49
Fixed in 8.1.2

**Closed as completed by desht** 2024-09-07 07:49 UTC
Labels: Bug, Fixed in Dev
