### ISSUE TITLE
Unexpected Crash and Bug

### ISSUE THREAD

**Issue by arcadymtr** [TeamPneumatic/pnc-repressurized#111] opened 2018-02-08 20:08 UTC
### Minecraft Version
1.12.2

### Forge Version
1.12.2-forge1.12.2-14.23.1.2604

### Mod Version
pneumaticcraft-repressurized-1.12.2-0.4.0-136

### Describe your problem, including steps to reproduce it
as requested, i already wrote everything about my issue/doubts over there:
http://tiny.cc/egwzqy ( refer to //www.minecraftforum.net/)

thanks for your help/assistance.

**Comment by desht** [comment] 2018-02-08 21:11
Can you provide a link to a full stack trace please, and also an export of the done program at fault (you can use the Programmer pastebin function to do this)?

**Comment by arcadymtr** [comment] 2018-02-09 00:13
first off, thank you very much for your dealing. i didn't expect such efficiency, honestly. it's a pleasure to help you somehow.

i ask you to be patient, please: if i understood correctly, you wanna me to interact with the Programmer, click on "Import/Export" button and copy Drone's workflow/program. am i right? if so, there the link:

https://pastebin.com/44rpj7Bs

**Comment by arcadymtr** [comment] 2018-02-09 00:50
since i'm posting that. i would like to share with you another crash-report related to Aphorism Tile. basically it works fine only the first time, from now and then you will get crashes when you try to interact with the Tile (ie. "pickaxing" and replacing it, or right-clicking on it).

https://pastebin.com/6C2FQXSZ

**Comment by desht** [comment] 2018-02-09 08:46
The Aphorism crash is due to it not being able to get any drama text from the drama server (http://mc-drama.herokuapp.com/raw).  This is just a "fun" feature, and you can disable it by setting ``B:aphorismDrama = false`` in the mod config.  But I'll fix that crash for the next release.

**Comment by desht** [comment] 2018-02-09 08:51
And yes, that drone program paste is exactly what's needed, thanks.

**Comment by arcadymtr** [comment] 2018-02-09 23:43
thank you very much. i could "fix" Aphorism by following your suggestions.

is there anything i can do to assist you, by providing any further information? maybe, would you need a fax-simile of Drone's workflow in order to compare MC 1.12.2 with MC 1.7.10 ? just asking.

**Comment by desht** [comment] 2018-02-10 10:12
I couldn't get that program to crash; it worked OK when I loaded it.  However, it does look like a null itemstack got in there somehow.  I've made a few fixes which may or may not solve your crashes.  Can you try this build please:  http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/138/artifact/build/libs/pneumaticcraft-repressurized-1.12.2-0.4.0-138.jar

(Also, although the program didn't crash, it didn't do anything either because of a mistake on my part - this build fixes that too, and the drone now either suicides or goes to standby correctly based on how much dirt is in the chest).

If that doesn't fix your problem, can you post a link to a _full_ stack trace of the NPE you're getting?

**Comment by arcadymtr** [comment] 2018-02-10 21:12
no, wait a moment.

when i wrote about "crashes" i was referring to MC 1.7.10 - indeed i didn't ask you to fix such old bugs/crashes since you fixed those for MC 1.12.2. i just reported that stuff, anyway. - finally, i started to play to MC 1.12.2 and i noticed all the rest (the "Condition: Items" and Aphorism not working as expected, and other little things).

i'm sorry if i was not clear enought. - however i just downloaded the newest version of your mod, and i will let you know as soon as possible.

thank you very much.

**Comment by arcadymtr** [comment] 2018-02-10 22:04
i tried the new version of your mod, the "Condition: Items" bug seems fixed. seriously, great work.

if you did not mind, i would ask you a major effort in order to implement a new Puzzle. i am thinking about a Puzzle that could help the Drone to assist the player to transfer or emit some kind of energy (Joule, RF or Redstone signal).

in my ignorant opinion, another good alternative could be the following: you might want the Charging Station to expel and spawn a Drone when it's fully recharged.

still, kindly i would like to clearly understand why most of "Conditions" can support more than one "Item Filter" - respectively, on the right and left side. in most of cases i attach a single "Item Filter" (on the right side) and that is.

i know these sounds like silly requests and i'm pretty sure you receive dozen of those. i would like to express my gratitude to you in this way.

best regards,
arcadymtr.

**Comment by desht** [comment] 2018-02-12 08:49
* For Energy transfer, I was going to point you to the "Import RF" and "Export RF" puzzle pieces, but then I realised that due to a bug, these pieces are not getting registered!  This will be fixed in the next update and RF (actually Forge Energy, but RF-compatible) transfer will work again, like it did in 1.7.10.  Redstone does work though: see the "Emit Redstone" piece.

* For Charging, if you put a Dispenser Upgrade in your Charging Station, it becomes a charge pad, and will charge anything standing above it: players and drones.  If a drone gets low on air, it will automatically seek and land on any available charge pad, and go into standby mode until fully charged, and then carry on with its tasks.  Useful?

* When you have multiple Item Filter pieces, it means "match any".  E.g. if you wanted a drone to pick up (say) a pickaxe and a shovel (useful for quarrying), you could have an Inventory Import piece, and add two Item Filters on the **right**, one for pickaxe, and one for shovel.  Then the drone will try to take both items from the inventory.

* Item Filter pieces on the **left** mean to blacklist the piece, so the condition will not match item in the blacklist.

**Comment by arcadymtr** [comment] 2018-02-12 17:27
about "Dispenser Upgrade", i totally agreed. it's really an useful option and help to increase the well-known learning curve for this mod. by the way i still enjoy to check Drone's Pressure by myself.

thank you very much for your explanation about "Item Filter/s".

keep up the good work, congratulations!

**Comment by MineMaarten** [comment] 2018-02-12 18:09
And as an addition, you might use multiple item filters on the right side, to whitelist multiple different items :)

**Comment by arcadymtr** [comment] 2018-02-12 21:58
thank you, @MineMaarten .

lastly i'm testing Coordinate and Coordinate Operator Puzzle(s).

think about the following (basic) Program:
- your character still stands on a block of Cobblestone
- the Drone will suicide if the previous condition/statement is verified successfully

"$player" marks player's character coordinates. that said, the "real" ground seems to be found at [X, Y-2, Z] instead of [X, Y-1, Z]. on the contrary, if you want the Drone to fly above your character's head, the new coordinates will be properly calculated as expected [X, Y+1, Z]. - same old question if you want to cross-check Drone's position ($drone) respect something else.

is all that intended, or something behind the scene is getting buggy?

if you didn't mind, i would suggest you to consider the silly idea to upgrade such Puzzles by taking inspiration from RFTools Shape Card (Quarry). so, setting up a new dummy area will look more logic and easy. in particular it will be, i guess, if you just need to determine what surround the Drone.

i hope to have been clear, and thanks for your attention @MineMaarten @desht

**Comment by desht** [comment] 2018-02-13 08:32
> "$player" marks player's character coordinates. that said, the "real" ground seems to be found at [X, Y-2, Z] instead of [X, Y-1, Z]. on the contrary, if you want the Drone to fly above your character's head, the new coordinates will be properly calculated as expected [X, Y+1, Z]. - same old question if you want to cross-check Drone's position ($drone) respect something else.
> is all that intended, or something behind the scene is getting buggy?

That seems fine to me.  The location returned from ``$owner`` or ``$player=<name>`` is the location of the player's head.  So (x, y+1, z) is the block above the player's head, and (x, y-2, z) is the block below the player's feet.  (x, y-1, z) would be the block that the player's lower half occupies.

For ``$drone``, it would be y+1/y-1 to check above/below, because drones only occupy a single block height.

>if you didn't mind, i would suggest you to consider the silly idea to upgrade such Puzzles by taking inspiration from RFTools Shape Card (Quarry). so, setting up a new dummy area will look more logic and easy. in particular it will be, i guess, if you just need to determine what surround the Drone.

Yes, making it easier to select areas is something we have discussed.  I believe @MineMaarten has some ideas about that...

**Comment by arcadymtr** [comment] 2018-02-13 13:48
maybe i'm doing something wrong, i crash everytime i try to order an item by using Amadron. precisely, if i click on "GPS icon", the client will crash instantly. it doesn't matter if i own a GPS or not, the result won't ever change.

there the log:
https://pastebin.com/q6v5LAwd

**Comment by desht** [comment] 2018-02-13 13:52
Yeah, I think I see what the problem is there, but I'm not at my dev environment right now.  But it should be an easy fix.

Also, can you use a new issue in future for separate unrelated problems?  It makes it a lot easier to keep track of things :)

**Comment by arcadymtr** [comment] 2018-02-13 14:03
roger!

meanwhile i wait for the next update/hotfix, i guess you can close this issue then.

thank you for all your efforts!

**Closed** 2018-02-17 16:03 UTC
