### ISSUE TITLE
Elevator going boom

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#526] opened 2020-06-17 10:54 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.9
### Mod Version
1.15.2-1.2.2-30
### Describe your problem, including steps to reproduce it

I've had a largish elevator installed for about a week without issues. There was some funky stuff setting it up initially, but I couldn't reproduce any of it then.

Today I went down the elevator and walked away from the computer for a bit. When I came back, I had a bunch of elevator frames in my inventory... Looking around I saw that the top middle elevator block had disappeared. I think it may have blown up, but I wasn't there when it happened, unfortunately.

Not sure what was going on, I just dropped in a new elevator frame and started hooking everything back up. At this point, however, the middle of the elevator simply wouldn't go up and down with the rest of the elevator. It's as if it were disconnected from the rest of it. So, I figured I'd just tear it all out and rebuild. This was one of the funky things I had happen when building it the first time, by the way.

Now, I didn't want to waste all of the air in the elevator, so I used a pneumatic wrench to pull them up. I have the feeling this may be part of the key to this issue. I dropped down all of the blocks and frames again, hooked it back up to the air... and a moment later the entire thing blew up. 

Then I started recording and put it all back together again. As soon as I hooked up the air, the gauge in the elevator block started hopping all over the place. Up and down and well into the red. Shortly after, it blew again. 

https://streamable.com/7cxfwn

After a restart and a fresh rebuild, I was able to get it working again, so I doubt I'll be able to reproduce this at will. 

### Any other comments?

It does look like there was an error logged on this, so hopefully it'll help. 

[2020-06-17-1.log.gz](https://github.com/TeamPneumatic/pnc-repressurized/files/4791975/2020-06-17-1.log.gz)

**Comment by desht** [comment] 2020-06-17 13:56
Hmm, that doesn't look too good.  I'll do what I can to reproduce that, but sounds like it might be tricky...

I don't think the error is the cause of the problem here - it's invalidating the air handler capability when the TE is removed (i.e. when it exploded), but wrongly doing that on the client - I need a check  and only do that on the server.  But I don't believe that's the cause of the problem.

I wonder if it's something to do with the charging module and regulator module being so close - are they actually on the same tube section?

**Comment by MuteTiefling** [comment] 2020-06-17 17:06
They are on the same section, yes. I'll put another pipe between them and keep an eye on it. 

In any case, restarting did seem to allow me to rebuild without further issue. So I suspect I'll just have to wait and see for a while. 

I also just checked the chunk boundaries. It's not falling on the tube section, but the boundary is effectively splitting the elevator in half. The front 6 columns are in one chunk and the back 3 columns are in another. I hope that's not what's slowly breaking it because I really don't want to move this one :(

**Comment by desht** [comment] 2020-06-17 17:53
As long as both chunks stay loaded there shouldn't be a problem...

**Comment by MuteTiefling** [comment] 2020-06-18 00:46
I'm not chunk loading either of them, so as I leave the area they'd probably unload at different rates :(

**Comment by desht** [comment] 2020-06-18 07:14
Yeah, that *might* cause problems...

Anyway I'll keep this open and monitor for issues.

**Comment by desht** [comment] 2020-06-19 10:40
By the way, the reason that one elevator didn't work after you placed it back down is that elevators are in redstone-controlled (as opposed to caller-controlled) mode by default when placed.  The Elevator Caller block is what auto-switches detected elevators to caller mode, when it's placed down, or rotated etc.  But it won't update an elevator base that's been placed *after* it - that could be a server performance nightmare, constantly needing to check for elevators.

So the easy fix there is just to switch the elevator back to caller mode in the GUI redstone tab after replacing it.  I could probably make that a bit more intuitive by checking for other elevator neighbours on placement, and copying their redstone mode...

**Comment by MuteTiefling** [comment] 2020-06-20 00:44
Ah, that makes a lot of sense. I had never noticed the default since I've only ever used them will callers and normally place them afterwards. It's just been these odd occasions where things go wrong that they're already in place. Good to know. Thanks!

**Comment by MuteTiefling** [comment] 2020-06-24 01:43
Just reporting in to say that this has remained stable since rebuilding it. I'm not sure if it's because I've separated the charging module and the regulator (I do still use that trick elsewhere with no ill effects) or if the whole incident was just due to a series issues  caused by simple bad luck and bad lag.

**Comment by desht** [comment] 2020-07-14 08:39
Wonder if this is also related to #550  ?

**Comment by MuteTiefling** [comment] 2020-07-14 10:55
Potentially, yeah. I do tend to load things up with volume upgrades, if that was somehow part of the trigger. That build, however, has been working without issue for a while now.

**Comment by desht** [comment] 2020-07-20 09:14
Gonna close this one, I think we're good for now.  Feel free to reopen if you see a re-occurrence :)

**Closed as completed by desht** 2020-07-20 09:14 UTC
Labels: Bug, Can't Reproduce
