### ISSUE TITLE
Higher tier jet boot upgrade shows up wrong on tooltip

### ISSUE THREAD

**Issue by tDegan** [TeamPneumatic/pnc-repressurized#1038] opened 2022-06-26 10:29 UTC
### Describe the bug

One tier 5 jetboots upgrade is shown as 5 tier 1 upgrades:

![2022-06-26_12 18 59](https://user-images.githubusercontent.com/103054313/175809817-7c5de77c-ba10-48aa-bdaa-df1edb08874d.png)

Happens with tier 2-4 as well.

### How to reproduce the bug

1. put a tier 5 jet boots upgrade in an pneumatic boot.
2. Look at the tooltip

### Expected behavior

Show `1 x tier 5` upgrade

### Additional details

As far as I can tell it's only visual. Higher tier upgrades still unlock advanced features (like builder mode)

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.3.0-104

**Comment by desht** [comment] 2022-06-26 11:33
Yes, the problem is purely visual. I'll see about fixing it for the next release (internally PNC considers 5 of a tier 1 upgrade equivalent to 1 tier 5 upgrade, but for display purposes it should be different).

**Comment by desht** [comment] 2022-07-12 11:28
Fixed in 3.3.1 release

**Closed as completed by desht** 2022-07-12 11:28 UTC
Labels: Bug, Fixed in Dev, Minor
