### ISSUE TITLE
Pneumatic Helmet crashes game

### ISSUE THREAD

**Issue by greengameplayer** [TeamPneumatic/pnc-repressurized#431] opened 2020-03-05 14:51 UTC
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2846
### Mod Version
1.12.2-0.11.10-385
### Describe your problem, including steps to reproduce it
Put on a pneumatic helmet, game hangs then crashes.
### Any other comments?
https://pastebin.com/SfSpQJrN
I've attached the Twitch modpack I use to this. This crash happens on a 1.12.2 server.
*this was the wrong file, see below*

**Comment by desht** [comment] 2020-03-05 16:39
This definitely falls under the "should never happen" and also the "I can't reproduce it" categories.

I can add an easy workaround to prevent that crash, but I have no idea why the method in question is returning null at the point in your crash, and makes me wonder what is wrong elsewhere...

**Comment by desht** [comment] 2020-03-05 16:50
Can you try build 387+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and let me know if that helps?

**Comment by greengameplayer** [comment] 2020-03-05 19:27
Uploading mod to multiplayer server now, will have answers in about 30 minutes.

**Comment by greengameplayer** [comment] 2020-03-05 20:20
D'OH... I gave you the wrong pack. So sorry about that...
https://drive.google.com/open?id=1E__dVg9CB8-zARvPyL9yxAKblubpDsjI

**Comment by greengameplayer** [comment] 2020-03-05 20:41
Okay, I can now put the helmet on. However no GUI is shown and when settings are accessed the entire game freezes, then crashes.
https://pastebin.com/WH8tNySV

**Comment by desht** [comment] 2020-03-06 08:06
I honestly don't know what's going on there.  Clearly something's badly broken, but I can't reproduce the problem, and I can't see how it would happen either.  I'll continue to investigate though.

**Comment by desht** [comment] 2020-03-13 10:17
Hopefully fixed in 0.11.11 release

**Closed by desht** 2020-03-13 10:17 UTC
Labels: Bug, Can't Reproduce, Response Needed
