### ISSUE TITLE
[1.14.4] Apostrophes in signs can cause client-side "missing method definition"

### ISSUE THREAD

**Issue by noobanidus** [TeamPneumatic/pnc-repressurized#449] opened 2020-04-17 05:05 UTC
1.14.4
28.2.3
1.0.0-8

https://paste.ubuntu.com/p/vwsx3MGpGW/

**Comment by desht** [comment] 2020-04-17 13:08
Confirmed.  Looks like `ArrayUtils` is not present in the obfuscated client.  Will implement a local array insertion method for this.

**Comment by desht** [comment] 2020-04-17 16:19
Fixed in 1.0.1 release

**Closed by desht** 2020-04-17 16:19 UTC
Labels: Bug, Fixed in Dev
