### ISSUE TITLE
Crash with PneumaticCraft:Repressurized & Ice and Fire: Dragons

### ISSUE THREAD

**Issue by Snifi0** [TeamPneumatic/pnc-repressurized#794] opened 2021-04-15 14:39 UTC
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### I instantly crash when I spawn a drone next to a cyclops

I think this is the log to the error
--------------------------------------------------------------------------------------------------------------------------------
[16:10:25] [Server thread/FATAL]: Preparing crash report with UUID d9046c44-6215-424c-b82b-56b696a38def
[16:10:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
    at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
    at net.minecraft.server.MinecraftServer$$Lambda$15591/1682631585.run(Unknown Source) [?:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: com.github.alexthe666.iceandfire.pathfinding.PathNavigateCyclops cannot be cast to me.desht.pneumaticcraft.common.ai.EntityPathNavigateDrone
    at me.desht.pneumaticcraft.common.ai.DroneMovementController.func_75641_c(DroneMovementController.java:43) ~[?:1.16.5-2.11.4-170]
    at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:692) ~[?:?]
    at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
    at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
    at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
    at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
    at me.desht.pneumaticcraft.common.entity.living.EntityDrone.func_70071_h_(EntityDrone.java:479) ~[?:1.16.5-2.11.4-170]
    at net.minecraft.entity.Entity.func_70098_U(Entity.java:1612) ~[?:?]
    at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2576) ~[?:?]
    at net.minecraft.world.server.ServerWorld.func_217459_a(ServerWorld.java:638) ~[?:?]
    at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:618) ~[?:?]
    at net.minecraft.world.server.ServerWorld$$Lambda$16286/99893851.accept(Unknown Source) ~[?:?]
    at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
    ... 6 more

**Comment by desht** [comment] 2021-04-15 16:17
I think I see the problem here, although I couldn't reproduce it myself.  Cyclopses like to pick up other entities (which replaces their path navigator).  Should be an easy fix, hopefully.

**Comment by desht** [comment] 2021-04-17 06:25
Fixed in 2.12.0

**Closed as completed by desht** 2021-04-17 06:25 UTC
Labels: Bug, Fixed in Dev
