### ISSUE TITLE
1.21 Neoforge bugs

### ISSUE THREAD

**Issue by EnotScript** [TeamPneumatic/pnc-repressurized#1322] opened 2024-08-02 16:12 UTC
### Describe the bug

1. The order does not work in the tablet of the amadron. When you click place, nothing happens.
2. Heat Frame recipes not working.
![image](https://github.com/user-attachments/assets/a6f4a2a0-d37d-43d9-a210-285f11af399c)

### How to reproduce the bug

Try place order.
Check recipe. + Try make any recipe.

### Expected behavior

Fix.

### Which Minecraft version are you using?

1.20.4

### Which version of PneumaticCraft: Repressurized are you using?

8.0.0 MC-1.21

**Comment by EnotScript** [comment] 2024-08-04 08:44
3. Logistics drone not working.
4. The entity tracker does not turn on. - debugging drones doesn't work because of this either.

**Comment by desht** [comment] 2024-08-04 21:05
1. Confirmed
2. Confirmed
3. Can't reproduce. Logistics drones working fine here, please provide more info to reproduce the problem.
4. Confirmed, already fixed in dev.

**Comment by EnotScript** [comment] 2024-08-04 21:35
3. Now everything works fine, perhaps there was a conflict before the modpack update.
I would like to add that the defender drone has very poor pathfinding. If an enemy stands on a pipe from any mod, it becomes unreachable for him in close combat. 
If I find anything else, I will definitely write.

**Comment by desht** [comment] 2024-08-04 21:38
That's almost certainly not a bug with the drone but with the other mod not correctly declaring the pipe as non-pathfindable.  Try getting a vanilla mob to walk across the pipe (e.g. tempt a cow with wheat) and see if gets stuck.

**Comment by EnotScript** [comment] 2024-08-04 22:08
![image](https://github.com/user-attachments/assets/c0eea312-9344-4871-8e38-1834ec8b9edc)
![image](https://github.com/user-attachments/assets/aa79b305-6504-4f52-a2e2-beba7ce9eeff)
![image](https://github.com/user-attachments/assets/0cb69457-15d3-4aca-8170-0b5ebc0c012b)
This seems odd. Even if he manages to aggro an enemy, if the enemy steps on an incomplete block (including a chest), he stops and does not try to kill it. 
Without debugging it becomes difficult to understand.

**Comment by desht** [comment] 2024-08-05 07:40
Interesting.  I'll take a look into that, that's definitely not intended behaviour.

**Comment by desht** [comment] 2024-08-05 21:30
All the issues should be resolved in the 8.0.1 release. Would appreciate as much drone testing as you can do - I believe the change I made should help a lot, but there is the possibility of side effects in other pathfinding situations...

**Closed as completed** 2024-08-05 21:30 UTC
Labels: Bug
